import fs from 'node:fs';
import assert from 'node:assert/strict';
import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';
import {doc,collection,getDoc,getDocs,setDoc,updateDoc,serverTimestamp,writeBatch,query,where} from 'firebase/firestore';
const env=await initializeTestEnvironment({projectId:'demo-science-vault-access',firestore:{host:'127.0.0.1',port:8089,rules:fs.readFileSync(new URL('../firestore.rules',import.meta.url),'utf8')}});
const subjects=['Physics ATAR','Chemistry ATAR','Biology ATAR','English ATAR'];
const profile=(uid,role,extra={})=>({email:uid+'@example.invalid',displayName:uid,role,status:'pending',permissions:{},registrationVersion:2,yearGroup:role==='student'?11:0,subjects:role==='student'?subjects:[],classCode:role==='teacher'?'ABCD2345':'',createdAt:serverTimestamp(),updatedAt:serverTimestamp(),...extra});
const ctx=uid=>env.authenticatedContext(uid,{email:uid+'@example.invalid',email_verified:true}).firestore();
const student=ctx('student'),other=ctx('other'),teacher=ctx('teacher'),stranger=ctx('stranger'),owner=ctx('owner'),guest=env.unauthenticatedContext().firestore();let count=0;const ok=async p=>{await assertSucceeds(p);count++},deny=async p=>{await assertFails(p);count++};
const room=(uid,code)=>({ownerUid:uid,name:'Test class',code,createdAt:serverTimestamp()});
const enrollment=()=>({studentUid:'student',displayName:'student',yearGroup:11,joinedAt:serverTimestamp()});
const task=()=>({title:'Physics task',kind:'assessment',course:'Physics ATAR',yearGroup:11,unit:'',topic:'',instructions:'Practise',dueDate:'',minutes:0,questionIds:['q1'],url:'student-quiz.html',ownerUid:'teacher',createdAt:serverTimestamp()});
const progress=(extra={})=>({studentUid:'student',taskId:'task1',kind:'quiz',title:'Physics task',course:'Physics ATAR',yearGroup:11,earned:1,max:2,manualCount:0,completed:true,selfReported:false,seconds:5,responses:[],createdAt:serverTimestamp(),...extra});
try{await env.clearFirestore();
 await deny(setDoc(doc(student,'members','student'),profile('student','student',{status:'active'})));
 await deny(setDoc(doc(student,'members','student'),profile('student','student',{subjects:subjects.slice(0,3)})));
 await deny(setDoc(doc(student,'members','student'),profile('student','student',{subjects:[...subjects,'Physics ATAR']})));
 await deny(setDoc(doc(student,'members','student'),profile('student','student',{yearGroup:10})));
 await ok(setDoc(doc(student,'members','student'),profile('student','student')));
 await ok(setDoc(doc(other,'members','other'),profile('other','student',{yearGroup:8,subjects:[]})));
 await deny(setDoc(doc(student,'admins','student'),{enabled:true}));
 await deny(updateDoc(doc(student,'members','student'),{status:'active',updatedAt:serverTimestamp()}));
 await deny(getDoc(doc(other,'members','student')));await deny(getDocs(collection(student,'members')));await deny(getDoc(doc(guest,'members','student')));
 const signup=writeBatch(teacher);signup.set(doc(teacher,'members','teacher'),profile('teacher','teacher'));signup.set(doc(teacher,'classes','ABCD2345'),room('teacher','ABCD2345'));await ok(signup.commit());
 await deny(setDoc(doc(student,'classes','ZZZZ2345'),room('student','ZZZZ2345')));
 await deny(setDoc(doc(teacher,'classes','ABCD2345','tasks','task1'),task()));
 await deny(setDoc(doc(student,'classes','ABCD2345','students','student'),enrollment()));
 await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'admins','owner'),{enabled:true})});
 for(const uid of ['student','other','teacher'])await ok(updateDoc(doc(owner,'members',uid),{status:'active',updatedAt:serverTimestamp()}));
 await ok(getDocs(query(collection(teacher,'classes'),where('ownerUid','==','teacher'))));
 const join=writeBatch(student);join.set(doc(student,'classes','ABCD2345','students','student'),enrollment());join.set(doc(student,'members','student','enrollments','ABCD2345'),{classCode:'ABCD2345',joinedAt:serverTimestamp()});await ok(join.commit());
 await deny(setDoc(doc(student,'members','student','enrollments','FAKE2345'),{classCode:'FAKE2345',joinedAt:serverTimestamp()}));
 await deny(getDocs(collection(student,'classes','ABCD2345','students')));
 await ok(getDocs(collection(teacher,'classes','ABCD2345','students')));
 await ok(setDoc(doc(teacher,'classes','ABCD2345','tasks','task1'),task()));
 await deny(setDoc(doc(student,'classes','ABCD2345','tasks','forged'),task()));
 await deny(setDoc(doc(teacher,'classes','ABCD2345','tasks','badurl'),{...task(),url:'javascript:alert(1)'}));
 await ok(getDoc(doc(student,'classes','ABCD2345','tasks','task1')));
 await deny(getDoc(doc(other,'classes','ABCD2345','tasks','task1')));
 await ok(setDoc(doc(student,'classes','ABCD2345','progress','attempt1'),progress()));
 await deny(setDoc(doc(student,'classes','ABCD2345','progress','attempt2'),progress({studentUid:'other'})));
 await deny(setDoc(doc(student,'classes','ABCD2345','progress','attempt3'),progress({course:'Psychology ATAR'})));
 await deny(setDoc(doc(student,'classes','ABCD2345','progress','attempt4'),progress({earned:99})));
 await deny(setDoc(doc(other,'classes','ABCD2345','progress','attempt5'),progress({studentUid:'other',yearGroup:8})));
 await ok(getDocs(collection(teacher,'classes','ABCD2345','progress')));
 await deny(getDoc(doc(stranger,'classes','ABCD2345','progress','attempt1')));
 await deny(getDoc(doc(other,'classes','ABCD2345','progress','attempt1')));
 await deny(getDocs(collection(guest,'classes','ABCD2345','progress')));
 await deny(updateDoc(doc(student,'classes','ABCD2345','progress','attempt1'),{earned:2}));
 await ok(updateDoc(doc(owner,'members','teacher'),{permissions:{'teacher-classes.html':false},updatedAt:serverTimestamp()}));
 await deny(getDocs(collection(teacher,'classes','ABCD2345','progress')));
 await deny(setDoc(doc(student,'classes','ABCD2345','progress','attempt6'),progress()));
 await ok(updateDoc(doc(owner,'members','teacher'),{permissions:{},updatedAt:serverTimestamp()}));
 await ok(updateDoc(doc(owner,'members','student'),{status:'suspended',updatedAt:serverTimestamp()}));
 await deny(setDoc(doc(student,'classes','ABCD2345','progress','attempt7'),progress()));
 console.log('Passed '+count+' Firestore checks: both approvals, senior subject validation, class-code registration, class isolation, assignments, private progress and revocation.');
}finally{await env.cleanup()}
