import fs from 'node:fs';
import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';
import {doc,collection,getDoc,getDocs,setDoc,updateDoc,deleteDoc,serverTimestamp,onSnapshot} from 'firebase/firestore';
import assert from 'node:assert/strict';
const env=await initializeTestEnvironment({projectId:'demo-science-vault-access',firestore:{host:'127.0.0.1',port:8089,rules:fs.readFileSync(new URL('../firestore.rules',import.meta.url),'utf8')}});
const profile=(role,email,extra={})=>({email,displayName:'Test account',role,status:role==='teacher'?'pending':'active',permissions:{},createdAt:serverTimestamp(),updatedAt:serverTimestamp(),...extra});
const student=env.authenticatedContext('student',{email:'student@example.invalid',email_verified:true}).firestore();
const teacher=env.authenticatedContext('teacher',{email:'teacher@example.invalid',email_verified:true}).firestore();
const owner=env.authenticatedContext('owner',{email:'owner@example.invalid',email_verified:true}).firestore();
const unverified=env.authenticatedContext('owner',{email:'owner@example.invalid',email_verified:false}).firestore();
const guest=env.unauthenticatedContext().firestore();
let checks=0;async function ok(p){await assertSucceeds(p);checks++}async function denied(p){await assertFails(p);checks++}
try{
 await env.clearFirestore();
 await denied(getDoc(doc(guest,'members','student')));
 await denied(setDoc(doc(guest,'members','student'),profile('student','student@example.invalid')));
 await ok(setDoc(doc(student,'members','student'),profile('student','student@example.invalid')));
 await ok(getDoc(doc(student,'members','student')));
 await denied(getDocs(collection(student,'members')));
 await denied(setDoc(doc(student,'admins','student'),{enabled:true}));
 await denied(getDoc(doc(student,'admins','owner')));
 await ok(getDoc(doc(student,'admins','student')));
 await denied(updateDoc(doc(student,'members','student'),{permissions:{'library.html':true},updatedAt:serverTimestamp()}));
 await denied(updateDoc(doc(student,'members','student'),{role:'teacher',updatedAt:serverTimestamp()}));
 await denied(deleteDoc(doc(student,'members','student')));
 await denied(setDoc(doc(teacher,'members','teacher'),profile('teacher','teacher@example.invalid',{status:'active'})));
 await denied(setDoc(doc(teacher,'members','teacher'),profile('teacher','teacher@example.invalid',{permissions:{'library.html':true}})));
 await ok(setDoc(doc(teacher,'members','teacher'),profile('teacher','teacher@example.invalid')));
 await denied(updateDoc(doc(teacher,'members','teacher'),{status:'active',updatedAt:serverTimestamp()}));
 await denied(getDoc(doc(student,'members','teacher')));
 await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'admins','owner'),{enabled:true})});
 await ok(getDocs(collection(owner,'members')));
 await ok(updateDoc(doc(owner,'members','teacher'),{status:'active',permissions:{'library.html':true,'student-quiz.html':false},updatedAt:serverTimestamp()}));
 const saved=(await getDoc(doc(teacher,'members','teacher'))).data();assert.equal(saved.status,'active');assert.equal(saved.permissions['library.html'],true);checks++;
 await denied(updateDoc(doc(unverified,'members','teacher'),{status:'suspended',updatedAt:serverTimestamp()}));
 await denied(getDocs(collection(unverified,'members')));
 await denied(updateDoc(doc(owner,'members','teacher'),{role:'student',updatedAt:serverTimestamp()}));
 await denied(updateDoc(doc(owner,'members','teacher'),{email:'replacement@example.invalid',updatedAt:serverTimestamp()}));
 await denied(updateDoc(doc(owner,'members','teacher'),{status:'nonsense',updatedAt:serverTimestamp()}));
 await denied(updateDoc(doc(owner,'members','teacher'),{permissions:[],updatedAt:serverTimestamp()}));
 await denied(updateDoc(doc(owner,'members','teacher'),{status:'suspended'}));
 await denied(deleteDoc(doc(owner,'members','teacher')));
 await denied(setDoc(doc(student,'results','fake'),{score:1}));
 const revokeSeen=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Revocation listener timed out')),3000);const stop=onSnapshot(doc(teacher,'members','teacher'),s=>{if(s.data()?.status==='suspended'){clearTimeout(timer);stop();resolve()}})});
 await ok(updateDoc(doc(owner,'members','teacher'),{status:'suspended',updatedAt:serverTimestamp()}));await revokeSeen;checks++;
 await env.withSecurityRulesDisabled(async c=>{await updateDoc(doc(c.firestore(),'admins','owner'),{enabled:false})});
 await denied(updateDoc(doc(owner,'members','teacher'),{status:'active',updatedAt:serverTimestamp()}));
 console.log(`Passed ${checks} emulator authorization checks: private accounts, no self-approval/escalation, admin-only grants, live revocation, and no result writes.`);
}finally{await env.cleanup()}
