import {accountError,signupProblem} from './account-helpers.mjs';
const $=id=>document.getElementById(id),forms={login:$('loginForm'),signup:$('signupForm'),reset:$('resetForm')};
let accessState,accessApi;
let client,mode=location.hash==='#signup'?'signup':location.hash==='#reset'?'reset':'login',busy=false,ready=false,verificationWarning='';
function message(text,kind='info'){$('accountStatus').textContent=text;$('accountStatus').dataset.kind=kind;$('accountStatus').hidden=!text}
function updateButtons(){document.querySelectorAll('.account-submit').forEach(b=>b.disabled=!ready||busy);document.querySelectorAll('[data-mode]').forEach(b=>b.disabled=busy);$('logout').disabled=busy;$('sendVerification').disabled=busy;$('checkVerification').disabled=busy;if($('saveMembership'))$('saveMembership').disabled=busy||!ready||!accessState?.ready||!!accessState?.error}
function render(){const user=client?.auth.currentUser;Object.entries(forms).forEach(([key,form])=>form.hidden=!!user||key!==mode);$('accountTabs').hidden=!!user;$('signedIn').hidden=!user;document.querySelectorAll('.account-tabs [data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));if(user){$('accountName').textContent=user.displayName||'Your account';$('accountEmail').textContent=user.email||'';$('verificationBadge').textContent=user.emailVerified?'Email verified':'Email not yet verified';$('verificationBadge').classList.toggle('verified',user.emailVerified);$('verificationActions').hidden=user.emailVerified;$('verificationHelp').hidden=user.emailVerified}updateButtons();if(accessState)accessRender(accessState)}
function changeMode(next){if(busy||!forms[next])return;mode=next;history.replaceState(null,'',next==='login'?location.pathname:'#'+next);if(next==='reset'&&!$('resetEmail').value)$('resetEmail').value=$('loginEmail').value;message('');render();forms[next].querySelector('input')?.focus()}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>changeMode(b.dataset.mode)));
window.addEventListener('hashchange',()=>{if(!busy)changeMode(location.hash==='#signup'?'signup':location.hash==='#reset'?'reset':'login')});
async function run(action){if(!ready||busy)return;busy=true;updateButtons();message('Please wait…');try{await action()}catch(error){message(accountError(error),'error')}finally{busy=false;render()}}
forms.login.addEventListener('submit',e=>{e.preventDefault();run(async()=>{try{await client.persistence($('loginRemember').checked);await client.signInWithEmailAndPassword(client.auth,$('loginEmail').value.trim(),$('loginPassword').value);message('You’re logged in. Your available pages are listed below.','success')}finally{$('loginPassword').value=''}})});
forms.signup.addEventListener('submit',e=>{e.preventDefault();const problem=signupProblem($('signupPassword').value,$('signupConfirm').value);if(problem){message(problem,'error');$('signupConfirm').focus();return}run(async()=>{try{await client.persistence($('signupRemember').checked);const {user}=await client.createUserWithEmailAndPassword(client.auth,$('signupEmail').value.trim(),$('signupPassword').value);const name=$('signupName').value.trim();verificationWarning='';if(name){try{await client.updateProfile(user,{displayName:name})}catch{verificationWarning=' Your account was created, but the display name could not be saved.'}}try{await (await import('./access-client.mjs')).registerMember(user,$('signupRole').value)}catch{verificationWarning+=' Account access could not be set up; finish registration below.'}try{await client.sendEmailVerification(user);message('Your account is created. Check your inbox for the verification email.'+verificationWarning,'success')}catch{message('Your account is created and you’re signed in. The verification email could not be sent; use Send verification email below to try again.'+verificationWarning,'info')}render()}finally{$('signupPassword').value='';$('signupConfirm').value=''}})});
forms.reset.addEventListener('submit',e=>{e.preventDefault();run(async()=>{try{await client.sendPasswordResetEmail(client.auth,$('resetEmail').value.trim())}catch(error){if(error.code!=='auth/user-not-found')throw error}message('If an account exists for this email, you’ll receive a password-reset link. Check your inbox and spam folder.','success')})});
$('logout').addEventListener('click',()=>run(async()=>{await client.signOut(client.auth);mode='login';message('You’re logged out.','success')}));
$('sendVerification').addEventListener('click',()=>run(async()=>{const user=client.auth.currentUser;if(!user)return;await client.sendEmailVerification(user);message('Verification email sent. Check your inbox and spam folder.','success')}));
$('checkVerification').addEventListener('click',()=>run(async()=>{const user=client.auth.currentUser;if(!user)return;await client.reload(user);await client.getIdToken(user,true);render();message(user.emailVerified?'Your email is verified.':'Your email is not verified yet. Open the link in your verification email, then try again.',user.emailVerified?'success':'info')}));
render();
try{client=await import('./firebase-client.mjs?v=2026.10.9-permissions');client.onAuthStateChanged(client.auth,()=>{ready=true;render();if(!busy)message(client.auth.currentUser?'You’re signed in. Your available pages are listed below.':'',client.auth.currentUser?'success':'info')},()=>{ready=false;updateButtons();message('Your session could not be restored. Refresh this page to try again.','error')})}catch{message('The account service could not load. Check your connection and refresh this page. Privacy and legal information remain available.','error')}


function accessRender(state){accessState=state;const user=client?.auth.currentUser;$('accountUid').textContent=user?.uid||'';$('accessPanel').hidden=!user;if(!user)return;if(state.user?.uid!==user.uid){$('accessStatus').textContent='Loading your account access…';$('adminLink').hidden=true;$('allowedPages').replaceChildren();$('memberForm').hidden=true;return}$('memberForm').hidden=!state.ready||!!state.member||state.admin;$('adminLink').hidden=!state.admin;$('allowedPages').replaceChildren();$('saveMembership').disabled=busy||!state.ready||!!state.error;if(!state.ready){$('accessStatus').textContent='Loading your account access…';return}if(state.error){$('accessStatus').textContent='Account access is not configured yet. The site owner needs to finish Firebase setup.';return}if(state.admin){$('accessStatus').textContent='Administrator · Full website access';}else if(!state.member){$('accessStatus').textContent='Choose Student or Teacher below to finish registering your account.';}else{$('accessStatus').textContent=state.member.status==='pending'?'Teacher account · Waiting for owner approval':state.member.status==='suspended'?'Account suspended · Contact the site owner':state.member.role==='teacher'&&!user.emailVerified?'Teacher account approved · Verify your email to continue':state.member.role==='teacher'?'Teacher account approved':'Student account active';}
import('./page-catalog.mjs').then(async({PAGES})=>{const {canOpenPage}=await import('./access-policy.mjs');if(accessState!==state)return;for(const page of PAGES.filter(p=>canOpenPage(state,p))){const a=document.createElement('a');a.href=page.id;a.textContent=page.label;$('allowedPages').appendChild(a)}}).catch(()=>{});
}
$('memberForm').addEventListener('submit',e=>{e.preventDefault();run(async()=>{await accessApi.registerMember(client.auth.currentUser,$('memberRole').value);message('Account type saved. Teacher access requires owner approval.','success')})});
try{accessApi=await import('./access-client.mjs');accessApi.observeAccess(accessRender)}catch{$('accessStatus').textContent='Account access could not load. Refresh this page to try again.'}
