import {PAGES} from './page-catalog.mjs';
import {canOpenPage} from './access-policy.mjs';
const $=id=>document.getElementById(id);let api,state,members=[],cursor,more=false,selected=null,permissions={},loading=false,saving=false,dirty=false,epoch=0;
function status(id,text,kind='info'){const el=$(id);el.textContent=text;el.dataset.kind=kind;el.hidden=!text}
function controls(){document.querySelectorAll('#permissionForm button,#permissionForm input,#permissionForm select').forEach(el=>el.disabled=saving);$('reloadMembers').disabled=loading||saving;$('loadMore').disabled=loading||saving;$('approveAccess').hidden=selected?.status!=='pending';$('loadMore').hidden=!more}
function list(){const term=$('memberSearch').value.trim().toLowerCase(),filter=$('memberFilter').value;$('memberList').replaceChildren();const shown=members.filter(m=>(filter==='all'||m.status===filter)&&[m.email,m.displayName,m.uid].some(v=>String(v||'').toLowerCase().includes(term)));$('memberCount').textContent=`${shown.length} shown · ${members.length} accounts loaded${more?' · more available':''}`;if(!shown.length){const p=document.createElement('p');p.textContent='No matching loaded accounts.';$('memberList').appendChild(p)}shown.forEach(member=>{const b=document.createElement('button');b.type='button';b.className='admin-member'+(selected?.uid===member.uid?' selected':'');b.disabled=saving;const title=document.createElement('strong');title.textContent=member.displayName||member.email;const email=document.createElement('span');email.textContent=member.email;const badge=document.createElement('span');badge.textContent=`${member.role} · ${member.status}`;badge.className=member.status;b.append(title,email,badge);b.addEventListener('click',()=>select(member));$('memberList').appendChild(b)});controls()}
function count(){$('selectedCount').textContent=`${PAGES.filter(p=>permissions[p.id]).length} / ${PAGES.length} selected`}
function choices(){const term=$('pageSearch').value.trim().toLowerCase();$('pageChoices').replaceChildren();const groups=new Map();for(const page of PAGES.filter(p=>(p.label+' '+p.id).toLowerCase().includes(term))){if(!groups.has(page.group)){const group=document.createElement('fieldset');group.className='page-group';const legend=document.createElement('legend');legend.textContent=page.group;group.appendChild(legend);groups.set(page.group,group);$('pageChoices').appendChild(group)}const label=document.createElement('label');label.className='page-choice';const input=document.createElement('input');input.type='checkbox';input.checked=permissions[page.id]===true;input.disabled=saving;input.addEventListener('change',()=>{permissions[page.id]=input.checked;dirty=true;count()});const text=document.createElement('span');text.textContent=page.label;const file=document.createElement('small');file.textContent=page.id;text.appendChild(file);label.append(input,text);groups.get(page.group).appendChild(label)}if(!groups.size){const p=document.createElement('p');p.textContent='No pages match your search.';$('pageChoices').appendChild(p)}count()}
function select(member){if(saving)return;if(dirty&&!window.confirm('Discard the unsaved access changes for this account?'))return;selected=member;dirty=false;permissions={...member.permissions};for(const page of PAGES)permissions[page.id]=canOpenPage({user:{emailVerified:true},member:{...member,status:'active'},admin:false},page);$('selectPrompt').hidden=true;$('permissionForm').hidden=false;$('memberName').textContent=member.displayName||'Account';$('memberEmail').textContent=member.email;$('memberRole').textContent=member.role;$('memberState').textContent=`Account ID: ${member.uid} · Current status: ${member.status}`;$('accountState').value=member.status;$('pageSearch').value='';status('editorStatus','');choices();list()}
async function load(reset=false){if(loading||saving||!state?.admin)return;if(reset&&dirty&&!window.confirm('Discard unsaved changes and refresh the accounts?'))return;const ticket=epoch;loading=true;controls();status('adminStatus','Loading accounts…');try{const result=await api.loadMembers(reset?null:cursor);if(ticket!==epoch||!state?.admin)return;if(reset){members=[];selected=null;dirty=false;$('permissionForm').hidden=true;$('selectPrompt').hidden=false}members.push(...result.members);cursor=result.cursor;more=result.more;list();status('adminStatus','Select an account to manage its access.')}catch(error){if(ticket===epoch)status('adminStatus',api.permissionError(error),'error')}finally{loading=false;controls()}}
async function save(nextStatus){if(!selected||saving||!state?.admin)return;saving=true;controls();list();status('editorStatus','Saving account access…');const uid=selected.uid,ticket=epoch;try{const member=await api.saveMember(uid,{status:nextStatus,permissions:{...permissions}},selected.updatedAt);if(ticket!==epoch||!state?.admin)return;members=members.map(m=>m.uid===uid?member:m);selected=member;dirty=false;$('accountState').value=member.status;$('memberState').textContent=`Account ID: ${uid} · Current status: ${member.status}`;status('editorStatus',nextStatus==='suspended'?'Account suspended. All content-page access is blocked.':'Saved. This account’s access has been updated.','success');list()}catch(error){if(ticket===epoch)status('editorStatus',api.permissionError(error),'error')}finally{saving=false;controls();list()}}
$('memberSearch').addEventListener('input',list);$('memberFilter').addEventListener('change',list);$('pageSearch').addEventListener('input',choices);$('accountState').addEventListener('change',()=>dirty=true);
$('loadMore').addEventListener('click',()=>load());$('reloadMembers').addEventListener('click',()=>load(true));
for(const [id,predicate] of [['allowAll',()=>true],['denyAll',()=>false],['studentPreset',p=>p.studentDefault]])$(id).addEventListener('click',()=>{if(saving)return;for(const page of PAGES)permissions[page.id]=!!predicate(page);dirty=true;choices()});
$('permissionForm').addEventListener('submit',e=>{e.preventDefault();save($('accountState').value)});$('approveAccess').addEventListener('click',()=>save('active'));$('suspendAccess').addEventListener('click',()=>save('suspended'));
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
try{api=await import('./access-client.mjs');api.observeAccess(next=>{const wasAdmin=state?.admin;state=next;if(!next.ready)return;$('adminPanel').hidden=!next.admin;$('adminGate').hidden=next.admin;if(!next.admin){epoch++;members=[];selected=null;permissions={};dirty=false;cursor=null;more=false;$('memberList').replaceChildren();$('permissionForm').hidden=true;$('memberName').textContent='';$('memberEmail').textContent='';$('memberState').textContent='';$('pageChoices').replaceChildren();status('adminStatus',next.error?'Admin access could not be checked. Follow the owner setup instructions.':next.user?'This account does not have administrator access.':'Log in with your administrator account.',next.error?'error':'info')}else if(!wasAdmin)load(true)})}catch{status('adminStatus','The account service could not load. Check your connection and try again.','error')}
