import {auth} from './firebase-client.mjs?v=2026.10.9-permissions';
import {db,waitForAccess,getAccessState} from './access-client.mjs?v=2026.10.9-classes';
import {canStudy} from './registration-options.mjs';
import {doc,getDoc,getDocs,collection,query,where,orderBy,limit,setDoc,writeBatch,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
export async function joinClass(raw){const code=raw.trim().toUpperCase(),state=await waitForAccess();if(!/^[A-HJ-NP-Z2-9]{8}$/.test(code))throw Error('Enter an 8-character class code.');if(state.member?.role!=='student'||state.member.status!=='active')throw Error('Your student account needs admin approval before joining a class.');const room=await getDoc(doc(db,'classes',code));if(!room.exists())throw Error('That class code was not found. Check it with your teacher.');const batch=writeBatch(db);batch.set(doc(db,'classes',code,'students',auth.currentUser.uid),{studentUid:auth.currentUser.uid,displayName:state.member.displayName,yearGroup:state.member.yearGroup,joinedAt:serverTimestamp()});batch.set(doc(db,'members',auth.currentUser.uid,'enrollments',code),{classCode:code,joinedAt:serverTimestamp()});await batch.commit();return code}
export async function myClasses(state){if(state.member?.role==='teacher'){const s=await getDocs(query(collection(db,'classes'),where('ownerUid','==',state.user.uid)));return s.docs.map(d=>d.data())}const refs=await getDocs(collection(db,'members',state.user.uid,'enrollments'));const rooms=await Promise.all(refs.docs.map(d=>getDoc(doc(db,'classes',d.id))));return rooms.filter(d=>d.exists()).map(d=>d.data())}
export async function classTasks(code){const s=await getDocs(query(collection(db,'classes',code,'tasks'),orderBy('createdAt','desc'),limit(100)));return s.docs.map(d=>({id:d.id,...d.data()}))}
export async function loadTask(code,id){if(!code||!id)return null;const s=await getDoc(doc(db,'classes',code,'tasks',id));if(!s.exists())throw Error('This assigned task no longer exists.');const task={id:s.id,...s.data()},state=await waitForAccess();if(!canStudy(state.member,task.course,task.yearGroup,state.admin))throw Error('This task is outside your approved year group or selected subjects.');return task}
export async function assignTask(code,values){const ref=doc(collection(db,'classes',code,'tasks'));await setDoc(ref,{...values,ownerUid:auth.currentUser.uid,createdAt:serverTimestamp()});return ref.id}
export async function classReport(code){const [students,results]=await Promise.all([getDocs(collection(db,'classes',code,'students')),getDocs(query(collection(db,'classes',code,'progress'),orderBy('createdAt','desc'),limit(200)))]);return{students:students.docs.map(d=>d.data()),results:results.docs.map(d=>({id:d.id,...d.data()}))}}
export async function saveProgress(values){const state=getAccessState();if(!state.ready||state.member?.role!=='student'||state.member.status!=='active'||state.member.registrationVersion!==2)return false;if(!canStudy(state.member,values.course,values.yearGroup))return false;const params=new URLSearchParams(location.search),taskId=params.get('task')||'',taskClass=params.get('class')||'';const rooms=taskClass?[{code:taskClass}]:await myClasses(state);if(!rooms.length)return false;const eventId=crypto.randomUUID();let failures=0;await Promise.all(rooms.map(async room=>{try{await setDoc(doc(db,'classes',room.code,'progress',eventId),{...values,studentUid:state.user.uid,taskId,createdAt:serverTimestamp()})}catch{failures++}}));if(failures===rooms.length)throw Error('Progress could not be saved. Your account and class teacher need approval, and Firestore rules must be published.');return true}
export function stageAssessment(draft){if(!draft.questionIds?.length)throw Error('Build an assessment first.');if(draft.questionIds.length>50)throw Error('Choose no more than 50 questions per assigned task.');sessionStorage.setItem('vault-assignment-draft',JSON.stringify(draft));location.href='teacher-classes.html'}
