(()=>{
const $=id=>document.getElementById(id),fmt=n=>Number(n||0).toLocaleString('en-AU');
async function json(name){try{const r=await fetch(name+'?ts='+Date.now(),{cache:'no-store'});return r.ok?await r.json():[]}catch(e){return[]}}
function show(id,n){const el=$(id);if(el)el.textContent=fmt(n)}
function clean(path){return (path.split('/').pop()||'').replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').replace(/^\d{13}\s*/,'').replace(/\s+/g,' ').trim()}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function raw(p){return'https://raw.githubusercontent.com/science-vault/science-vault-wa/main/'+String(p||'').split('/').map(encodeURIComponent).join('/')}
function dateLabel(v){if(!v)return'';const d=new Date(v);return isNaN(d)?'':d.toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'})}
async function draw(){
 const [resources,exams,assessments,textbooks]=await Promise.all([json('resource-manifest.json'),json('exam-manifest.json'),json('assessment-manifest.json'),json('textbook-manifest.json')]);
 const isAssessment=r=>/^resources\/Assessments\//i.test(r.path||''),isTextbook=r=>/(^|\/)Textbooks?\//i.test(r.path||'');
 const ordinary=resources.filter(r=>!isAssessment(r)&&!isTextbook(r));
 const textbookPaths=new Set([...resources.filter(isTextbook).map(r=>r.path),...textbooks.map(r=>r.path)]);
 const classify=r=>{const p=(r.path||'').toLowerCase(),n=p.split('/').pop()||'';if(/\.pptx?$/.test(n)||p.includes('powerpoint')||p.includes('/ppts/'))return'PowerPoint';if(/worksheet|activity sheet|guided notes/.test(p))return'Worksheet';if(/practical|experiment|investigation|dissection|fieldwork/.test(p))return'Practical';if(/revision|review/.test(p))return'Revision';if(/test|assessment|quiz|exam|task/.test(p))return'Test / Task';if(/note|summary/.test(p))return'Notes';return'Other Resource'};
 const counts={};ordinary.forEach(r=>{const t=classify(r);const key={'PowerPoint':'PowerPoints','Worksheet':'Worksheets','Practical':'Practicals','Revision':'Revision','Test / Task':'Tests','Notes':'Notes','Other Resource':'Other Resources'}[t];counts[key]=(counts[key]||0)+1});
 show('statPowerPoints',counts.PowerPoints);show('statWorksheets',counts.Worksheets);show('statNotes',counts.Notes);show('statPracticals',counts.Practicals);show('statRevision',counts.Revision);show('statTests',counts.Tests);show('statOther',counts['Other Resources']);show('statAssessments',assessments.length);show('statExams',exams.length);show('statTextbooks',textbookPaths.size);show('statTotal',ordinary.length+assessments.length+exams.length+textbookPaths.size);
 const stamp=$('statsUpdated');if(stamp)stamp.textContent='Running totals from the current website library';
 const all=[...ordinary.map(x=>({...x,type:classify(x),vault:'Resource'})),...assessments.map(x=>({...x,type:'Assessment',vault:'Assessment'})),...exams.map(x=>({...x,type:'Exam',vault:'Exam'})),...textbooks.filter(x=>/\.pdf$/i.test(x.path||'')).map(x=>({...x,type:'Textbook',vault:'Textbook'}))].filter(x=>x.path);
 all.sort((a,b)=>(Date.parse(b.modified||b.updated||0)||0)-(Date.parse(a.modified||a.updated||0)||0));
 const recent=all.slice(0,8),stats=document.querySelector('.resource-stats-section');
 if(stats&&recent.length){const sec=document.createElement('section');sec.className='home-section recently-added';sec.innerHTML='<div class="home-section-head"><div><span class="eyebrow">RECENTLY ADDED</span><h2>New in the vault</h2></div><p>The latest files added across resources, assessments, exams and textbooks.</p></div><div class="recent-grid">'+recent.map(r=>{const path=r.path,parts=path.split('/'),context=parts.slice(1,-1).slice(-3).join(' · '),d=dateLabel(r.modified||r.updated),url=raw(path);return '<article class="recent-card" data-resource-path="'+esc(path)+'"><div class="recent-top"><span class="new-badge">NEW</span><span class="recent-type">'+esc(r.type)+'</span></div><h3>'+esc(clean(path))+'</h3><p>'+esc(context)+'</p><div class="recent-meta">'+(d?'<span>Added '+esc(d)+'</span>':'<span>Recently added</span>')+'<span>'+esc((path.split('.').pop()||'FILE').toUpperCase())+'</span></div><div class="resource-actions recent-actions"><button type="button" class="preview-btn" data-preview="'+esc(url)+'" data-title="'+esc(clean(path))+'">Preview</button><a class="download-btn" target="_blank" rel="noopener" href="'+esc(url)+'">Download</a></div></article>'}).join('')+'</div><div class="recent-more"><a class="primary-action" href="library.html">Browse all resources</a></div>';stats.after(sec);VaultUI.decorate(sec)}
 const footer=document.querySelector('footer');if(footer){const links=footer.querySelector('.footer-links');if(links&&!links.querySelector('[href="about.html"]'))links.insertAdjacentHTML('beforeend','<a href="about.html">About</a><a href="contact.html">Contact</a><a href="copyright.html">Copyright</a><a href="privacy.html">Privacy</a><a href="terms.html">Terms</a>')}
}
draw();
})();