// Generated by page-catalog-builder.py. Login, legal and admin screens use separate rules.
export const PAGES=[
  {
    "id": "about.html",
    "label": "About",
    "group": "Learning and general pages",
    "studentDefault": true
  },
  {
    "id": "contact.html",
    "label": "Contact",
    "group": "Learning and general pages",
    "studentDefault": true
  },
  {
    "id": "index.html",
    "label": "Home",
    "group": "Learning and general pages",
    "studentDefault": true
  },
  {
    "id": "learning-area.html",
    "label": "Learning Area",
    "group": "Learning and general pages",
    "studentDefault": true
  },
  {
    "id": "syllabus.html",
    "label": "Science",
    "group": "Learning and general pages",
    "studentDefault": true
  },
  {
    "id": "student-area.html",
    "label": "Student area",
    "group": "Learning and general pages",
    "studentDefault": true
  },
  {
    "id": "topic-hub.html",
    "label": "Topic Hub",
    "group": "Learning and general pages",
    "studentDefault": true
  },
  {
    "id": "topic-hubs.html",
    "label": "Topic Hubs",
    "group": "Learning and general pages",
    "studentDefault": true
  },
  {
    "id": "student-quiz.html",
    "label": "Practice tests",
    "group": "Practice",
    "studentDefault": true
  },
  {
    "id": "assessment-year.html",
    "label": "Assessment Vault",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "assessments.html",
    "label": "Assessment Vault",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "biology.html",
    "label": "Biology ATAR",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "chemistry.html",
    "label": "Chemistry ATAR",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "english-atar.html",
    "label": "English ATAR",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "exams.html",
    "label": "Exam Vault",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "human-biology.html",
    "label": "Human Biology ATAR",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "student-tracking.html",
    "label": "Learning Vault WA",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "teacher-tracking.html",
    "label": "Learning Vault WA",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "mathematics-applications.html",
    "label": "Mathematics Applications ATAR",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "mathematics-methods.html",
    "label": "Mathematics Methods ATAR",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "mathematics-specialist.html",
    "label": "Mathematics Specialist ATAR",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "notes.html",
    "label": "Notes Vault",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "other-resources.html",
    "label": "Other Resources",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "pdf-preview.html",
    "label": "PDF preview",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "physical-education-studies.html",
    "label": "PE Studies ATAR",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "physics.html",
    "label": "Physics ATAR",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "physics-atar-layout-preview.html",
    "label": "Physics ATAR Builder Preview",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "powerpoints.html",
    "label": "PowerPoint Vault",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "practicals.html",
    "label": "Practical Vault",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "psychology.html",
    "label": "Psychology ATAR",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "library.html",
    "label": "Resource Vault",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "revision.html",
    "label": "Revision Vault",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "textbooks.html",
    "label": "Textbook Vault",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "videos.html",
    "label": "Video Vault",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "worksheets.html",
    "label": "Worksheet Vault",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "year10.html",
    "label": "Year 10 Science",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "year7.html",
    "label": "Year 7 Science",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "year8.html",
    "label": "Year 8 Science",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "year9.html",
    "label": "Year 9 Science",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "senior.html",
    "label": "Years 11",
    "group": "Resources and course pages",
    "studentDefault": false
  },
  {
    "id": "assessment-builders.html",
    "label": "Assessment Builders",
    "group": "Teacher tools",
    "studentDefault": false
  },
  {
    "id": "assessment-builder.html",
    "label": "Lower School Assessment Builder",
    "group": "Teacher tools",
    "studentDefault": false
  },
  {
    "id": "my-resources.html",
    "label": "My Resources",
    "group": "Teacher tools",
    "studentDefault": false
  },
  {
    "id": "assessment-question-browser.html",
    "label": "Question Bank Database",
    "group": "Teacher tools",
    "studentDefault": false
  },
  {
    "id": "questions.html",
    "label": "Question Vault",
    "group": "Teacher tools",
    "studentDefault": false
  },
  {
    "id": "OPEN-RESOURCE-MANAGER.html",
    "label": "Resource manager launcher",
    "group": "Teacher tools",
    "studentDefault": false
  },
  {
    "id": "teacher-area.html",
    "label": "Teacher area",
    "group": "Teacher tools",
    "studentDefault": false
  },
  {
    "id": "upper-school-assessment-builder.html",
    "label": "Upper School Assessment Builder",
    "group": "Teacher tools",
    "studentDefault": false
  }
];
