"""Update root content-page gates and the admin catalogue before Pages deployment."""
from pathlib import Path
import re,json,sys
root=Path(sys.argv[1]).resolve() if len(sys.argv)>1 else Path(__file__).resolve().parent
public={'account.html','privacy.html','terms.html','copyright.html','admin-access.html','firebase-setup.html'}
student={'index.html','student-area.html','topic-hub.html','topic-hubs.html','student-quiz.html','learning-area.html','syllabus.html','about.html','contact.html'}
labels={'index.html':'Home','teacher-area.html':'Teacher area','student-area.html':'Student area','student-quiz.html':'Practice tests','pdf-preview.html':'PDF preview','OPEN-RESOURCE-MANAGER.html':'Resource manager launcher'}
teacher={'assessment-builders.html','assessment-builder.html','upper-school-assessment-builder.html','assessment-question-browser.html','questions.html','my-resources.html','OPEN-RESOURCE-MANAGER.html','teacher-area.html'}
pages=[]
for path in sorted(root.glob('*.html')):
 name=path.name
 if name in public:continue
 text=path.read_text()
 title=re.search(r'<title>(.*?)</title>',text,re.S|re.I)
 label=labels.get(name,re.split(r'\s*[|–—]\s*',title.group(1) if title else name)[0].strip())
 group='Teacher tools' if name in teacher else 'Practice' if name=='student-quiz.html' else 'Learning and general pages' if name in student else 'Resources and course pages'
 pages.append({'id':name,'label':label,'group':group,'studentDefault':name in student})
 if not re.search(r'<script\b[^>]*src=["\'][^"\']*access-bootstrap\.js',text,re.I):
  text=re.sub(r'<head([^>]*)>',lambda m:m.group(0)+'<script src="access-bootstrap.js?v=2026.10.9"></script>',text,count=1,flags=re.I)
 if 'id="accessNoScript"' not in text:
  notice='<noscript id="accessNoScript"><style>body>*:not(#accessNoScript){display:none!important}#accessNoScript{display:block!important;padding:40px;font:16px/1.6 Arial}</style><h1>JavaScript is required</h1><p>Enable JavaScript to log in and check your page access.</p><a href="privacy.html">Privacy information</a></noscript>'
  text=re.sub(r'<body([^>]*)>',lambda m:m.group(0)+notice,text,count=1,flags=re.I)
 path.write_text(text)
pages.sort(key=lambda p:(p['group'],p['label']))
(root/'page-catalog.mjs').write_text('// Generated by page-catalog-builder.py. Login, legal and admin screens use separate rules.\nexport const PAGES='+json.dumps(pages,ensure_ascii=False,indent=2)+';\n')
print(f'Updated {len(pages)} content-page gates and access catalogue.')
