import {getDocument,GlobalWorkerOptions} from './pdfjs-reader.mjs';
GlobalWorkerOptions.workerSrc=new URL('./pdfjs-worker.mjs',import.meta.url).href;
const canvas=document.getElementById('page'),status=document.getElementById('status'),count=document.getElementById('pageCount'),previous=document.getElementById('previous'),next=document.getElementById('next');
let pdf,pageNumber=1,busy=false;
function controls(){previous.disabled=busy||!pdf||pageNumber<=1;next.disabled=busy||!pdf||pageNumber>=pdf.numPages}
function failure(error){canvas.hidden=true;status.hidden=false;status.textContent='This PDF could not be previewed. Use Open file or Download above to view the original.';console.error('PDF preview:',error)}
async function render(){if(busy||!pdf)return;busy=true;controls();try{const page=await pdf.getPage(pageNumber),base=page.getViewport({scale:1}),width=Math.max(240,document.documentElement.clientWidth-32),scale=Math.min(width/base.width,1.7),viewport=page.getViewport({scale}),ratio=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(viewport.width*ratio);canvas.height=Math.round(viewport.height*ratio);canvas.style.width=viewport.width+'px';canvas.style.height=viewport.height+'px';const context=canvas.getContext('2d');await page.render({canvasContext:context,viewport,transform:ratio===1?undefined:[ratio,0,0,ratio,0,0]}).promise;canvas.hidden=false;status.hidden=true;count.textContent='Page '+pageNumber+' of '+pdf.numPages;canvas.setAttribute('aria-label','PDF document page '+pageNumber+' of '+pdf.numPages)}catch(error){failure(error)}finally{busy=false;controls()}}
previous.onclick=()=>{if(pageNumber>1&&!busy){pageNumber--;render()}};next.onclick=()=>{if(pdf&&pageNumber<pdf.numPages&&!busy){pageNumber++;render()}};
try{const source=new URL(new URLSearchParams(location.search).get('src')||'',location.href);if(source.protocol!=='https:'||!(source.origin===location.origin||source.hostname==='raw.githubusercontent.com'&&source.pathname.startsWith('/science-vault/science-vault-wa/main/')))throw new Error('Unsupported PDF source');pdf=await getDocument({url:source.href,isEvalSupported:false}).promise;await render()}catch(error){failure(error)}
