"""Original examination rehearsal, not a reproduced official paper or marking key."""
MCQ=[
('During sarcomere shortening, which stays approximately constant?',['A-band length','I-band width','Z-line separation','H-zone width'],0,'Thick-filament length remains approximately constant; actin slides into greater overlap.'),
('What exposes actin binding sites?',['Calcium regulation through troponin and tropomyosin','Calcium becoming ATP','Myosin filaments dissolving','A-band expansion'],0,'Calcium binds troponin and changes tropomyosin position.'),
('A motor unit consists of:',['One motor neuron and its innervated muscle fibres','One sensory neuron and an entire limb','All motor neurons in the body','A fascicle and its artery'],0,'Motor units are recruited to grade whole-muscle output.'),
('Which mechanism differs from recruitment?',['Increasing impulses per second in active units','Activating additional units','Including larger units','Adding active fibres through more units'],0,'Rate coding changes firing frequency; recruitment changes active units.'),
('Type I generally has:',['High oxidative capacity and fatigue resistance','No mitochondria','Only maximal sprint use','No role in sport'],0,'Characteristics are tendencies; muscles contain mixed fibre populations.'),
('Humidity particularly reduces the potential for:',['Sweat evaporation','Gravity','Oxygen fraction in air','All muscle recruitment'],0,'A smaller vapour-pressure gradient can limit effective evaporation.'),
('At altitude, the primary oxygen challenge is:',['Lower inspired oxygen partial pressure','No oxygen molecules remaining','Instant loss of all haemoglobin','Identical pressure with zero nitrogen'],0,'Oxygen fraction stays approximately similar while atmospheric pressure falls.'),
('Which is a mesocycle in a stated nested plan?',['A training block within the broad period','A single nerve impulse','The total body mass','An individual sarcomere'],0,'Cycle length depends on the programme rather than one universal calendar.'),
('A useful taper generally:',['Reduces load while preserving useful stimulus','Stops all training indefinitely','Doubles every variable immediately','Removes all recovery'],0,'The aim is readiness, not prolonged cessation.'),
('Which statement about supplements is sound?',['Ingredient status does not establish every product’s purity','Every protein powder guarantees strength','Creatine replaces technique learning','Caffeine guarantees improved sleep'],0,'Evidence, safety, need and contamination risk are separate considerations.'),
('Transfer that interferes with the target task is:',['Negative','Always positive','Defined only by indoor practice','The same as speed'],0,'State source and target and consider alternative explanations.'),
('Which follows intervention in the analysis cycle?',['Re-observation','Assuming permanent success','Ignoring outcomes','A medical diagnosis from one frame'],0,'Compare the priority feature again under suitable conditions.'),
('A coach links components into a sequence. This illustrates:',['Chaining','Blood redistribution','Wave drag','Rate coding'],0,'Shaping progressively modifies a skill; chaining links components.'),
('Democratic leadership involves:',['Suitable participant involvement in decisions','No agreed expectations','Every decision being urgent and unilateral','A guarantee of winning'],0,'Style should fit experience, context and task.'),
('A 0.5 kg ball changes from +4 to −4 m/s. Its Δp is:',['−4 kg·m/s','0 kg·m/s','+8 kg·m/s','−8 kg·m/s'],0,'0.5 × (−4 − 4) = −4 kg·m/s. Direction matters.'),
('Fixed-surface drop 1 m, rebound 0.49 m gives ideal e:',['0.7','0.49','1.49','2.04'],0,'e = square root of rebound/drop, under the stated assumptions.'),
('With conserved L, halving I gives angular velocity:',['Twice the initial value','Half the value','Zero regardless of L','Four times the value'],0,'Iω stays constant with negligible net external torque.'),
('A 10 N force with 0.2 m perpendicular arm gives torque:',['2 N·m','50 N·m','0.02 N·m','2 N/s'],0,'Torque = force × perpendicular moment arm.'),
('The equal-height ideal range optimum of 45° assumes:',['Fixed speed and no air resistance','All sports have ground-level targets','Spin cancels gravity','Release speed always rises with angle'],0,'Real target height, spin, drag and technique can change the optimum.'),
('A friendly team with unclear defensive roles may have:',['Social cohesion without effective task coordination','No possible social connection','Guaranteed tactical success','A proven diagnosis of social loafing'],0,'Task and social cohesion are different; investigate the actual issue.')]
SHORT=[
('Neural activation and force','Explain a sensory-to-motor pathway for reacting to a ball and two mechanisms for grading muscle force.', ['Sensory pathways convey relevant information towards the central nervous system.','Brain and spinal cord processing coordinate response; exact pathways depend on task.','Motor neurons supply output to their innervated fibres.','A motor unit is one motor neuron and its muscle fibres.','Recruitment increases active units and rate coding changes firing frequency.','All-or-none unit activation does not make whole-muscle force all-or-none.']),
('Muscle model','Compare the A band, I band and H zone during shortening, then distinguish calcium and ATP roles.', ['Z lines move closer and overlap increases.','A band remains approximately constant because thick-filament length stays constant.','I band and H zone narrow; the filaments do not shrink.','Calcium binds troponin and shifts tropomyosin to expose sites.','ATP binding supports detachment; hydrolysis prepares further cycling.','ATP also supports calcium pumping; calcium is not an ATP substitute.']),
('Environment case','A fictional tournament moves to a hot humid afternoon. Explain three mechanisms affecting performance and two planning considerations.', ['Temperature gradients can reduce dry heat loss or produce heat gain.','Humidity can reduce sweat evaporation, so visible sweat does not prove effective cooling.','Skin blood flow and sweating demands can add cardiovascular strain.','Review scheduling, shade and planned breaks within current school procedures.','Review the established individual hydration arrangements without prescribing a universal amount.','Acclimatisation takes time and does not eliminate risk; this is planning analysis, not treatment.']),
('Periodisation data','A fictional 12-week macrocycle contains three 4-week blocks and weekly schedules. Before a priority event, volume falls while some intensity is retained. Identify the cycles and explain the change.', ['The stated 12-week plan is a macrocycle.','The 4-week blocks are mesocycles; weekly schedules are microcycles.','Durations are contextual, not universal definitions.','The pre-event change illustrates tapering.','Reducing load while retaining useful stimulus can support readiness.','Competition and recovery monitoring should guide adjustments; the plan is not a personal prescription.']),
('Impulse calculation','A 0.4 kg ball changes from +6 to −4 m/s during 0.05 s. Calculate Δp and average net force; compare a 0.10 s interval for the same change.', ['Δp = 0.4 × (−4 − 6).','Δp = −4 kg·m/s.','Average net force = −4 / 0.05 = −80 N.','For 0.10 s, average net force = −40 N.','Longer time reduces average force for the same impulse.','These are net average values, not peak contact force; state the reference direction.']),
('Collision and torque','A fixed-surface drop is 1.44 m and rebound 0.81 m. Estimate e. A separate static lever has 15 N load at 0.4 m and effort arm 0.05 m. Find balancing effort.', ['e = √(0.81 / 1.44) = √0.5625.','e = 0.75, under no-drag vertical-bounce assumptions.','Load torque = 15 × 0.4 = 6 N·m.','Effort = 6 / 0.05 = 120 N.','Use perpendicular arms and static balance.','The lever calculation omits other forces and limb weight; restitution depends on both bodies and conditions.']),
('Flight diagram','Compare ideal no-spin flight with top-spin and back-spin flight for rightward travel in a stated common regime. Identify gravity, drag and the ideal-angle limitation.', ['Gravity continues acting downward in all cases.','Drag opposes relative motion; the ideal no-drag model omits it.','For rightward travel, top surface right identifies top spin, commonly adding downward Magnus force.','Top surface left identifies back spin, commonly adding upward Magnus force.','Real force depends on speed, surface, spin and flow regime.','45 degrees is an ideal equal-height fixed-speed range result, not a universal sport target angle.']),
('Coaching evidence','A learner’s stationary passing is accurate but decisions fail against defenders. Apply transfer and the analysis cycle, and explain one feedback choice.', ['The issue concerns training-to-competition transfer and omitted changing information demands.','Prepare relevant decision and execution criteria, then observe comparable attempts.','Evaluate the supported priority rather than assuming technique is the only cause.','Introduce a manageable progression with defenders and a useful scanning cue.','Provide terminal feedback distinguishing result and decision/process where appropriate.','Re-observe and compare; improved outcome alone does not prove the cause.'])]
EXTENDED=[
('Repeated-effort tournament','A fictional player faces repeated short rallies across a tournament, with a hot humid afternoon and little time between matches. Analyse energy supply, nutrition/hydration principles, environmental demands and recovery planning. Do not prescribe personal amounts or treatment.',[
'Begin by separating short high-intensity rally demands from lower-intensity movement and recovery between rallies. ATP–CP can contribute substantially to rapid efforts, but glycolytic and aerobic contributions remain present. Aerobic processes also support recovery and repeated-work capacity; do not describe three timed switches.',
'Carbohydrate availability can support demanding repeated activity and glycogen restoration. Protein contributes amino acids for repair and adaptation within adequate total intake. Pre-event food needs include established tolerance; during- and post-event needs depend on actual duration and access. GI alone cannot specify a complete diet.',
'Heat can reduce dry heat loss and humidity limits evaporation. Sweating visibly is not proof that sufficient cooling occurs. Increased thermal and circulatory demands can affect readiness across matches. Appropriate scheduling, shade, breaks and existing school procedures should be reviewed without treating acclimatisation as immediate protection.',
'Hydration needs depend on individual losses and conditions. Avoid a universal large drinking target or using fictional arithmetic as a prescription. Recovery includes rest, adequate energy, fluid and a realistic competition/training balance; a supplement cannot replace these foundations.',
'Evaluate the written plan using actual match timing, comparable performance and recovery observations. A persistent adverse pattern requires appropriate support and review, but one tired match does not diagnose overtraining. State what information is missing before making a stronger judgement.']),
('Skill improvement programme','A fictional netball team performs passes accurately without defenders, loses possession under pressure and has unclear support roles. Design and justify a coaching-analysis and team strategy, including transfer, feedback, leadership and cohesion.',[
'Prepare criteria for relevant scanning, pass selection, execution and support positioning. Observe several comparable game-like situations before assigning the cause. Accurate isolated execution alongside poor contested decisions suggests a possible transfer gap, not proof that every technical feature is already adequate.',
'Evaluate whether the main priority is stimulus identification, response selection, support spacing or execution. Use a manageable static-to-dynamic progression with changing defenders, preserving useful timing and decision information. Shaping can adjust difficulty; chaining can link components when the parts remain meaningful.',
'Provide focused terminal feedback explaining the observed process and result. A learner can use intrinsic outcome and balance information, supplemented by coach or video evidence. Avoid simultaneous corrections to every feature and use a suitable camera/checklist rather than unsupported claims from one image.',
'Use direct instruction where the task needs shared initial clarity and democratic discussion where experienced players can contribute useful observations. Agree communication calls, individual roles and a shared tactical goal. These address task cohesion; social friendship alone does not guarantee coordinated support.',
'Re-observe under comparable conditions, review decision quality as well as possession outcomes and adjust the plan. Unclear responsibilities can reduce contribution, but social loafing should not be diagnosed from one error. The written strategy supports actual supervised practice rather than certifying competitive proficiency.']),
('Biomechanical performance case','A fictional athlete throws a ball, another rotates with changing body shape, and a catcher stops a ball. Explain how segment timing, projection, angular momentum and impulse can be used in analysis. Include equations and assumptions; no practical aerial or contact instruction is required.',[
'A throw depends on coordinated segmental interaction, often involving proximal-to-distal sequencing. Timing matters more than simply making every segment peak together. Identify phases from suitable observation; forces on different bodies and at different times cannot simply be added as unrelated scalars.',
'Projection depends on speed, angle, height and the target. The ideal equal-height no-drag range equation R = v² sin(2θ)/g gives 45 degrees only at fixed speed under those assumptions. Real release height, drag, spin and technique can change the optimum; accuracy or net clearance may be the actual criterion.',
'For a simplified rotation, L = Iω is conserved only if net external torque is negligible. Moving mass closer to the axis reduces I and can increase ω while L remains constant. For example I changing from 4 to 2 with L = 12 changes ω from 3 to 6. This creates no extra angular momentum.',
'For stopping, impulse equals Δp = m(vf − vi), and average net force is Δp/Δt. Increasing the stopping interval for the same momentum change reduces average force. It does not establish peak force or provide an exact safe-contact technique.',
'Use labelled directions, units and model boundaries. Lever torque requires perpendicular moment arms and additional forces in a realistic system. The analysis supports explanation and teacher feedback; it cannot certify practical technique, safety or athlete-specific maximum values.']),
('Psychology and performance claims','A fictional team is worried before competition, uses only a winning goal and receives a supplement advertisement claiming guaranteed performance. Evaluate a psychological plan and the advertisement using evidence, risks, team dynamics and permitted status.',[
'Distinguish activation from perceived stress and confidence. The inverted-U is a hypothesis whose useful region depends on task, experience and individual response. Do not assume every athlete needs calming or diagnose a condition from competition nerves.',
'Add controllable process goals and measurable performance goals alongside the outcome aim. Define a SMARTER version and include evaluation and review. A familiar routine, task-focused self-talk or appropriate imagery can support attention; effectiveness should be checked rather than promised.',
'Clarify team roles, communication and shared aims to support task cohesion. Address inclusion and interpersonal needs separately as social cohesion. Reduced contribution may relate to diffuse responsibility, but alternative explanations should be considered before using a social-loafing label.',
'Evaluate a supplement through mechanism, relevant evidence, need, health risk and product contamination. Protein can support adequate amino-acid intake, caffeine has variable alertness/performance effects and possible unwanted effects, and creatine can support some repeated high-intensity demands. None guarantees technique, victory or recovery.',
'Anabolic agents, EPO-related substances and specified blood-manipulation methods are prohibited categories under current WADA rules. Natural physiology does not establish the legality of an administered substance. Check current AIS and Sport Integrity Australia sources; no student product use, dose or administration is recommended.'])]
