"""Original labelled vector models, with explicit text descriptions and limits."""
from html import escape as E
V={}
def text(x,y,t,size=18,anchor='start'):return f'<text x="{x}" y="{y}" font-size="{size}" fill="#173f42" text-anchor="{anchor}">{E(t)}</text>'
def line(x,y,a,b,arrow=False,color='#087f87'):return f'<path d="M{x},{y} L{a},{b}" fill="none" stroke="{color}" stroke-width="3"'+(' marker-end="url(#arr)"'if arrow else'')+'/>'
def box(x,y,w,h,t):return f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="12" fill="#e4f3ef" stroke="#14806e"/>'+text(x+w/2,y+h/2+6,t,17,'middle')
def add(k,title,body,caption):
 V[k]=dict(title=title,svg=f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 400" role="img" aria-label="{E(title)}"><title>{E(title)}</title><desc>{E(caption)}</desc><defs><marker id="arr" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10Z" fill="#087f87"/></marker></defs><rect width="640" height="400" fill="#fcfefd"/>'+text(24,34,title,22)+body+'</svg>',caption=caption,explain=caption,limit='Conceptual model, not to scale or an athlete-specific measurement. Read the stated assumptions.')
models={
'skeleton':('Bone sequences in limbs',['Arm: humerus → radius / ulna','Hand: carpals → metacarpals → phalanges','Leg: femur → tibia / fibula','Foot: tarsals → metatarsals → phalanges','Trunk: pelvis · sternum · ribs'],'Patella lies at the front of the knee. This map identifies anatomical order, not a full skeleton image.'),
'antagonists':('Opposing elbow actions',['Flexion: angle decreases','Biceps contributes to flexion','Extension: angle increases','Triceps contributes to extension','Co-contraction can stabilise'],'Roles depend on action and phase. Muscles pull through tendons and can develop tension without shortening.'),
'joint-actions':('Joint action and direction',['Flexion ↔ extension','Abduction ↔ adduction','Forearm: supination ↔ pronation','Ankle: dorsiflexion ↔ plantarflexion','Rotation differs from circumduction'],'Identify joint and anatomical reference; a segment can combine actions.'),
'circulation':('The two circulatory circuits',['Right heart → pulmonary arteries','Lung capillaries: gas exchange','Pulmonary veins → left heart','Systemic arteries → tissue capillaries','Systemic veins → right heart'],'Arteries carry away from the heart; veins return. Pulmonary vessels are exceptions to the usual oxygen-content association.'),
'ventilation':('Quiet inhalation',['Diaphragm contracts and descends','Thoracic / lung volume increases','Pressure falls below atmospheric','Air moves inward','Gas exchange at alveoli'],'Ventilation moves air; diffusion exchanges gases. Quiet exhalation uses relaxation and elastic recoil.'),
'energy':('Three overlapping energy pathways',['ATP–CP: high rate; limited capacity','Glycolytic: carbohydrate-based supply','Aerobic: sustained supply and recovery','All contribute to ATP resynthesis','Dominance changes with demand'],'Rows are comparative categories, not a chronological switch sequence. All three pathways contribute during activity.'),
'fitness':('Fitness capacities and demands',['Health: strength · endurance · flexibility','Muscular endurance · body composition','Performance: agility · balance · coordination','Reaction time · speed · power','One test samples a stated capacity'],'The endurance term in the first row means cardiorespiratory endurance. Several components interact; body composition is not a talent ranking.'),
 'training':('Training principles',['FITT: frequency · intensity · time · type','Specificity: match the demand','Progressive overload with recovery','Observe comparable performance','Review; lower stimulus → reversibility'],'These are planning considerations, not a prescribed session or load.'),
'skill':('Classify the actual task',['Gross ↔ fine','Open ↔ closed environment','Discrete · serial · continuous','Dimensions answer different questions','Indoor play can still be open'],'Opponent movement can make an indoor task unpredictable. Classification depends on the exact action.'),
'learning':('Learning stages and progression',['Cognitive: understand the task','Associative: refine coordination','Autonomous: less conscious demand','Stage depends on the particular skill','Preserve timing in practice progression'],'Stages do not follow a fixed age schedule; an experienced player can be learning a new skill cognitively.'),
'processing':('Information processing',['Input: relevant stimuli','Identify and select a response','Prepare and execute output','Sense movement and observe result','Feedback informs later decisions'],'A simplified continuous process. A wrong decision can coexist with fast execution.'),
'feedback':('Feedback has separate dimensions',['Source: intrinsic / extrinsic','Timing: concurrent / terminal','Content: results / performance','One message can combine dimensions','Coach after serve: extrinsic + terminal'],'Landed long is knowledge of results; contact behind is knowledge of performance. Timing and source are different classifications.'),
'goals':('Goal types and review',['Outcome: result relative to others','Performance: individual standard','Process: controllable action','Evaluate evidence of progress','Review and adjust the goal'],'SMARTER here means specific, measurable, achievable, relevant, time-bound, evaluated and reviewed. Variants exist.'),
'attention':('Nideffer attentional styles',['Broad external: scan the field','Narrow external: selected target','Broad internal: analyse options','Narrow internal: one sensation','Switch to suit the task and phase'],'Width and direction are separate dimensions, not fixed personality types.'),
'hierarchy':('Nested muscle organisation',['Muscle belly: epimysium','Fascicles: perimysium','Muscle fibres: endomysium','Myofibrils inside fibres','Sarcomeres contain actin and myosin'],'Organisational order moves inward; it does not encode relative size or show every cell structure.'),
'crossbridge':('Calcium regulation and ATP cycling',['Calcium → troponin → exposed sites','Myosin binds actin','Power stroke generates force','ATP binding permits detachment','ATP hydrolysis prepares next cycle'],'Calcium and ATP have distinct roles. ATP also supports calcium pumping; calcium does not become ATP.'),
'neuron':('Sensory input to motor output',['Sensory input → central nervous system','Brain / spinal cord processing','Motor-neuron output','Motor unit: neuron + its muscle fibres','Recruitment and firing rate grade force'],'Neurons have dendrites, cell body/nucleus and axon. The model omits many connections and is not wholly conscious in every action.'),
'recruitment':('Whole-muscle force is graded',['Recruitment: more active units','Higher demand: larger units can contribute','Rate coding: more impulses per second','Temporal summation supports force','Whole muscle is not all-or-none'],'Recruitment and rate coding are separate mechanisms. Preferential recruitment is a general size-principle pattern.'),
'fibres':('Compare fibre tendencies',['Type I: oxidative; fatigue resistant','Type IIa: fast; mixed capacities','Fast glycolytic: rapid; less resistant','Syllabus IIb; human label usually IIx','Muscles contain mixed populations'],'Characteristics contribute alongside training and mechanics. Appearance cannot identify an individual’s fibre distribution.'),
'nutrition':('Roles across competition',['Before: fuel availability and tolerance','During: event-dependent fuel / fluid needs','After: glycogen replenishment and repair','Carbohydrate differs from protein roles','GI alone is not a full meal plan'],'General education provides no personal amounts, restrictions or supplement-use instructions.'),
'heat':('Four heat-transfer mechanisms',['Radiation: emitted thermal energy','Convection: moving air or fluid','Conduction: direct contact','Evaporation: liquid sweat → vapour','Humidity can limit evaporation'],'Temperature gradients govern dry exchange; hot surroundings can add heat. Sweat must evaporate to provide evaporative cooling.'),
'environment':('Different environmental demands',['Heat: thermal gradients and evaporation','Humidity: lower evaporation potential','Cold: greater potential heat loss','Altitude: lower oxygen partial pressure','Acclimatisation takes time and varies'],'Altitude does not remove the oxygen fraction. This is not an exposure schedule or treatment plan.'),
'enhancers':('Evaluate a performance claim',['Identify proposed physiological effect','Connect it to a specific demand','Evaluate evidence and limits','Consider health and product risks','Check current AIS / WADA / SIA sources'],'Mechanism, safety and permitted status are different questions. No dose, product recommendation or administration instructions.'),
'periodisation':('Nested planning periods',['Macrocycle: broad planning period','Mesocycle: block within the period','Microcycle: shorter recurring schedule','Prepare · compete · transition','Monitor recovery and review the plan'],'Durations depend on context. Tapering reduces load while preserving useful stimulus, rather than ending all training indefinitely.'),
'transfer':('Transfer category and effect',['Skill → skill','Theory → practice','Training → competition','Effect: positive / negative / zero','Judge evidence in comparable conditions'],'The first three rows are categories, not stages. Effect identifies help, interference or little detectable influence.'),
'analysis':('Qualitative movement analysis',['Prepare: task, criteria and evidence','Observe comparable attempts','Evaluate and select a supported priority','Intervene with a suitable change','Re-observe and compare'],'The Knudson and Morrison cycle is iterative coaching analysis, not a clinical diagnosis from one image.'),
'sequence':('Segment interaction in a throw',['Leg and trunk contribution','Upper-arm movement','Forearm and hand movement','Distal speed depends on timing','Observe phases, not one still image'],'Actions overlap and depend on the task. Scalar forces at different times cannot simply be added.'),
'drag':('Fluid-force mechanisms',['Pressure drag: distribution and wake','Surface drag: skin friction','Wave drag: free-surface waves','Shape, speed and flow determine effects','Equal transit time is not required'],'Turbulence is not universally worse; boundary-layer changes can influence separation and total drag. Bernoulli has assumptions.'),
'cohesion':('Group aims, relationships and effort',['Task cohesion: coordinated shared aims','Social cohesion: interpersonal connection','Roles, communication and leadership','Meaningful individual responsibility','Review evidence rather than blame'],'Task success does not prove inclusion. Low output has alternatives to social loafing, including unclear instruction.'),
'exam':('Current written examination',['Reading: 10 min; working: 150 min','Section 1: 20 MCQ · 20% · 30 min','Section 2: 6–10 items · 50% · 70 min','Section 3: choose 2 of 4 · 30% · 50 min','Use the actual paper instructions'],'Current Year 12 design details are separate from school-assessment and combined written/practical weights.')}
for k,(title,rows,cap) in models.items():
 b=''.join(box(65,60+i*60,510,42,t) for i,t in enumerate(rows))
 add(k,title,b,cap)
add('cardiac-output','Cardiac output and cancelling units',box(25,95,265,70,'HR: beats / minute')+box(350,95,265,70,'SV: mL / beat')+text(320,142,'×',28,'middle')+line(320,170,320,218,True)+box(95,225,450,55,'Output: mL / minute')+box(95,315,450,45,'Divide by 1000 → L / minute'),'HR × SV cancels beat units. 150 × 120 = 18000 mL/min = 18 L/min in the fictional example.')
add('vectors','Distance and displacement differ',line(100,270,100,100,True)+line(100,100,490,100,True)+line(490,100,490,270,True)+line(490,270,100,270,True)+text(295,195,'Return to start',22,'middle')+text(320,340,'Distance > 0; net displacement = 0',19,'middle'),'A complete loop has positive distance and zero displacement. Average speed is positive but average velocity is zero for the whole loop.')
add('projectile','Ideal projectile and downward acceleration',line(65,320,570,320)+line(65,320,65,65)+'<path d="M65 320 Q315 -60 565 320" fill="none" stroke="#14806e" stroke-width="4"/>'+line(245,145,245,240,True)+text(260,222,'Gravity',18)+line(65,320,155,230,True)+text(105,213,'Release',18)+text(320,370,'No drag · fixed speed · equal heights',18,'middle'),'The ideal parabola has constant horizontal velocity and downward acceleration. The curve is qualitative; 45 degrees is not a universal sport optimum.')
add('balance','Static support and line of gravity','<polygon points="110,300 425,300 385,330 70,330" fill="#d9ede8"/>'+line(250,95,250,310)+'<circle cx="250" cy="135" r="11" fill="#d16c34"/>'+text(280,142,'Centre of gravity',18)+text(280,220,'Vertical line of gravity',18)+text(125,365,'Base of support',19),'The line of gravity lies inside the base in this static model. Dynamic movement needs additional force and active-control analysis.')
add('newton','Interaction forces act on different bodies',box(30,115,230,85,'Runner')+box(380,115,230,85,'Ground')+line(260,135,375,135,True)+line(380,180,265,180,True)+text(320,90,'Runner on ground →',17,'middle')+text(320,235,'← Ground on runner',17,'middle')+text(320,320,'Equal and opposite; different bodies',19,'middle'),'Arrows connect the bodies, not their motion. The two interaction forces do not cancel on the runner.')
add('lever','Third class: effort between axis and load',line(75,240,550,240)+'<polygon points="75,240 55,275 95,275" fill="#173f42"/>'+line(180,335,180,240,True)+line(530,125,530,240,True)+text(75,305,'Axis',18,'middle')+text(180,365,'Effort',18,'middle')+text(530,95,'Load',18,'middle')+text(320,190,'Use perpendicular moment arms',18,'middle'),'The ideal lever omits limb weight and other forces. Torque equals force times perpendicular moment arm; short effort arm creates a force disadvantage.')
add('arousal','Inverted-U: an illustrative hypothesis',line(80,315,565,315)+line(80,315,80,80)+'<path d="M95 300 C195 300 220 90 315 90 C410 90 435 300 550 300" fill="none" stroke="#14806e" stroke-width="4"/>'+text(320,360,'Arousal →',18,'middle')+text(100,65,'Performance',18)+text(315,215,'Optimum varies',18,'middle'),'Task, experience and individual differences affect the relationship. This is a hypothesis without diagnostic numerical scores.')
b=''
for y,w in [(125,490),(255,380)]:
 x=(640-w)/2;b+=line(x,y-35,x,y+35)+line(x+w,y-35,x+w,y+35)+line(x,y,x+255,y,color='#d16c34')+line(x+w-255,y,x+w,y,color='#d16c34')+line(230,y+12,410,y+12)
b+=text(24,75,'Before',18)+text(24,215,'Shorter',18)+text(320,330,'Z lines closer; filaments unchanged in length',17,'middle')+text(320,365,'A constant; I band and H zone narrow',18,'middle')
add('sarcomere','Filaments slide into greater overlap',b,'Orange actin extends from Z lines; the green thick-filament span remains fixed. Z lines move closer in the lower schematic; the geometry is qualitative.')
add('force-length','Active force–length and optimal overlap',line(70,315,570,315)+line(70,315,70,75)+'<path d="M85 300 C155 290 200 110 275 110 L335 110 C410 110 460 290 550 300" fill="none" stroke="#14806e" stroke-width="4"/>'+text(90,65,'Active force',18)+text(320,360,'Muscle length →',18,'middle')+text(320,205,'Intermediate optimal region',17,'middle'),'Active force is lower at excessive shortening or lengthening. Passive and total force have different curves; this diagram has no athlete-specific scale.')
add('tactics','Support options and defender constraints','<rect x="65" y="75" width="510" height="260" fill="#edf7ed" stroke="#14806e"/>'+''.join(f'<circle cx="{x}" cy="{y}" r="13" fill="{c}"/>'for x,y,c in [(280,255,'#087f87'),(130,145,'#087f87'),(480,145,'#087f87'),(265,150,'#d16c34'),(445,200,'#d16c34')])+line(280,255,140,153,True)+line(280,255,470,153,True)+text(320,365,'Teal: attack · orange: defence',18,'middle'),'The ball-carrier has two wide options with different defender constraints. A schematic of spacing, not sport rules or a compulsory formation.')
add('impulse','Equal impulse with different force and time',line(65,320,570,320)+line(65,320,65,70)+'<rect x="115" y="100" width="95" height="220" fill="#dcefe8" stroke="#14806e"/><rect x="335" y="210" width="190" height="110" fill="#e4e5f5" stroke="#655ba6"/>'+text(160,85,'Higher / shorter',16,'middle')+text(430,195,'Lower / longer',16,'middle')+text(320,365,'Equal area → equal impulse',19,'middle'),'On a force–time graph equal signed area means equal impulse. The two illustrated rectangles have equal area; actual force shape and peak need data.')
add('bounce','Vertical bounce: e = √(rebound / drop)',line(65,330,575,330)+line(185,100,185,328,True)+line(420,325,420,184,True)+text(155,75,'Drop height',18)+text(380,158,'Rebound height',18)+text(320,375,'Fixed surface · no drag · same height reference',16,'middle'),'The square-root estimate is for the stated simplified vertical bounce. Restitution depends on both interacting bodies and collision conditions.')
add('angular','Conserved momentum: redistribute mass',box(35,95,270,95,'I = 4; ω = 3')+box(335,95,270,95,'I = 2; ω = 6')+line(310,145,332,145,True)+box(125,250,390,65,'L = Iω = 12 in both states')+text(320,355,'Negligible net external torque',19,'middle'),'I in kg·m², ω in rad/s, L in kg·m²/s. Lower inertia increases angular velocity without creating angular momentum.')
add('magnus','Travel right: common Magnus directions','<circle cx="185" cy="190" r="55" fill="#edf5f1" stroke="#087f87"/><circle cx="455" cy="190" r="55" fill="#edf5f1" stroke="#087f87"/>'+line(125,105,245,105,True)+line(515,105,395,105,True)+line(185,250,185,310,True)+line(455,250,455,170,True)+text(185,70,'Top spin: top surface →',16,'middle')+text(455,70,'Back spin: top surface ←',16,'middle')+text(185,345,'Force: down',18,'middle')+text(455,345,'Force: up',18,'middle')+text(320,385,'Both balls travel right; gravity still acts',17,'middle'),'Spin arrows are relative to the ball centre, with a stated side view and rightward travel. The common force directions depend on regime; magnitudes are not to scale.')

add('force-velocity','Concentric force–velocity tendency',line(70,315,570,315)+line(70,315,70,75)+'<path d="M90 90 C150 190 280 280 550 300" fill="none" stroke="#14806e" stroke-width="4"/>'+text(95,65,'Maximal force',18)+text(320,360,'Shortening velocity →',18,'middle'),'Under comparable concentric conditions, maximal force capacity generally falls as shortening speed rises. Power depends on both force and velocity. No athlete-specific numerical scale.')
