window.SCIENCE_VAULT_QUESTIONS = [
/*
Individual questions extracted from uploaded assessments are indexed here.
Schema:
{id,title,text,year,strand,topic,subtopic,marks,type,options,answer,source,answerSource,school}
Questions are never generated by the Test Maker.
*/
];
