window.SCIENCE_VAULT_RESOURCES = [
  {
    "id": "waves-1-waves-overview-pptx",
    "title": "1. WAVES overview",
    "year": "Year 11",
    "course": "Physics",
    "strand": "",
    "unit": "Unit 2 – Waves, nuclear and electrical physics",
    "topic": "Waves",
    "subtopic": "Wave properties, wave equation and wave graphs",
    "school": "",
    "type": "PowerPoint",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 11 Physics/Unit 2 - Waves/1. WAVES _overview.pptx",
    "preview": "",
    "description": "PowerPoint resource for Wave properties, wave equation and wave graphs."
  },
  {
    "id": "waves-2-waves-reflectionrefrdiffetc-pptx",
    "title": "2. WAVES ReflectionRefrDiffetc",
    "year": "Year 11",
    "course": "Physics",
    "strand": "",
    "unit": "Unit 2 – Waves, nuclear and electrical physics",
    "topic": "Waves",
    "subtopic": "Reflection, refraction, diffraction and seismic waves",
    "school": "",
    "type": "PowerPoint",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 11 Physics/Unit 2 - Waves/2. WAVES_ReflectionRefrDiffetc.pptx",
    "preview": "",
    "description": "PowerPoint resource for Reflection, refraction, diffraction and seismic waves."
  },
  {
    "id": "waves-3-superposition-interferenceresonance-pptx",
    "title": "3. Superposition InterferenceResonance",
    "year": "Year 11",
    "course": "Physics",
    "strand": "",
    "unit": "Unit 2 – Waves, nuclear and electrical physics",
    "topic": "Waves",
    "subtopic": "Superposition, interference, resonance and standing waves",
    "school": "",
    "type": "PowerPoint",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 11 Physics/Unit 2 - Waves/3. Superposition InterferenceResonance.pptx",
    "preview": "",
    "description": "PowerPoint resource for Superposition, interference, resonance and standing waves."
  },
  {
    "id": "waves-waves-in-pipe-summary-docx",
    "title": "Waves in pipe summary",
    "year": "Year 11",
    "course": "Physics",
    "strand": "",
    "unit": "Unit 2 – Waves, nuclear and electrical physics",
    "topic": "Waves",
    "subtopic": "Standing waves in open and closed pipes",
    "school": "",
    "type": "Notes",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 11 Physics/Unit 2 - Waves/Waves in pipe summary.docx",
    "preview": "",
    "description": "Notes resource for Standing waves in open and closed pipes."
  },
  {
    "id": "waves-waves-worksheet-1-docx",
    "title": "Waves Worksheet 1",
    "year": "Year 11",
    "course": "Physics",
    "strand": "",
    "unit": "Unit 2 – Waves, nuclear and electrical physics",
    "topic": "Waves",
    "subtopic": "Wave properties, wave equation and standing waves",
    "school": "",
    "type": "Worksheet",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 11 Physics/Unit 2 - Waves/Waves Worksheet 1.docx",
    "preview": "",
    "description": "Worksheet resource for Wave properties, wave equation and standing waves."
  },
  {
    "id": "waves-y11-waves-student-review-sheet-pdf",
    "title": "Y11 Waves student review sheet",
    "year": "Year 11",
    "course": "Physics",
    "strand": "",
    "unit": "Unit 2 – Waves, nuclear and electrical physics",
    "topic": "Waves",
    "subtopic": "Waves revision",
    "school": "",
    "type": "Revision",
    "format": "PDF",
    "answers": false,
    "file": "resources/Year 11 Physics/Unit 2 - Waves/Y11 Waves student review sheet.pdf",
    "preview": "resources/Year 11 Physics/Unit 2 - Waves/Y11 Waves student review sheet.pdf",
    "description": "Revision resource for Waves revision."
  }
];
