window.SCIENCE_VAULT_RESOURCES = [
  {
    "id": "y7-bio-001",
    "title": "1 Characteristics of Living Things",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Characteristics and classification of living things",
    "school": "",
    "type": "PowerPoints",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/1 Characteristics of Living Things.pptx",
    "preview": "",
    "description": "PowerPoints resource for Characteristics and classification of living things.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification"
    ]
  },
  {
    "id": "y7-bio-002",
    "title": "1 Characteristics of Living Things_answers",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Characteristics and classification of living things",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": true,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/1 Characteristics of Living Things_answers.docx",
    "preview": "",
    "description": "Worksheets resource for Characteristics and classification of living things.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification"
    ]
  },
  {
    "id": "y7-bio-003",
    "title": "10 BEAN COUNTER v2",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Adaptations and survival",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/10 BEAN COUNTER v2.docx",
    "preview": "",
    "description": "Worksheets resource for Adaptations and survival.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "adaptations",
      "adaptations and survival",
      "survival",
      "camouflage"
    ]
  },
  {
    "id": "y7-bio-004",
    "title": "10 BEAN COUNTER",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Adaptations and survival",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/10 BEAN COUNTER.docx",
    "preview": "",
    "description": "Worksheets resource for Adaptations and survival.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "adaptations",
      "adaptations and survival",
      "survival",
      "camouflage"
    ]
  },
  {
    "id": "y7-bio-005",
    "title": "10 MATCHSTICK CAMOUFLAGE",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Adaptations and survival",
    "school": "",
    "type": "Other Resources",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/10 MATCHSTICK CAMOUFLAGE.docx",
    "preview": "",
    "description": "Other Resources resource for Adaptations and survival.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "adaptations",
      "adaptations and survival",
      "survival",
      "camouflage"
    ]
  },
  {
    "id": "y7-bio-006",
    "title": "11 Types of Adaptations Activity (pages 4-16)",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Adaptations and survival",
    "school": "",
    "type": "Worksheets",
    "format": "PDF",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/11 Types of Adaptations Activity (pages 4-16).pdf",
    "preview": "resources/Year 7/Biological Sciences/PowerPoints/11 Types of Adaptations Activity (pages 4-16).pdf",
    "description": "Worksheets resource for Adaptations and survival.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "adaptations",
      "adaptations and survival",
      "survival",
      "camouflage"
    ]
  },
  {
    "id": "y7-bio-007",
    "title": "11 Types of Adaptations Activity Worksheet Option 1",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Adaptations and survival",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/11 Types of Adaptations Activity Worksheet Option 1.docx",
    "preview": "",
    "description": "Worksheets resource for Adaptations and survival.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "adaptations",
      "adaptations and survival",
      "survival",
      "camouflage"
    ]
  },
  {
    "id": "y7-bio-008",
    "title": "11 Types of Adaptations Activity Worksheet Option 2",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Adaptations and survival",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/11 Types of Adaptations Activity Worksheet Option 2.docx",
    "preview": "",
    "description": "Worksheets resource for Adaptations and survival.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "adaptations",
      "adaptations and survival",
      "survival",
      "camouflage"
    ]
  },
  {
    "id": "y7-bio-009",
    "title": "12 Classification Keys",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Classification keys",
    "school": "",
    "type": "PowerPoints",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/12 Classification Keys.pptx",
    "preview": "",
    "description": "PowerPoints resource for Classification keys.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "classification keys",
      "dichotomous keys",
      "branched keys",
      "tabular keys",
      "developing classification keys"
    ]
  },
  {
    "id": "y7-bio-010",
    "title": "12 Planet Pamishan",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Classification keys",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/12 Planet Pamishan.docx",
    "preview": "",
    "description": "Worksheets resource for Classification keys.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "classification keys",
      "dichotomous keys",
      "branched keys",
      "tabular keys",
      "developing classification keys"
    ]
  },
  {
    "id": "y7-bio-011",
    "title": "12 Planet Pamishan_answers",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Classification keys",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": true,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/12 Planet Pamishan_answers.docx",
    "preview": "",
    "description": "Worksheets resource for Classification keys.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "classification keys",
      "dichotomous keys",
      "branched keys",
      "tabular keys",
      "developing classification keys"
    ]
  },
  {
    "id": "y7-bio-012",
    "title": "13 Drawing Branched Keys",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Classification keys",
    "school": "",
    "type": "PowerPoints",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/13 Drawing Branched Keys.pptx",
    "preview": "",
    "description": "PowerPoints resource for Classification keys.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "classification keys",
      "dichotomous keys",
      "branched keys",
      "tabular keys",
      "developing classification keys"
    ]
  },
  {
    "id": "y7-bio-013",
    "title": "14 Drawing Tabular Keys",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Classification keys",
    "school": "",
    "type": "PowerPoints",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/14 Drawing Tabular Keys.pptx",
    "preview": "",
    "description": "PowerPoints resource for Classification keys.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "classification keys",
      "dichotomous keys",
      "branched keys",
      "tabular keys",
      "developing classification keys"
    ]
  },
  {
    "id": "y7-bio-014",
    "title": "15 Drawing Branched and Tabular Keys Practice",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Classification keys",
    "school": "",
    "type": "Practicals",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/15 Drawing Branched and Tabular Keys Practice.pptx",
    "preview": "",
    "description": "Practicals resource for Classification keys.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "classification keys",
      "dichotomous keys",
      "branched keys",
      "tabular keys",
      "developing classification keys"
    ]
  },
  {
    "id": "y7-bio-015",
    "title": "16 Classification of Living Things",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Characteristics and classification of living things",
    "school": "",
    "type": "PowerPoints",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/16 Classification of Living Things.pptx",
    "preview": "",
    "description": "PowerPoints resource for Characteristics and classification of living things.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification"
    ]
  },
  {
    "id": "y7-bio-016",
    "title": "16 Scientific Naming - Connect version",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Scientific naming",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/16 Scientific Naming - Connect version.docx",
    "preview": "",
    "description": "Worksheets resource for Scientific naming.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "scientific naming",
      "binomial nomenclature",
      "genus",
      "species",
      "classification hierarchy",
      "kingdom to species"
    ]
  },
  {
    "id": "y7-bio-017",
    "title": "16 Scientific Naming - answers",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Scientific naming",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": true,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/16 Scientific Naming - answers.docx",
    "preview": "",
    "description": "Worksheets resource for Scientific naming.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "scientific naming",
      "binomial nomenclature",
      "genus",
      "species",
      "classification hierarchy",
      "kingdom to species"
    ]
  },
  {
    "id": "y7-bio-018",
    "title": "16 Scientific Naming - printable version",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Scientific naming",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/16 Scientific Naming - printable version.docx",
    "preview": "",
    "description": "Worksheets resource for Scientific naming.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "scientific naming",
      "binomial nomenclature",
      "genus",
      "species",
      "classification hierarchy",
      "kingdom to species"
    ]
  },
  {
    "id": "y7-bio-019",
    "title": "17 Kingdoms",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Kingdoms",
    "school": "",
    "type": "PowerPoints",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/17 Kingdoms.pptx",
    "preview": "",
    "description": "PowerPoints resource for Kingdoms.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "kingdoms",
      "classification hierarchy",
      "kingdom to species"
    ]
  },
  {
    "id": "y7-bio-020",
    "title": "17 Understanding Kingdoms (2)",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Kingdoms",
    "school": "",
    "type": "Other Resources",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/17 Understanding Kingdoms (2).docx",
    "preview": "",
    "description": "Other Resources resource for Kingdoms.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "kingdoms",
      "classification hierarchy",
      "kingdom to species"
    ]
  },
  {
    "id": "y7-bio-021",
    "title": "17 Understanding Kingdoms",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Kingdoms",
    "school": "",
    "type": "Other Resources",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/17 Understanding Kingdoms.docx",
    "preview": "",
    "description": "Other Resources resource for Kingdoms.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "kingdoms",
      "classification hierarchy",
      "kingdom to species"
    ]
  },
  {
    "id": "y7-bio-022",
    "title": "17 Understanding Kingdoms_answers",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Kingdoms",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": true,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/17 Understanding Kingdoms_answers.docx",
    "preview": "",
    "description": "Worksheets resource for Kingdoms.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "kingdoms",
      "classification hierarchy",
      "kingdom to species"
    ]
  },
  {
    "id": "y7-bio-023",
    "title": "18 Vertebrate & Arthropod Graphic Organiser Filled",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Animal classification",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": true,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/18 Vertebrate & Arthropod Graphic Organiser Filled.docx",
    "preview": "",
    "description": "Worksheets resource for Animal classification.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "animal classification",
      "vertebrates",
      "invertebrates",
      "arthropods",
      "phyla",
      "classification hierarchy",
      "kingdom to species"
    ]
  },
  {
    "id": "y7-bio-024",
    "title": "18 Vertebrate & Arthropod Graphic Organiser",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Animal classification",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/18 Vertebrate & Arthropod Graphic Organiser.docx",
    "preview": "",
    "description": "Worksheets resource for Animal classification.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "animal classification",
      "vertebrates",
      "invertebrates",
      "arthropods",
      "phyla",
      "classification hierarchy",
      "kingdom to species"
    ]
  },
  {
    "id": "y7-bio-025",
    "title": "18 Vertebrate & Arthropod Graphic Organiser_LowLit",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Animal classification",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/18 Vertebrate & Arthropod Graphic Organiser_LowLit.docx",
    "preview": "",
    "description": "Worksheets resource for Animal classification.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "animal classification",
      "vertebrates",
      "invertebrates",
      "arthropods",
      "phyla",
      "classification hierarchy",
      "kingdom to species"
    ]
  },
  {
    "id": "y7-bio-026",
    "title": "18 Vertebrates",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Animal classification",
    "school": "",
    "type": "PowerPoints",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/18 Vertebrates.pptx",
    "preview": "",
    "description": "PowerPoints resource for Animal classification.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "animal classification",
      "vertebrates",
      "invertebrates",
      "arthropods",
      "phyla",
      "classification hierarchy",
      "kingdom to species"
    ]
  },
  {
    "id": "y7-bio-027",
    "title": "19 Arthropods",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Animal classification",
    "school": "",
    "type": "PowerPoints",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/19 Arthropods.pptx",
    "preview": "",
    "description": "PowerPoints resource for Animal classification.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "animal classification",
      "vertebrates",
      "invertebrates",
      "arthropods",
      "phyla",
      "classification hierarchy",
      "kingdom to species"
    ]
  },
  {
    "id": "y7-bio-028",
    "title": "2 Food Chains",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Ecosystems and feeding relationships",
    "subtopic": "Food chains",
    "school": "",
    "type": "PowerPoints",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/2 Food Chains.pptx",
    "preview": "",
    "description": "PowerPoints resource for Food chains.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "food chains",
      "producer",
      "consumer",
      "decomposer",
      "producers consumers and decomposers",
      "energy flow in ecosystems",
      "feeding relationships"
    ]
  },
  {
    "id": "y7-bio-029",
    "title": "20 Other Phyla Graphic Organiser",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Animal classification",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/20 Other Phyla Graphic Organiser.docx",
    "preview": "",
    "description": "Worksheets resource for Animal classification.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "animal classification",
      "vertebrates",
      "invertebrates",
      "arthropods",
      "phyla",
      "classification hierarchy",
      "kingdom to species"
    ]
  },
  {
    "id": "y7-bio-030",
    "title": "20 Other Phyla",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Animal classification",
    "school": "",
    "type": "PowerPoints",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/20 Other Phyla.pptx",
    "preview": "",
    "description": "PowerPoints resource for Animal classification.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "animal classification",
      "vertebrates",
      "invertebrates",
      "arthropods",
      "phyla",
      "classification hierarchy",
      "kingdom to species"
    ]
  },
  {
    "id": "y7-bio-031",
    "title": "21 Identifying Other Phyla specimens",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Animal classification",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/21 Identifying Other Phyla specimens.docx",
    "preview": "",
    "description": "Worksheets resource for Animal classification.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "animal classification",
      "vertebrates",
      "invertebrates",
      "arthropods",
      "phyla",
      "classification hierarchy",
      "kingdom to species"
    ]
  },
  {
    "id": "y7-bio-032",
    "title": "21 Identifying Phylum and Class specimens",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Animal classification",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/21 Identifying Phylum and Class specimens.docx",
    "preview": "",
    "description": "Worksheets resource for Animal classification.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "animal classification",
      "vertebrates",
      "invertebrates",
      "arthropods",
      "phyla",
      "classification hierarchy",
      "kingdom to species"
    ]
  },
  {
    "id": "y7-bio-033",
    "title": "22 All Graphic Organisers",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Classification",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/22 All Graphic Organisers.docx",
    "preview": "",
    "description": "Worksheets resource for Classification.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification"
    ]
  },
  {
    "id": "y7-bio-034",
    "title": "22 Classification Test Revision ANSWERS",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Characteristics and classification of living things",
    "school": "",
    "type": "Revision",
    "format": "DOCX",
    "answers": true,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/22 Classification Test Revision ANSWERS.docx",
    "preview": "",
    "description": "Revision resource for Characteristics and classification of living things.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "revision",
      "test revision"
    ]
  },
  {
    "id": "y7-bio-035",
    "title": "22 Classification Test Revision",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Characteristics and classification of living things",
    "school": "",
    "type": "Revision",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/22 Classification Test Revision.docx",
    "preview": "",
    "description": "Revision resource for Characteristics and classification of living things.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "revision",
      "test revision"
    ]
  },
  {
    "id": "y7-bio-036",
    "title": "3 Food Chains Questions (Connect Version)",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Ecosystems and feeding relationships",
    "subtopic": "Food chains",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/3 Food Chains Questions (Connect Version).docx",
    "preview": "",
    "description": "Worksheets resource for Food chains.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "food chains",
      "producer",
      "consumer",
      "decomposer",
      "producers consumers and decomposers",
      "energy flow in ecosystems",
      "feeding relationships"
    ]
  },
  {
    "id": "y7-bio-037",
    "title": "3 Food Chains Questions (Printout Version)",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Ecosystems and feeding relationships",
    "subtopic": "Food chains",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/3 Food Chains Questions (Printout Version).docx",
    "preview": "",
    "description": "Worksheets resource for Food chains.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "food chains",
      "producer",
      "consumer",
      "decomposer",
      "producers consumers and decomposers",
      "energy flow in ecosystems",
      "feeding relationships"
    ]
  },
  {
    "id": "y7-bio-038",
    "title": "3 Food chain display pyramid blank",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Ecosystems and feeding relationships",
    "subtopic": "Food chains",
    "school": "",
    "type": "Other Resources",
    "format": "PDF",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/3 Food chain display pyramid blank.pdf",
    "preview": "resources/Year 7/Biological Sciences/PowerPoints/3 Food chain display pyramid blank.pdf",
    "description": "Other Resources resource for Food chains.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "food chains",
      "producer",
      "consumer",
      "decomposer",
      "producers consumers and decomposers",
      "energy flow in ecosystems",
      "feeding relationships"
    ]
  },
  {
    "id": "y7-bio-039",
    "title": "3 Food chain display pyramid",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Ecosystems and feeding relationships",
    "subtopic": "Food chains",
    "school": "",
    "type": "Other Resources",
    "format": "PDF",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/3 Food chain display pyramid.pdf",
    "preview": "resources/Year 7/Biological Sciences/PowerPoints/3 Food chain display pyramid.pdf",
    "description": "Other Resources resource for Food chains.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "food chains",
      "producer",
      "consumer",
      "decomposer",
      "producers consumers and decomposers",
      "energy flow in ecosystems",
      "feeding relationships"
    ]
  },
  {
    "id": "y7-bio-040",
    "title": "4 Food Webs",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Ecosystems and feeding relationships",
    "subtopic": "Food webs",
    "school": "",
    "type": "PowerPoints",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/4 Food Webs.pptx",
    "preview": "",
    "description": "PowerPoints resource for Food webs.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "food webs",
      "producer",
      "consumer",
      "decomposer",
      "producers consumers and decomposers",
      "energy flow in ecosystems",
      "feeding relationships"
    ]
  },
  {
    "id": "y7-bio-041",
    "title": "5 Drawing Food Webs",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Ecosystems and feeding relationships",
    "subtopic": "Food webs",
    "school": "",
    "type": "Other Resources",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/5 Drawing Food Webs.docx",
    "preview": "",
    "description": "Other Resources resource for Food webs.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "food webs",
      "producer",
      "consumer",
      "decomposer",
      "producers consumers and decomposers",
      "energy flow in ecosystems",
      "feeding relationships"
    ]
  },
  {
    "id": "y7-bio-042",
    "title": "5 Wooly Web Activity",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Ecosystems and feeding relationships",
    "subtopic": "Food webs",
    "school": "",
    "type": "Worksheets",
    "format": "PDF",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/5 Wooly Web Activity.pdf",
    "preview": "resources/Year 7/Biological Sciences/PowerPoints/5 Wooly Web Activity.pdf",
    "description": "Worksheets resource for Food webs.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "food webs",
      "producer",
      "consumer",
      "decomposer",
      "producers consumers and decomposers",
      "energy flow in ecosystems",
      "feeding relationships"
    ]
  },
  {
    "id": "y7-bio-043",
    "title": "6 Construct a Giant Food Web ANSWERS",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Ecosystems and feeding relationships",
    "subtopic": "Food webs",
    "school": "",
    "type": "Worksheets",
    "format": "PDF",
    "answers": true,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/6 Construct a Giant Food Web ANSWERS.pdf",
    "preview": "resources/Year 7/Biological Sciences/PowerPoints/6 Construct a Giant Food Web ANSWERS.pdf",
    "description": "Worksheets resource for Food webs.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "food webs",
      "producer",
      "consumer",
      "decomposer",
      "producers consumers and decomposers",
      "energy flow in ecosystems",
      "feeding relationships"
    ]
  },
  {
    "id": "y7-bio-044",
    "title": "6 Construct a Giant Food Web",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Ecosystems and feeding relationships",
    "subtopic": "Food webs",
    "school": "",
    "type": "Worksheets",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/6 Construct a Giant Food Web.docx",
    "preview": "",
    "description": "Worksheets resource for Food webs.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "food webs",
      "producer",
      "consumer",
      "decomposer",
      "producers consumers and decomposers",
      "energy flow in ecosystems",
      "feeding relationships"
    ]
  },
  {
    "id": "y7-bio-045",
    "title": "7 Growing Plants Investigation",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Ecosystems and feeding relationships",
    "subtopic": "Producers and plant growth",
    "school": "",
    "type": "Practicals",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/7 Growing Plants Investigation.pptx",
    "preview": "",
    "description": "Practicals resource for Producers and plant growth.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "producers",
      "plant growth",
      "producer",
      "producers consumers and decomposers",
      "energy flow in ecosystems",
      "feeding relationships"
    ]
  },
  {
    "id": "y7-bio-046",
    "title": "8 Impacts Info Sheet",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Ecosystems and feeding relationships",
    "subtopic": "Human impacts on ecosystems",
    "school": "",
    "type": "Other Resources",
    "format": "DOCX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/8 Impacts Info Sheet.docx",
    "preview": "",
    "description": "Other Resources resource for Human impacts on ecosystems.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "human impacts",
      "human activity",
      "impacts of human activity on feeding relationships",
      "ecosystem impacts",
      "feeding relationships"
    ]
  },
  {
    "id": "y7-bio-047",
    "title": "8 Impacts Posters",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Ecosystems and feeding relationships",
    "subtopic": "Human impacts on ecosystems",
    "school": "",
    "type": "PowerPoints",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/8 Impacts Posters.pptx",
    "preview": "",
    "description": "PowerPoints resource for Human impacts on ecosystems.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "human impacts",
      "human activity",
      "impacts of human activity on feeding relationships",
      "ecosystem impacts",
      "feeding relationships"
    ]
  },
  {
    "id": "y7-bio-048",
    "title": "9 Adaptations",
    "year": "Year 7",
    "course": "Science",
    "strand": "Biological Sciences",
    "unit": "",
    "topic": "Classification",
    "subtopic": "Adaptations and survival",
    "school": "",
    "type": "PowerPoints",
    "format": "PPTX",
    "answers": false,
    "file": "resources/Year 7/Biological Sciences/PowerPoints/9 Adaptations.pptx",
    "preview": "",
    "description": "PowerPoints resource for Adaptations and survival.",
    "keywords": [
      "year 7",
      "science",
      "biological sciences",
      "classification",
      "diversity of life",
      "living things",
      "characteristics used for classification",
      "adaptations",
      "adaptations and survival",
      "survival",
      "camouflage"
    ]
  }
];
