
function isPublicResource(r){const p=String((r&&r.file)||'').replace(/\\/g,'/'),n=p.split('/').pop()||'',l=n.toLowerCase(),parts=p.toLowerCase().split('/');if(!n)return false;if(/^\.(ds_store|gitkeep|gitignore|directory)$/i.test(n)||/^(thumbs\.db|desktop\.ini)$/i.test(n))return false;if(/^~\$/.test(n)||/\.(tmp|temp|bak|old|orig|part|crdownload|icloud|lnk)$/i.test(n))return false;if(/(^|[ ._-])(copy|backup|autosave|recovered|conflicted copy)([ ._()-]|$)/i.test(l))return false;if(parts.some(v=>['__macosx','.git','.github','node_modules'].includes(v)))return false;return true;}
const ALL_RESOURCES = (window.SCIENCE_VAULT_RESOURCES || []).filter(isPublicResource);
let activeType = "All";
let activeTopic = "";
let activeSubtopic = "";

function norm(v){ return String(v||"").toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z0-9]+/g," ").trim(); }
function searchable(r){ return [r.title,r.year,r.course,r.strand,r.unit,r.topic,r.subtopic,r.type,r.format,r.description,r.file,...(r.keywords||[])].map(norm).join(" "); }
function termsForQuery(q){ const map={"diversity of life":["diversity of life","classification","kingdoms","animal classification","adaptations"],"classification hierarchy: kingdom to species":["classification hierarchy","kingdom to species","kingdoms","scientific naming","animal classification"],"characteristics used for classification":["characteristics used for classification","characteristics and classification of living things","classification"],"dichotomous keys":["dichotomous keys","classification keys","branched keys","tabular keys"],"developing classification keys":["developing classification keys","classification keys","branched keys","tabular keys"],"producers, consumers and decomposers":["producers consumers and decomposers","producer","consumer","decomposer","food chains","food webs"],"energy flow in ecosystems":["energy flow in ecosystems","food chains","food webs","feeding relationships"],"impacts of human activity on feeding relationships":["impacts of human activity on feeding relationships","human impacts","human activity","ecosystem impacts"]}; const nq=norm(q); return map[nq]||nq.split(/\s+/).filter(Boolean); }
function courseForPage(){return document.body.dataset.course||"";} function yearForPage(){return document.body.dataset.year||"";}
function filterValue(id){return document.getElementById(id)?.value||""}
function metadataFor(r){const labs=window.VaultUI?VaultUI.labels({path:r.file||''}):[],s=norm((r.file||'')+' '+(r.title||''));return{labels:labs,answer:!!r.answers||labs.includes('Answer / Marking Key'),rubric:labs.includes('Rubric')||/rubric|criteria sheet|marking criteria/.test(s),video:labs.includes('Video')||/\.(mp4|webm|ogv|mov|m4v)$/i.test(r.file||''),format:(r.format||((r.file||'').split('.').pop()||'')).toUpperCase()}}
function filteredResources(){const q=norm(document.getElementById("searchInput")?.value),pageCourse=courseForPage();return ALL_RESOURCES.filter(r=>{const pageYear=yearForPage(),courseOK=!pageCourse||r.course===pageCourse,yearOK=!pageYear||r.year===pageYear;const aliases={worksheet:["worksheet","worksheets"],powerpoint:["powerpoint","powerpoints"],practical:["practical","practicals"],test:["test","tests","assessments"],exam:["exam","exams","assessments"],note:["note","notes"],revision:["revision"],video:["video","videos"],"other resources":["other resources"]};const wanted=aliases[norm(activeType)]||aliases[norm(activeType).replace(/s$/,"")]||[norm(activeType)],m=metadataFor(r),typeOK=activeType==="All"||(norm(activeType)==='videos'?m.video:wanted.includes(norm(r.type))),topicOK=!activeTopic||norm(r.topic)===norm(activeTopic),subtopicOK=!activeSubtopic||termsForQuery(activeSubtopic).some(t=>searchable(r).includes(t)),qt=termsForQuery(q),qOK=!q||qt.every(t=>searchable(r).includes(t));const fy=filterValue('advancedYear'),fc=filterValue('advancedCourse'),ff=filterValue('advancedFormat'),fk=filterValue('advancedKey');const advancedOK=(!fy||String(r.year||'')===fy)&&(!fc||String(r.course||'')===fc)&&(!ff||m.format===ff)&&(!fk||(fk==='answer'&&m.answer)||(fk==='rubric'&&m.rubric)||(fk==='editable'&&m.labels.includes('Editable')));return courseOK&&yearOK&&typeOK&&topicOK&&subtopicOK&&qOK&&advancedOK;});}
function badge(t){return t?`<span class="meta-badge">${t}</span>`:"";}
function resourceDetails(r){const p=[],slides=r.slides??r.slideCount??r.slide_count,pages=r.pages??r.pageCount??r.page_count,size=r.sizeLabel??r.fileSizeLabel??r.file_size_label??r.size??r.fileSize??r.file_size;if(slides)p.push(slides+" slide"+(Number(slides)===1?"":"s"));else if(pages)p.push(pages+" page"+(Number(pages)===1?"":"s"));if(size){let s=size;if(typeof s==="number")s=s>=1048576?(s/1048576).toFixed(1)+" MB":s>=1024?(s/1024).toFixed(0)+" KB":s+" B";p.push(s);}return p.join(" • ");}
function render(){const grid=document.getElementById("resourceGrid");if(!grid)return;const data=filteredResources(),empty=document.getElementById("emptyState"),count=document.getElementById("resultCount");if(count)count.textContent=`${data.length} resource${data.length===1?"":"s"}`;if(empty)empty.classList.toggle("hidden",data.length>0);grid.innerHTML=data.map(r=>`<article class="resource-card"><div class="resource-top"><div>${badge(r.type)} ${badge(r.format)} ${r.answers?badge("Answers / Key"):""}</div><span class="resource-year">${r.year||""}</span></div><h3>${r.title}</h3><p>${r.description||""}${resourceDetails(r)?` <strong class="resource-details">${resourceDetails(r)}</strong>`:""}</p><div class="resource-path">${[r.course,r.unit,r.topic,r.subtopic].filter(Boolean).join(" › ")}</div><div class="resource-actions">${r.file?`<button class="preview-btn" data-preview="${r.file}" data-title="${r.title}">${metadataFor(r).video?'Play':'Preview'}</button><a class="download-btn" href="${encodeURI(r.file)}" download>Download</a>`:""}</div></article>`).join("");bindPreviewButtons();}
function setupFilters(){document.querySelectorAll(".filters [data-filter]").forEach(b=>b.addEventListener("click",()=>{activeType=b.dataset.filter;document.querySelectorAll(".filters [data-filter]").forEach(x=>x.classList.toggle("active",x===b));render();}));document.getElementById("searchInput")?.addEventListener("input",render);}
function setupAdvancedFilters(){const box=document.getElementById('advancedFilters');if(!box)return;const vals=(key)=>[...new Set(ALL_RESOURCES.map(r=>String(r[key]||'')).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));const fill=(id,label,a)=>{const e=document.getElementById(id);if(e)e.innerHTML='<option value="">'+label+'</option>'+a.map(v=>'<option value="'+v.replace(/"/g,'&quot;')+'">'+v+'</option>').join('')};fill('advancedYear','All years',vals('year'));fill('advancedCourse','All subjects / courses',vals('course'));fill('advancedFormat','All file formats',[...new Set(ALL_RESOURCES.map(metadataFor).map(m=>m.format).filter(Boolean))].sort());['advancedYear','advancedCourse','advancedFormat','advancedKey'].forEach(id=>document.getElementById(id)?.addEventListener('change',()=>{window.resourcePage=1;render()}));document.getElementById('clearAdvanced')?.addEventListener('click',()=>{['advancedYear','advancedCourse','advancedFormat','advancedKey'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''});const q=document.getElementById('searchInput');if(q)q.value='';activeType='All';document.querySelectorAll('.filters [data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter==='All'));window.resourcePage=1;render()})}
function setupSubtopics(){document.querySelectorAll("[data-topic]").forEach(b=>b.addEventListener("click",()=>{activeTopic=b.dataset.topic||"";activeSubtopic="";document.querySelectorAll("[data-topic],[data-subtopic]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");const q=document.getElementById("searchInput");if(q)q.value="";render();document.getElementById("resources")?.scrollIntoView({behavior:"smooth"});}));document.querySelectorAll("[data-subtopic]").forEach(b=>b.addEventListener("click",()=>{activeTopic="";activeSubtopic=b.dataset.subtopic||"";document.querySelectorAll("[data-topic],[data-subtopic]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");const q=document.getElementById("searchInput");if(q)q.value="";render();document.getElementById("resources")?.scrollIntoView({behavior:"smooth"});}));}
function setupExamSearch(){document.querySelectorAll("[data-examsearch]").forEach(b=>b.addEventListener("click",()=>{const q=document.getElementById("searchInput");if(q){q.value=b.dataset.examsearch;render();}document.getElementById("resources")?.scrollIntoView({behavior:"smooth"});}));}
let modal;function ensureModal(){if(modal)return;modal=document.createElement("div");modal.className="preview-modal hidden";modal.innerHTML=`<div class="preview-shell"><div class="preview-head"><div><small>RESOURCE PREVIEW</small><h3 id="previewTitle">Preview</h3></div><div class="preview-actions"><a id="previewDownload" class="download-btn" href="#" download>Download</a><button id="previewClose" class="preview-close">×</button></div></div><div id="previewBody" class="preview-body"></div></div>`;document.body.appendChild(modal);modal.querySelector("#previewClose").onclick=closePreview;modal.onclick=e=>{if(e.target===modal)closePreview()};document.addEventListener("keydown",e=>{if(e.key==="Escape")closePreview()});}
function previewURL(url){let u=String(url||'').trim();try{u=decodeURI(u)}catch(e){}return new URL(u,window.location.href).href}
function openPreview(url,name){if(window.VaultUI){VaultUI.preview(url,name);return}ensureModal();const absolute=previewURL(url),safe=encodeURI(absolute);modal.querySelector("#previewTitle").textContent=name||"Preview";modal.querySelector("#previewDownload").href=safe;const body=modal.querySelector("#previewBody"),pathname=new URL(absolute).pathname,ext=(pathname.split(".").pop()||"").toLowerCase();if(['mp4','webm','ogv','mov','m4v'].includes(ext))body.innerHTML=`<video controls playsinline style="width:100%;height:75vh;background:#000" src="${safe}"></video>`;else if(ext==="pdf"||ext==="txt"||ext==="md")body.innerHTML=`<iframe src="${safe}" title="Resource preview"></iframe>`;else if(["png","jpg","jpeg","gif","webp","svg"].includes(ext))body.innerHTML=`<div class="image-preview"><img src="${safe}" alt=""></div>`;else if(["doc","docx","ppt","pptx","xls","xlsx"].includes(ext)){const office="https://view.officeapps.live.com/op/embed.aspx?src="+encodeURIComponent(absolute);body.innerHTML=`<iframe src="${office}" title="Office document preview" style="width:100%;height:75vh;border:0"></iframe>`;}else body.innerHTML=`<div class="preview-message"><h3>Preview not available for this file type</h3><p>You can still download the original resource.</p></div>`;modal.classList.remove("hidden");document.body.style.overflow="hidden";}
function closePreview(){if(modal){modal.classList.add("hidden");modal.querySelector("#previewBody").innerHTML="";document.body.style.overflow="";}}function bindPreviewButtons(){document.querySelectorAll("[data-preview]").forEach(b=>b.onclick=()=>openPreview(b.dataset.preview,b.dataset.title));}
function drawLibrary(){const grid=document.getElementById("libraryGrid");if(!grid)return;const R=(window.SCIENCE_VAULT_RESOURCES||[]).filter(isPublicResource),$=id=>document.getElementById(id),keys=["year","course","unit","topic","subtopic","school","type","format"],esc=x=>String(x??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));keys.forEach(k=>{const el=$(k+"Filter");if(!el)return;const old=el.value||"All",vals=[...new Set(R.map(r=>r[k]).filter(Boolean))].sort();el.innerHTML=`<option value="All">All ${k==="unit"?"units":k+"s"}</option>`+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join("");if([...el.options].some(o=>o.value===old))el.value=old;});const q=($("librarySearch")?.value||"").toLowerCase(),rows=R.filter(r=>(!q||Object.values(r).join(" ").toLowerCase().includes(q))&&keys.every(k=>!$(k+"Filter")||$(k+"Filter").value==="All"||r[k]===$(k+"Filter").value));if($("libraryCount"))$("libraryCount").textContent=`${rows.length} resource${rows.length===1?"":"s"}`;if($("libraryEmpty"))$("libraryEmpty").classList.toggle("hidden",rows.length>0);grid.innerHTML=rows.map(r=>{const file=r.file||"";return `<article class="resource-card"><div class="resource-top"><span class="resource-type">${esc(r.type)}</span><span class="resource-format">${esc(r.format)}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.description||"")}</p><small>${esc(r.year)} · ${esc(r.course)} · ${esc(r.unit)}</small><div class="resource-actions">${r.file?`<button class="preview-btn" data-preview="${esc(file)}" data-title="${esc(r.title)}">${metadataFor(r).video?'Play':'Preview'}</button><a class="download-btn" href="${encodeURI(file)}" download>Download</a>`:""}</div></article>`}).join("");bindPreviewButtons();}
function refreshAllResources(){render();drawLibrary();}
document.addEventListener("DOMContentLoaded",()=>{setupFilters();setupAdvancedFilters();setupSubtopics();setupExamSearch();render();drawLibrary();document.getElementById("librarySearch")?.addEventListener("input",drawLibrary);["year","course","unit","topic","subtopic","school","type","format"].forEach(k=>document.getElementById(k+"Filter")?.addEventListener("change",drawLibrary));});
window.addEventListener("science-vault-resources-ready",()=>{setupAdvancedFilters();refreshAllResources()});
