
const ALL_RESOURCES = window.SCIENCE_VAULT_RESOURCES || [];
let activeType = "All";
let activeTopic = "";
let activeSubtopic = "";

function norm(v){ return String(v||"").toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z0-9]+/g," ").trim(); }
function searchable(r){ return [r.title,r.year,r.course,r.strand,r.unit,r.topic,r.subtopic,r.type,r.format,r.description,...(r.keywords||[])].map(norm).join(" "); }
function termsForQuery(q){ const map={"diversity of life":["diversity of life","classification","kingdoms","animal classification","adaptations"],"classification hierarchy: kingdom to species":["classification hierarchy","kingdom to species","kingdoms","scientific naming","animal classification"],"characteristics used for classification":["characteristics used for classification","characteristics and classification of living things","classification"],"dichotomous keys":["dichotomous keys","classification keys","branched keys","tabular keys"],"developing classification keys":["developing classification keys","classification keys","branched keys","tabular keys"],"producers, consumers and decomposers":["producers consumers and decomposers","producer","consumer","decomposer","food chains","food webs"],"energy flow in ecosystems":["energy flow in ecosystems","food chains","food webs","feeding relationships"],"impacts of human activity on feeding relationships":["impacts of human activity on feeding relationships","human impacts","human activity","ecosystem impacts"]}; const nq=norm(q); return map[nq]||nq.split(/\s+/).filter(Boolean); }
function courseForPage(){return document.body.dataset.course||"";} function yearForPage(){return document.body.dataset.year||"";}
function filteredResources(){const q=norm(document.getElementById("searchInput")?.value),pageCourse=courseForPage();return ALL_RESOURCES.filter(r=>{const pageYear=yearForPage(),courseOK=!pageCourse||r.course===pageCourse,yearOK=!pageYear||r.year===pageYear;const aliases={worksheet:["worksheet","worksheets"],powerpoint:["powerpoint","powerpoints"],practical:["practical","practicals"],test:["test","tests","assessments"],exam:["exam","exams","assessments"],note:["note","notes"],revision:["revision"],"other resources":["other resources"]};const wanted=aliases[norm(activeType)]||aliases[norm(activeType).replace(/s$/,"")]||[norm(activeType)],typeOK=activeType==="All"||wanted.includes(norm(r.type)),topicOK=!activeTopic||norm(r.topic)===norm(activeTopic),subtopicOK=!activeSubtopic||termsForQuery(activeSubtopic).some(t=>searchable(r).includes(t)),qt=termsForQuery(q),qOK=!q||qt.every(t=>searchable(r).includes(t));return courseOK&&yearOK&&typeOK&&topicOK&&subtopicOK&&qOK;});}
function badge(t){return t?`<span class="meta-badge">${t}</span>`:"";}
function resourceDetails(r){const p=[],slides=r.slides??r.slideCount??r.slide_count,pages=r.pages??r.pageCount??r.page_count,size=r.sizeLabel??r.fileSizeLabel??r.file_size_label??r.size??r.fileSize??r.file_size;if(slides)p.push(slides+" slide"+(Number(slides)===1?"":"s"));else if(pages)p.push(pages+" page"+(Number(pages)===1?"":"s"));if(size){let s=size;if(typeof s==="number")s=s>=1048576?(s/1048576).toFixed(1)+" MB":s>=1024?(s/1024).toFixed(0)+" KB":s+" B";p.push(s);}return p.join(" • ");}
function render(){const grid=document.getElementById("resourceGrid");if(!grid)return;const data=filteredResources(),empty=document.getElementById("emptyState"),count=document.getElementById("resultCount");if(count)count.textContent=`${data.length} resource${data.length===1?"":"s"}`;if(empty)empty.classList.toggle("hidden",data.length>0);grid.innerHTML=data.map(r=>`<article class="resource-card"><div class="resource-top"><div>${badge(r.type)} ${badge(r.format)} ${r.answers?badge("Answers / Key"):""}</div><span class="resource-year">${r.year||""}</span></div><h3>${r.title}</h3><p>${r.description||""}${resourceDetails(r)?` <strong class="resource-details">${resourceDetails(r)}</strong>`:""}</p><div class="resource-path">${[r.course,r.unit,r.topic,r.subtopic].filter(Boolean).join(" › ")}</div><div class="resource-actions">${r.file?`<a class="download-btn" href="${encodeURI(r.file)}" download>Download</a>`:""}</div></article>`).join("");}
function setupFilters(){document.querySelectorAll(".filters [data-filter]").forEach(b=>b.addEventListener("click",()=>{activeType=b.dataset.filter;document.querySelectorAll(".filters [data-filter]").forEach(x=>x.classList.toggle("active",x===b));render();}));document.getElementById("searchInput")?.addEventListener("input",render);}
function setupSubtopics(){document.querySelectorAll("[data-topic]").forEach(b=>b.addEventListener("click",()=>{activeTopic=b.dataset.topic||"";activeSubtopic="";document.querySelectorAll("[data-topic],[data-subtopic]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");const q=document.getElementById("searchInput");if(q)q.value="";render();document.getElementById("resources")?.scrollIntoView({behavior:"smooth"});}));document.querySelectorAll("[data-subtopic]").forEach(b=>b.addEventListener("click",()=>{activeTopic="";activeSubtopic=b.dataset.subtopic||"";document.querySelectorAll("[data-topic],[data-subtopic]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");const q=document.getElementById("searchInput");if(q)q.value="";render();document.getElementById("resources")?.scrollIntoView({behavior:"smooth"});}));}
function setupExamSearch(){document.querySelectorAll("[data-examsearch]").forEach(b=>b.addEventListener("click",()=>{const q=document.getElementById("searchInput");if(q){q.value=b.dataset.examsearch;render();}document.getElementById("resources")?.scrollIntoView({behavior:"smooth"});}));}
function drawLibrary(){const grid=document.getElementById("libraryGrid");if(!grid)return;const R=window.SCIENCE_VAULT_RESOURCES||[],$=id=>document.getElementById(id),keys=["year","course","unit","topic","subtopic","school","type","format"],esc=x=>String(x??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));keys.forEach(k=>{const el=$(k+"Filter");if(!el)return;const old=el.value||"All",vals=[...new Set(R.map(r=>r[k]).filter(Boolean))].sort();el.innerHTML=`<option value="All">All ${k==="unit"?"units":k+"s"}</option>`+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join("");if([...el.options].some(o=>o.value===old))el.value=old;});const q=($("librarySearch")?.value||"").toLowerCase(),rows=R.filter(r=>(!q||Object.values(r).join(" ").toLowerCase().includes(q))&&keys.every(k=>!$(k+"Filter")||$(k+"Filter").value==="All"||r[k]===$(k+"Filter").value));if($("libraryCount"))$("libraryCount").textContent=`${rows.length} resource${rows.length===1?"":"s"}`;if($("libraryEmpty"))$("libraryEmpty").classList.toggle("hidden",rows.length>0);grid.innerHTML=rows.map(r=>{const file=encodeURI(r.file||"");return `<article class="resource-card"><div class="resource-top"><span class="resource-type">${esc(r.type)}</span><span class="resource-format">${esc(r.format)}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.description||"")}</p><small>${esc(r.year)} · ${esc(r.course)} · ${esc(r.unit)}</small><div class="resource-actions">${r.file?`<a class="download-btn" href="${file}" download>Download</a>`:""}</div></article>`}).join("");}
function refreshAllResources(){render();drawLibrary();}
document.addEventListener("DOMContentLoaded",()=>{setupFilters();setupSubtopics();setupExamSearch();render();drawLibrary();document.getElementById("librarySearch")?.addEventListener("input",drawLibrary);["year","course","unit","topic","subtopic","school","type","format"].forEach(k=>document.getElementById(k+"Filter")?.addEventListener("change",drawLibrary));});
window.addEventListener("science-vault-resources-ready",refreshAllResources);
