window.SENIOR_COURSES={
"Science":[
{name:"Biology",pathways:["ATAR","General"]},{name:"Chemistry",pathways:["ATAR"]},{name:"Human Biology",pathways:["ATAR","General"]},{name:"Physics",pathways:["ATAR"]},{name:"Psychology",pathways:["ATAR","General"]}
],
"Mathematics":[
{name:"Mathematics Applications",pathways:["ATAR"]},{name:"Mathematics Methods",pathways:["ATAR"]},{name:"Mathematics Specialist",pathways:["ATAR"]},{name:"Mathematics Essential",pathways:["General"]}
],
"English":[
{name:"English",pathways:["ATAR","General"]},{name:"Literature",pathways:["ATAR"]},{name:"English as an Additional Language or Dialect",pathways:["ATAR","General"]}
],
"HASS":[
{name:"Aboriginal and Intercultural Studies",pathways:["ATAR","General"]},{name:"Accounting and Finance",pathways:["ATAR","General"]},{name:"Agribusiness",pathways:["General"]},{name:"Ancient History",pathways:["ATAR","General"]},{name:"Business Management and Enterprise",pathways:["ATAR","General"]},{name:"Careers and Employability",pathways:["General"]},{name:"Economics",pathways:["ATAR"]},{name:"Geography",pathways:["ATAR","General"]},{name:"Modern History",pathways:["ATAR","General"]},{name:"Politics and Law",pathways:["ATAR","General"]},{name:"Religion and Life",pathways:["ATAR","General"]}
],
"Health and Physical Education":[
{name:"Health Studies",pathways:["ATAR","General"]},{name:"Outdoor Education",pathways:["ATAR","General"]},{name:"Physical Education Studies",pathways:["ATAR","General"]}
]};
window.SENIOR_CONTENT={
"English|ATAR":{1:["Language, identity and textual representation","Purpose, context, audience and conventions","Analysis and evaluation of texts","Creating analytical, interpretive, persuasive and imaginative texts"],2:["Comparison of texts and perspectives","Stylistic and structural choices","Interpretation and critical response","Creating sustained written, oral, multimodal and digital texts"],3:["Relationships between language, genre, context and ideology","Critical analysis of representations and perspectives","Evaluation of textual conventions and language choices","Creation of analytical and imaginative texts"],4:["Intertextuality and interpretation","Critical evaluation of values, attitudes and perspectives","Synthesis of ideas across texts","Refined creation of analytical, interpretive and creative texts"]},
"English|General":{1:["Comprehending everyday, community and workplace texts","Language, audience, purpose and context","Interpreting ideas and information","Creating clear written, oral and multimodal texts"],2:["Responding to a range of texts","Language and textual conventions","Comparing ideas and viewpoints","Creating imaginative, interpretive and persuasive texts"],3:["Comprehending and evaluating texts for different contexts","Representation and point of view","Using evidence to support interpretations","Creating texts for social, community and workplace purposes"],4:["Critical literacy in everyday and public texts","Evaluating information and perspectives","Adapting language for audience and purpose","Creating sustained written, oral, multimodal and digital texts"]},
"Mathematics Applications|ATAR":{1:["Consumer arithmetic","Algebra and matrices","Shape and measurement"],2:["Univariate data analysis and the statistical investigation process","Applications of trigonometry","Linear equations and their graphs"],3:["Bivariate data analysis","Growth and decay in sequences","Graphs and networks"],4:["Time series analysis","Loans, investments and annuities","Networks and decision mathematics"]},
"Mathematics Methods|ATAR":{1:["Functions and graphs","Trigonometric functions","Counting and probability"],2:["Exponential functions","Arithmetic and geometric sequences and series","Introduction to differential calculus"],3:["Further differentiation and applications","Integrals","Discrete random variables"],4:["The logarithmic function","Continuous random variables and the normal distribution","Interval estimates for proportions"]},
"Mathematics Specialist|ATAR":{1:["Combinatorics","Vectors in the plane","Geometry"],2:["Trigonometry","Matrices","Real and complex numbers"],3:["Complex numbers","Functions and sketching graphs","Vectors in three dimensions","Rates of change and differential equations"],4:["Integral calculus","Statistical inference","Motion and vector calculus applications"]},
"Mathematics Essential|General":{1:["Basic calculations, percentages and rates","Measurement","Algebra","Graphs"],2:["Representing and comparing data","Percentages and rates","Time and motion","Networks"],3:["Measurement","Scales, plans and models","Graphs in practical situations","Data collection and interpretation"],4:["Probability and relative frequencies","Earth geometry and time zones","Loans and compound interest","Networks and decision making"]},
"Health Studies|ATAR":{1:["Dimensions and determinants of health","Health inquiry and data","Health promotion","Personal and community health"],2:["Health inequities and determinants","Health promotion frameworks","Health research and evidence","Strategies to improve health"],3:["Health status and determinants","Health inequities and population groups","Health promotion planning","Evidence-based health inquiry"],4:["Global and Australian health issues","Social justice and health","Health policy and promotion","Evaluation of health strategies"]},
"Health Studies|General":{1:["Dimensions of health","Personal health influences","Health decisions","Health promotion"],2:["Social and environmental influences on health","Community health","Health inquiry","Strategies for healthier living"],3:["Health beliefs and behaviours","Health determinants","Community health issues","Planning health promotion"],4:["Health issues and priorities","Social and environmental factors","Health promotion strategies","Evaluating health information and action"]},
"Physical Education Studies|ATAR":{1:["Functional anatomy","Biomechanics","Motor learning and coaching","Exercise physiology","Sport psychology"],2:["Movement analysis","Training principles","Skill acquisition","Psychological skills","Performance analysis"],3:["Advanced functional anatomy and biomechanics","Exercise physiology and training","Motor learning and coaching","Sport psychology and performance"],4:["Integrated performance analysis","Training program design","Biomechanical application","Psychological and tactical preparation"]},
"Physical Education Studies|General":{1:["Developing physical skills","Functional anatomy and movement","Training basics","Teamwork and leadership"],2:["Movement concepts","Fitness and training","Skill learning","Participation and performance"],3:["Performance improvement","Training principles","Movement analysis","Leadership and coaching"],4:["Planning for performance","Fitness development","Tactical and psychological factors","Evaluation of participation and performance"]},
"Outdoor Education|ATAR":{1:["Outdoor practical skills","Planning and risk management","Environment and sustainability","Leadership and group dynamics"],2:["Expedition planning","Navigation and outdoor skills","Human-nature relationships","Leadership and decision making"],3:["Advanced outdoor skills","Risk management and emergency response","Environmental interpretation","Leadership and facilitation"],4:["Expedition management","Sustainability and minimal-impact practices","Group dynamics and leadership","Evaluation of outdoor experiences"]},
"Outdoor Education|General":{1:["Outdoor activity skills","Planning and safety","Environmental awareness","Working with others"],2:["Outdoor journeys","Navigation","Risk awareness","Leadership and teamwork"],3:["Planning outdoor experiences","Practical skills and safety","Environmental responsibility","Leadership"],4:["Extended outdoor experiences","Risk management","Sustainable practices","Group management and reflection"]}
};