window.SENIOR_COURSES={
"Science":[
{name:"Biology",pathways:["ATAR"]},{name:"Chemistry",pathways:["ATAR","General"]},{name:"Earth and Environmental Science",pathways:["ATAR","General"]},{name:"Human Biology",pathways:["ATAR","General"]},{name:"Integrated Science",pathways:["General"]},{name:"Physics",pathways:["ATAR"]},{name:"Psychology",pathways:["ATAR","General"]},{name:"Science in Practice",pathways:["General"]}
],
"Mathematics":[{name:"Mathematics Applications",pathways:["ATAR"]},{name:"Mathematics Methods",pathways:["ATAR"]},{name:"Mathematics Specialist",pathways:["ATAR"]},{name:"Mathematics Essential",pathways:["General"]}],
"English":[{name:"English",pathways:["ATAR","General"]},{name:"Literature",pathways:["ATAR"]},{name:"English as an Additional Language or Dialect",pathways:["ATAR","General"]}],
"HASS":[{name:"Aboriginal and Intercultural Studies",pathways:["ATAR","General"]},{name:"Accounting and Finance",pathways:["ATAR","General"]},{name:"Agribusiness",pathways:["General"]},{name:"Ancient History",pathways:["ATAR","General"]},{name:"Business Management and Enterprise",pathways:["ATAR","General"]},{name:"Careers and Employability",pathways:["General"]},{name:"Economics",pathways:["ATAR"]},{name:"Geography",pathways:["ATAR","General"]},{name:"Modern History",pathways:["ATAR","General"]},{name:"Politics and Law",pathways:["ATAR","General"]},{name:"Religion and Life",pathways:["ATAR","General"]}],
"Health and Physical Education":[{name:"Health Studies",pathways:["ATAR","General"]},{name:"Outdoor Education",pathways:["ATAR","General"]},{name:"Physical Education Studies",pathways:["ATAR","General"]}]
};
window.SENIOR_CONTENT={
"Biology|ATAR":{1:["Ecosystems and biodiversity","Classification and biological diversity","Ecosystem interactions and energy flow","Science inquiry and field investigation"],2:["From single cells to multicellular organisms","Cell structure and function","Exchange and transport systems","Science inquiry and biological investigation"],3:["Continuity of species","DNA, genes and inheritance","Reproduction and population genetics","Evolutionary processes"],4:["Surviving in a changing environment","Homeostasis and disease","Population change and environmental pressures","Biological responses and applications"]},
"Chemistry|ATAR":{1:["Chemical fundamentals: structure, properties and reactions","Atomic structure and periodicity","Chemical bonding and materials","Stoichiometry and chemical reactions"],2:["Molecular interactions and reactions","Intermolecular forces and properties","Aqueous chemistry and reactions","Energy changes and reaction processes"],3:["Equilibrium, acids and bases, and redox reactions","Chemical equilibrium","Acids, bases and buffers","Oxidation-reduction and electrochemistry"],4:["Organic chemistry and chemical synthesis","Structure and reactions of organic compounds","Chemical synthesis and analysis","Applications of chemistry"]},
"Chemistry|General":{1:["Chemistry in everyday materials","Atoms, elements and compounds","Chemical language and reactions","Properties and uses of materials"],2:["Chemistry and the environment","Solutions and reactions","Acids and bases","Chemical processes and sustainability"],3:["Materials and chemical processes","Organic materials and fuels","Rates and energy in reactions","Chemistry in industry and society"],4:["Chemistry for a sustainable future","Polymers and useful products","Environmental chemistry","Evaluating chemical technologies"]},
"Earth and Environmental Science|ATAR":{1:["Earth systems and resources","Earth materials and geological processes","Earth resources","Earth and environmental inquiry"],2:["Earth processes and hazards","Plate tectonics","Geological hazards","Monitoring and managing Earth processes"],3:["Earth systems and environmental change","Interactions among Earth systems","Climate and environmental records","Human impacts and environmental change"],4:["Managing Earth resources and environments","Resource management","Environmental sustainability","Evidence-based environmental decision making"]},
"Earth and Environmental Science|General":{1:["Earth materials and landscapes","Earth resources","Geological processes","Earth science investigations"],2:["Earth hazards and environments","Natural hazards","Environmental monitoring","Human responses to Earth processes"],3:["Earth systems and change","Climate and environmental change","Human impacts","Environmental investigation"],4:["Sustainable use of Earth resources","Resource use","Environmental management","Sustainability and community decisions"]},
"Human Biology|ATAR":{1:["The functioning human body","Cells and tissues","Metabolism and body systems","Science inquiry in human biology"],2:["Reproduction and inheritance","Human reproduction","DNA, genes and inheritance","Human variation"],3:["Homeostasis and disease","Coordination and regulation","Immune responses and disease","Human biology investigations"],4:["Human variation and evolution","Population genetics","Human evolution","Applications of human biological knowledge"]},
"Human Biology|General":{1:["Healthy body systems","Cells, tissues and body organisation","Body systems and maintaining life","Lifestyle and health"],2:["Reproduction and development","Human reproduction","Growth and development","Personal health decisions"],3:["Maintaining a healthy body","Coordination and regulation","Disease and defence","Health choices"],4:["Human variation and community health","Inheritance and variation","Population health","Evaluating health information"]},
"Integrated Science|General":{1:["Science inquiry and practical investigation","Matter and energy in everyday contexts","Living systems","Science applications"],2:["Earth and environmental systems","Forces, energy and technologies","Scientific evidence","Science in society"],3:["Integrated scientific investigations","Biological and chemical applications","Earth and physical science applications","Evaluating scientific information"],4:["Science, technology and community","Sustainability","Applied investigations","Communicating scientific evidence"]},
"Physics|ATAR":{1:["Thermal, nuclear and electrical physics","Heating processes and thermal physics","Nuclear reactions and radiation","Electrical circuits"],2:["Linear motion and waves","Motion and forces","Mechanical energy and momentum","Waves and wave behaviour"],3:["Gravity and electromagnetism","Motion in gravitational fields","Electric and magnetic fields","Electromagnetic induction"],4:["Revolutions in modern physics","Special relativity","Quantum physics","Wave-particle duality and cosmology"]},
"Psychology|ATAR":{1:["Introduction to psychology and scientific inquiry","Biological influences on behaviour","Cognition and development","Psychological research methods"],2:["Individuals and social behaviour","Personality and individual differences","Social influence","Psychological investigation"],3:["Mind, brain and behaviour","Memory and cognition","Development and behaviour","Research and ethical practice"],4:["Psychology in society","Attitudes and social influence","Personality and behaviour","Applying and evaluating psychological evidence"]},
"Psychology|General":{1:["Introduction to psychology","Behaviour and biological influences","Psychological inquiry","Individuals and everyday behaviour"],2:["People in groups","Social influence","Communication and relationships","Psychological investigation"],3:["Cognition and behaviour","Memory and learning","Development","Applying psychological knowledge"],4:["Psychology and community","Social behaviour","Wellbeing and relationships","Evaluating psychological information"]},
"Science in Practice|General":{1:["Practical science skills","Planning and conducting investigations","Measurement and data","Science applications"],2:["Science in everyday contexts","Experimental design","Evidence and communication","Science and technology"],3:["Applied scientific investigations","Data analysis","Workplace and community science","Evaluating evidence"],4:["Science projects and applications","Problem solving","Sustainability and technology","Communicating scientific findings"]},
"English|ATAR":{1:["Language, identity and textual representation","Purpose, context, audience and conventions","Analysis and evaluation of texts","Creating analytical, interpretive, persuasive and imaginative texts"],2:["Comparison of texts and perspectives","Stylistic and structural choices","Interpretation and critical response","Creating sustained written, oral, multimodal and digital texts"],3:["Relationships between language, genre, context and ideology","Critical analysis of representations and perspectives","Evaluation of textual conventions and language choices","Creation of analytical and imaginative texts"],4:["Intertextuality and interpretation","Critical evaluation of values, attitudes and perspectives","Synthesis of ideas across texts","Refined creation of analytical, interpretive and creative texts"]},
"English|General":{1:["Comprehending everyday, community and workplace texts","Language, audience, purpose and context","Interpreting ideas and information","Creating clear written, oral and multimodal texts"],2:["Responding to a range of texts","Language and textual conventions","Comparing ideas and viewpoints","Creating imaginative, interpretive and persuasive texts"],3:["Comprehending and evaluating texts for different contexts","Representation and point of view","Using evidence to support interpretations","Creating texts for social, community and workplace purposes"],4:["Critical literacy in everyday and public texts","Evaluating information and perspectives","Adapting language for audience and purpose","Creating sustained written, oral, multimodal and digital texts"]},
"Mathematics Applications|ATAR":{1:["Consumer arithmetic","Algebra and matrices","Shape and measurement"],2:["Univariate data analysis and the statistical investigation process","Applications of trigonometry","Linear equations and their graphs"],3:["Bivariate data analysis","Growth and decay in sequences","Graphs and networks"],4:["Time series analysis","Loans, investments and annuities","Networks and decision mathematics"]},
"Mathematics Methods|ATAR":{1:["Functions and graphs","Trigonometric functions","Counting and probability"],2:["Exponential functions","Arithmetic and geometric sequences and series","Introduction to differential calculus"],3:["Further differentiation and applications","Integrals","Discrete random variables"],4:["The logarithmic function","Continuous random variables and the normal distribution","Interval estimates for proportions"]},
"Mathematics Specialist|ATAR":{1:["Combinatorics","Vectors in the plane","Geometry"],2:["Trigonometry","Matrices","Real and complex numbers"],3:["Complex numbers","Functions and sketching graphs","Vectors in three dimensions","Rates of change and differential equations"],4:["Integral calculus","Statistical inference","Motion and vector calculus applications"]},
"Mathematics Essential|General":{1:["Basic calculations, percentages and rates","Measurement","Algebra","Graphs"],2:["Representing and comparing data","Percentages and rates","Time and motion","Networks"],3:["Measurement","Scales, plans and models","Graphs in practical situations","Data collection and interpretation"],4:["Probability and relative frequencies","Earth geometry and time zones","Loans and compound interest","Networks and decision making"]},
"Economics|ATAR":{1:["Microeconomics","Markets and allocation","Demand, supply and market efficiency","Government intervention"],2:["Macroeconomics","Economic growth, inflation and unemployment","Aggregate economic activity","Government policy"],3:["Australia and the global economy","International trade and globalisation","Balance of payments and exchange rates","Economic policy"],4:["Economic policies and management","Macroeconomic objectives","Fiscal and monetary policy","Structural change and contemporary economic issues"]},
"Geography|ATAR":{1:["Natural and ecological hazards","Hazard processes","Risk, vulnerability and resilience","Hazard management"],2:["Global networks and interconnections","Globalisation and spatial interactions","Networks, flows and places","Geographical inquiry"],3:["Global environmental change","Environmental processes and change","Human impacts and sustainability","Geographical investigation"],4:["Planning sustainable places","Urban and regional change","Planning strategies","Sustainable futures"]},
"Geography|General":{1:["Geography of environments","Natural environments and human use","Geographical skills","Environmental management"],2:["People and places","Population and settlement","Connections between places","Geographical inquiry"],3:["Environmental change","Human-environment interactions","Sustainability","Fieldwork and investigation"],4:["Planning places","Urban and regional issues","Community planning","Evaluating geographical information"]},
"Modern History|ATAR":{1:["Understanding the modern world","Historical concepts and evidence","Significant developments and movements","Historical inquiry"],2:["Movements for change in the twentieth century","Ideas, people and movements","Causes and consequences of change","Historical interpretations"],3:["Modern nations in the twentieth century","Political, social and economic change","Evidence and perspectives","Historical argument"],4:["The modern world since 1945","International developments and conflict","Change and continuity","Historical interpretations and evidence"]},
"Modern History|General":{1:["People, place and time","Historical evidence","Change and continuity","Historical inquiry"],2:["Power and people","Movements and events","Perspectives and interpretations","Communicating history"],3:["Societies and change","Significant events and developments","Historical sources","Historical investigation"],4:["The changing modern world","People and events","Cause and consequence","Evaluating historical accounts"]},
"Politics and Law|ATAR":{1:["Democracy and the rule of law","Political and legal systems","Representation and participation","Political and legal inquiry"],2:["Representation and justice","Parliament and executive government","Courts and legal processes","Rights and accountability"],3:["Political and legal power","Australian political institutions","Law-making and judicial processes","Accountability and rights"],4:["Australian political and legal system","Constitutional change","Rights and governance","Contemporary political and legal issues"]},
"Politics and Law|General":{1:["Citizenship and government","Democratic participation","Law and society","Political and legal inquiry"],2:["Representation and law","Parliament and government","Courts and justice","Rights and responsibilities"],3:["Government and law in Australia","Political participation","Law-making","Accountability"],4:["Contemporary politics and law","Rights and freedoms","Political and legal change","Evaluating issues"]},
"Health Studies|ATAR":{1:["Dimensions and determinants of health","Health inquiry and data","Health promotion","Personal and community health"],2:["Health inequities and determinants","Health promotion frameworks","Health research and evidence","Strategies to improve health"],3:["Health status and determinants","Health inequities and population groups","Health promotion planning","Evidence-based health inquiry"],4:["Global and Australian health issues","Social justice and health","Health policy and promotion","Evaluation of health strategies"]},
"Health Studies|General":{1:["Dimensions of health","Personal health influences","Health decisions","Health promotion"],2:["Social and environmental influences on health","Community health","Health inquiry","Strategies for healthier living"],3:["Health beliefs and behaviours","Health determinants","Community health issues","Planning health promotion"],4:["Health issues and priorities","Social and environmental factors","Health promotion strategies","Evaluating health information and action"]},
"Physical Education Studies|ATAR":{1:["Functional anatomy","Biomechanics","Motor learning and coaching","Exercise physiology","Sport psychology"],2:["Movement analysis","Training principles","Skill acquisition","Psychological skills","Performance analysis"],3:["Advanced functional anatomy and biomechanics","Exercise physiology and training","Motor learning and coaching","Sport psychology and performance"],4:["Integrated performance analysis","Training program design","Biomechanical application","Psychological and tactical preparation"]},
"Physical Education Studies|General":{1:["Developing physical skills","Functional anatomy and movement","Training basics","Teamwork and leadership"],2:["Movement concepts","Fitness and training","Skill learning","Participation and performance"],3:["Performance improvement","Training principles","Movement analysis","Leadership and coaching"],4:["Planning for performance","Fitness development","Tactical and psychological factors","Evaluation of participation and performance"]},
"Outdoor Education|ATAR":{1:["Outdoor practical skills","Planning and risk management","Environment and sustainability","Leadership and group dynamics"],2:["Expedition planning","Navigation and outdoor skills","Human-nature relationships","Leadership and decision making"],3:["Advanced outdoor skills","Risk management and emergency response","Environmental interpretation","Leadership and facilitation"],4:["Expedition management","Sustainability and minimal-impact practices","Group dynamics and leadership","Evaluation of outdoor experiences"]},
"Outdoor Education|General":{1:["Outdoor activity skills","Planning and safety","Environmental awareness","Working with others"],2:["Outdoor journeys","Navigation","Risk awareness","Leadership and teamwork"],3:["Planning outdoor experiences","Practical skills and safety","Environmental responsibility","Leadership"],4:["Extended outdoor experiences","Risk management","Sustainable practices","Group management and reflection"]}
};