const R=window.SCIENCE_VAULT_RESOURCES||[];
const CURRICULUM={
"Year 7":[
["Biological Sciences","Classification and diversity of life","Classification helps organise living things from kingdom to species; classification tools including dichotomous keys can be used to classify organisms.",["classification","classifying","dichotomous","taxonomy","kingdom","species","diversity"]],
["Biological Sciences","Food chains, food webs and human impacts","Food chains and food webs represent energy flow in ecosystems and can be used to predict possible impacts of human activity.",["food chain","food web","ecosystem","producer","consumer","decomposer","feeding relationship","energy flow"]],
["Chemical Sciences","Particle model and states of matter","Particle models describe solids, liquids and gases and changes of state.",["states of matter","state of matter","particle model","solid","liquid","gas","melting","freezing","boiling","evaporation","condensation","sublimation"]],
["Chemical Sciences","Mixtures and separation","Mixtures can be separated using differences in physical properties and appropriate separation techniques.",["mixture","separation","filtration","distillation","chromatography","decantation","sieving","magnetic separation","solution","solute","solvent"]],
["Earth and Space Sciences","Space and the Solar System","Celestial objects include planets, stars, moons, asteroids, meteors, comets, constellations and galaxies.",["solar system","planet","asteroid","meteoroid","meteor","comet","constellation","celestial object"]],
["Earth and Space Sciences","Earth, Sun and Moon phenomena","Relative positions of Earth, the Sun and Moon explain lunar phases, eclipses, seasons and tides.",["lunar","moon phase","phases of the moon","eclipse","season","tide","earth sun moon"]],
["Physical Sciences","Forces and motion","Forces can change motion; balanced and unbalanced forces and contact and non-contact forces can be investigated.",["force","motion","balanced force","unbalanced force","friction","gravity","gravitational","magnetic force","electrostatic","newton","contact force","non contact"]],
["Physical Sciences","Simple machines","Simple machines can change the size, direction or distance over which forces act.",["simple machine","mechanical advantage","lever","inclined plane","wheel and axle","pulley","gear","wedge","screw"]]
],
"Year 8":[
["Biological Sciences","Cells and specialised structures","Cells are the basic units of living things and contain structures and organelles with specialised functions.",["cell","cells","organelle","microscope","cell membrane","cytoplasm","nucleus","mitochondria","chloroplast","vacuole","specialised cell"]],
["Biological Sciences","Plant and vertebrate systems","Flowering plant and vertebrate systems carry out specialised functions including gas exchange, transport and reproduction.",["body system","organ system","digestive","respiratory","circulatory","excretory","reproductive","gas exchange","flowering plant","vertebrate","heart","lung","blood"]],
["Chemical Sciences","Elements, compounds and mixtures","Matter can be represented and classified using elements, compounds and mixtures.",["element","compound","mixture","atom","periodic table","pure substance"]],
["Chemical Sciences","Chemical and physical change","Physical and chemical changes can be distinguished using observations and evidence.",["chemical change","physical change","chemical reaction","reactant","product","combustion","rusting"]],
["Earth and Space Sciences","Plate tectonics","Plate tectonics explains global patterns of geological activity and plate-boundary features.",["plate tectonic","tectonic plate","continental drift","divergent","convergent","transform boundary","earthquake","volcano"]],
["Earth and Space Sciences","Rocks and the rock cycle","Rocks contain minerals and form through processes in the rock cycle.",["rock cycle","igneous","sedimentary","metamorphic","mineral","rocks"]],
["Physical Sciences","Energy","Energy occurs in different forms and can be transferred and transformed.",["energy","kinetic","potential","thermal","heat","energy transfer","energy transformation"]]
],
"Year 9":[
["Biological Sciences","Adaptations","Plants and animals have structural, behavioural and physiological adaptations that enable survival.",["adaptation","structural adaptation","behavioural adaptation","behavioral adaptation","physiological adaptation"]],
["Biological Sciences","Responses to environmental change","Organisms have mechanisms for responding to environmental changes including temperature and stimuli.",["environmental change","endotherm","ectotherm","tropism","phototropism","geotropism","stimulus","homeostasis"]],
["Chemical Sciences","Atomic structure and reactions","Atomic structure and rearrangement of matter underpin chemical reactions.",["atomic structure","proton","neutron","electron","chemical equation","conservation of mass","rearrangement"]],
["Earth and Space Sciences","Global systems and climate change","Global systems include interactions between the biosphere, lithosphere, hydrosphere and atmosphere; carbon and water cycles and changes to global systems explain climate patterns.",["global system","global systems","climate change","global climate","carbon cycle","water cycle","biosphere","lithosphere","hydrosphere","atmosphere","greenhouse","greenhouse effect","freshwater","desalination"]],
["Physical Sciences","Electricity and energy transfer","Electrical systems transfer energy and can be investigated using current, voltage, resistance and circuit models.",["electricity","electric circuit","circuit","current","voltage","resistance","ohm","series circuit","parallel circuit"]],
["Physical Sciences","Light and sound","Wave models explain the behaviour and transfer of light and sound energy.",["light","sound","wave","reflection","refraction","frequency","wavelength","amplitude"]]
],
"Year 10":[
["Biological Sciences","DNA, chromosomes, mitosis and meiosis","Mitosis and meiosis produce new cells; chromosomes contain genes composed of DNA.",["dna","chromosome","gene","mitosis","meiosis","cell division","gamete"]],
["Biological Sciences","Patterns of inheritance","Monohybrid inheritance can be predicted using pedigrees and Punnett squares.",["inheritance","punnett","pedigree","dominant","recessive","sex linked","allele","genotype","phenotype"]],
["Chemical Sciences","Chemical reactions","Reaction types, rates and energy changes can be investigated using particle and collision ideas.",["reaction rate","rates of reaction","collision theory","activation energy","precipitation","acid base","acid and base","chemical reaction","exothermic","endothermic","catalyst"]],
["Earth and Space Sciences","Universe and stellar processes","Stars, galaxies and solar systems have formed since the Big Bang; stars have life cycles determined by mass and space exploration contributes to scientific knowledge.",["universe","stellar","galaxy","big bang","life cycle of stars","life cycle of a star","star formation","red giant","supernova","black hole","space exploration","nebular"]],
["Physical Sciences","Motion and energy","Motion can be described quantitatively and explained through forces and energy.",["motion","velocity","acceleration","newton law","kinetic energy","potential energy","momentum","distance time","speed"]]
]};
const ATAR=[["Physics","Year 11–12 ATAR Physics","Browse resources by year, unit and syllabus topic."],["Chemistry","Year 11–12 ATAR Chemistry","Browse resources by year, unit and syllabus topic."],["Human Biology","Year 11–12 ATAR Human Biology","Browse resources by year, unit and syllabus topic."],["Biology","Year 11–12 ATAR Biology","Browse resources by year, unit and syllabus topic."],["Psychology","Year 11–12 ATAR Psychology","Browse resources by year, unit and syllabus topic."]];
let active="Year 7";const norm=s=>String(s||"").toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z0-9]+/g," ").trim();
const hay=r=>norm([r.title,r.description,...(r.keywords||[])].join(" "));
function score(r,p){const h=` ${hay(r)} `;let total=0;for(const key of p[3]){const k=norm(key);if(!k)continue;if(h.includes(` ${k} `)||h.includes(k))total+=k.includes(' ')?6:2}const oldStrand=norm(r.strand),newStrand=norm(p[0]);if(oldStrand&&oldStrand===newStrand)total+=1;return total}
function originalFileName(r){const source=String(r.file||r.title||"");try{return decodeURIComponent(source.split("/").pop()||r.title||"Resource file")}catch(e){return source.split("/").pop()||r.title||"Resource file"}}
function shortTitle(r){let s=originalFileName(r).replace(/\.(pptx?|docx?|pdf|xlsx?|csv)$/i,"").replace(/[_]+/g," ").replace(/[–—-]+/g," ");s=s.replace(/\b(copy|final|updated?|new|version|ver|draft)\b/gi," ").replace(/\b(v\s*\d+(?:\.\d+)*)\b/gi," ").replace(/\b(year|yr|y)\s*(7|8|9|10|11|12)\b/gi," ").replace(/^\s*(7|8|9|10|11|12)\s+/i,"").replace(/\b(lesson|week|term)\s*\d+[a-z]?\b/gi," ").replace(/\b(pptx?|powerpoint|document|docx?|pdf)\b/gi," ").replace(/\(\s*\d+\s*\)/g," ").replace(/\s+/g," ").trim();if(!s||s.length<3)s=r.topic||r.subtopic||r.type||"Science Resource";return s.replace(/\b\w/g,m=>m.toUpperCase())}
function card(r,year,strand){const fileName=originalFileName(r);return `<article class="syllabus-resource"><div><b>${shortTitle(r)}</b><small>${[r.type,year,strand].filter(Boolean).join(" • ")}</small><small><strong>Original file:</strong> ${fileName}</small></div><div class="resource-actions">${r.file?`<a class="download-btn" href="${encodeURI(r.file)}" download>Download</a>`:""}</div></article>`}
function grouped(rows,year,strand){const order=['PowerPoints','Worksheets','Practicals','Notes','Revision','Tests','Other Resources'];const groups={};rows.forEach(r=>{const k=r.type||"Other Resources";(groups[k]??=[]).push(r)});return Object.entries(groups).sort((a,b)=>{const ai=order.indexOf(a[0]),bi=order.indexOf(b[0]);return (ai<0?99:ai)-(bi<0?99:bi)||a[0].localeCompare(b[0])}).map(([type,items])=>`<details class="resource-type-group"><summary><b>${type}</b><span>${items.length}</span></summary><div class="compact-resource-list">${items.map(r=>card(r,year,strand)).join("")}</div></details>`).join("")}
function dot(x,rows,year){return `<section class="dotpoint-card"><div class="dotpoint-head"><span class="strand-badge">${x[0]}</span><div><h2>${x[1]}</h2><p>${x[2]}</p></div><span class="dot-count">${rows.length} resources</span></div>${rows.length?grouped(rows,year,x[0]):'<p class="empty-dot">No matching resources currently indexed.</p>'}</section>`}
function classifyAll(q){const buckets={};Object.keys(CURRICULUM).forEach(y=>buckets[y]=CURRICULUM[y].map(()=>[]));R.filter(r=>r.course==='Science'||!r.course).forEach(r=>{let best=null,bestScore=0;for(const [year,points] of Object.entries(CURRICULUM)){points.forEach((p,i)=>{const s=score(r,p);if(s>bestScore){bestScore=s;best={year,i}}})}if(best&&bestScore>=2){const p=CURRICULUM[best.year][best.i];if(!q||hay(r).includes(q)||norm(p[0]+' '+p[1]+' '+p[2]).includes(q))buckets[best.year][best.i].push(r)}});return buckets}
function render(){const host=document.getElementById("syllabusContent"),q=norm(document.getElementById("syllabusSearch").value);if(active==="ATAR"){host.innerHTML='<div class="syllabus-list">'+ATAR.map(x=>{const rows=R.filter(r=>norm(r.course)===norm(x[0])&&(!q||hay(r).includes(q)));return dot(["ATAR",x[1],x[2],[]],rows,'ATAR')}).join('')+'</div>';return}const buckets=classifyAll(q),points=CURRICULUM[active]||[];host.innerHTML='<div class="syllabus-list">'+points.map((x,i)=>dot(x,buckets[active][i],active)).join('')+'</div>'}
document.querySelectorAll('[data-syl-year]').forEach(b=>b.onclick=()=>{active=b.dataset.sylYear;document.querySelectorAll('[data-syl-year]').forEach(x=>x.classList.toggle('active',x===b));render()});document.getElementById('syllabusSearch').addEventListener('input',render);window.addEventListener('science-vault-resources-ready',render);render();