const R=window.SCIENCE_VAULT_RESOURCES||[];
const CURRICULUM={
"Year 7":[
["Biological sciences","Classification and diversity of life","Classification helps organise living things from kingdom to species; classification tools such as dichotomous keys are used to classify organisms.",["classification","classifying","dichotomous","taxonomy","kingdom","species","diversity"]],
["Biological sciences","Food chains, food webs and human impacts","Food chains and food webs represent energy flow in ecosystems and can be used to predict possible impacts of human activity.",["food chain","food web","ecosystem","producer","consumer","decomposer","feeding relationship","energy flow","human impact"]],
["Chemical sciences","Particle model and states of matter","The particle model is used to describe solids, liquids and gases and changes associated with adding or removing energy.",["states of matter","state of matter","particle model","particles","solid","liquid","gas","melting","freezing","boiling","evaporation","condensation","sublimation"]],
["Chemical sciences","Mixtures and separation","Mixtures contain substances that can be separated using differences in physical properties and appropriate separation techniques.",["mixture","separation","filtration","distillation","chromatography","decantation","sieving","magnetic separation","solution","solute","solvent","dissolve"]],
["Earth and space sciences","Space and the Solar System","Objects in space include planets, stars, moons, asteroids, meteoroids, comets, constellations and galaxies; planets have different features.",["solar system","planet","star","moon","asteroid","meteoroid","meteor","comet","constellation","galaxy","space"]],
["Earth and space sciences","Earth, Sun and Moon phenomena","Relative positions and motions of Earth, the Sun and Moon explain observable phenomena including lunar phases, eclipses, seasons and tides.",["lunar","moon phase","phases of the moon","eclipse","season","tide","earth sun moon","day night"]],
["Physical sciences","Forces and motion","Forces can change motion; balanced and unbalanced forces and contact and non-contact forces can be investigated and measured.",["force","motion","balanced force","unbalanced force","friction","gravity","gravitational","magnetic force","electrostatic","newton","contact force","non contact"]],
["Physical sciences","Simple machines","Simple machines change the size, direction or distance over which forces act and can provide mechanical advantage.",["simple machine","mechanical advantage","lever","inclined plane","wheel and axle","pulley","gear","wedge","screw","force advantage","distance advantage","speed advantage"]],
["Science inquiry","Science inquiry skills","Questioning, predicting, planning, conducting, processing, analysing, evaluating and communicating are used in scientific investigations.",["science inquiry","investigation","variables","independent variable","dependent variable","controlled variable","risk assessment","graph","data table","error","conclusion","prediction","hypothesis"]]
],
"Year 8":[
["Biological sciences","Cells and specialised structures","Cells are the basic units of living things; plant and animal cells contain structures and organelles with specialised functions.",["cell","cells","organelle","microscope","cell membrane","cytoplasm","nucleus","mitochondria","chloroplast","vacuole","specialised cell","specialized cell"]],
["Biological sciences","Plant and vertebrate systems","Flowering plant and vertebrate systems carry out specialised functions including gas exchange, transport and reproduction.",["body system","organ system","digestive","respiratory","circulatory","excretory","reproductive","gas exchange","transport","flower","flowering plant","vertebrate","heart","lung","blood"]],
["Chemical sciences","Elements, compounds and mixtures","Matter can be classified and represented using particle models, elements, compounds and mixtures.",["element","compound","mixture","atom","particle","periodic table","pure substance"]],
["Chemical sciences","Chemical and physical change","Physical and chemical changes can be distinguished using observations and evidence.",["chemical change","physical change","chemical reaction","reaction","reactant","product","combustion","rusting"]],
["Earth and space sciences","Rocks and geological processes","Rocks and geological processes can be explained through cycles and changes in Earth materials.",["rock","rock cycle","igneous","sedimentary","metamorphic","geology","mineral","weathering","erosion"]],
["Physical sciences","Energy","Energy appears in different forms and can be transferred and transformed in systems.",["energy","kinetic","potential","thermal","heat","light energy","sound energy","electrical energy","energy transfer","energy transformation"]],
["Science inquiry","Science inquiry skills","Plan, conduct, process, analyse, evaluate and communicate reproducible scientific investigations.",["science inquiry","investigation","variables","graph","data","error","conclusion","reliability","validity","hypothesis"]]
],
"Year 9":[
["Biological sciences","Adaptations","Plants and animals have structural, behavioural and physiological adaptations that enable survival in their environments.",["adaptation","structural adaptation","behavioural adaptation","behavioral adaptation","physiological adaptation","survival"]],
["Biological sciences","Responses to environmental change","Organisms respond to environmental change; endotherms, ectotherms and plant tropisms illustrate different responses.",["environmental change","response","endotherm","ectotherm","tropism","phototropism","geotropism","stimulus","homeostasis"]],
["Chemical sciences","Atomic structure and reactions","Atomic structure and rearrangement of matter underpin chemical reactions and observable changes.",["atomic structure","atom","proton","neutron","electron","chemical reaction","chemical equation","conservation of mass","rearrangement"]],
["Earth and space sciences","Earth systems","Interactions within and between Earth systems explain geological and environmental phenomena.",["earth system","geosphere","atmosphere","hydrosphere","biosphere","carbon cycle","water cycle","plate tectonic","tectonic","global system"]],
["Physical sciences","Electricity and energy transfer","Electrical systems transfer energy and can be investigated using current, voltage, resistance and circuit models.",["electricity","electric circuit","circuit","current","voltage","resistance","ohm","series circuit","parallel circuit","electrical energy"]],
["Physical sciences","Light and sound","Wave models explain the behaviour and transfer of light and sound energy.",["light","sound","wave","reflection","refraction","frequency","wavelength","amplitude","electromagnetic"]],
["Science inquiry","Science inquiry skills","Design and evaluate investigations, analyse patterns and uncertainty, and communicate evidence-based conclusions.",["science inquiry","investigation","uncertainty","data","evidence","evaluation","reliability","validity","variables"]]
],
"Year 10":[
["Biological sciences","DNA, chromosomes, mitosis and meiosis","Cell division produces cells with chromosome numbers suited to their roles; chromosomes contain genes composed of DNA.",["dna","chromosome","gene","mitosis","meiosis","cell division","gamete"]],
["Biological sciences","Patterns of inheritance","Monohybrid inheritance, including autosomal dominant/recessive and sex-linked recessive inheritance, can be predicted using pedigrees and Punnett squares.",["inheritance","punnett","pedigree","dominant","recessive","sex linked","allele","genotype","phenotype"]],
["Chemical sciences","Chemical reactions","Reaction types, rates and energy changes are investigated using particle and collision ideas.",["reaction rate","rates of reaction","collision theory","activation energy","precipitation","acid base","acid and base","chemical reaction","exothermic","endothermic","catalyst"]],
["Earth and space sciences","Universe and stellar processes","Evidence and models are used to explain stars, galaxies and the evolution of the universe.",["universe","stellar","galaxy","big bang","life cycle of stars","life cycle of a star","star formation","red giant","supernova","black hole"]],
["Physical sciences","Motion and energy","Motion can be described quantitatively and explained through forces, energy and system interactions.",["motion","velocity","acceleration","force","newton law","kinetic energy","potential energy","momentum","distance time","speed"]],
["Science inquiry","Science inquiry skills","Plan and evaluate investigations, process quantitative data and justify conclusions using scientific evidence.",["science inquiry","investigation","validity","reliability","precision","data","conclusion","uncertainty","variables"]]
]};
const ATAR=[["Physics","Year 11–12 ATAR Physics","Browse resources by year, unit and syllabus topic."],["Chemistry","Year 11–12 ATAR Chemistry","Browse resources by year, unit and syllabus topic."],["Human Biology","Year 11–12 ATAR Human Biology","Browse resources by year, unit and syllabus topic."],["Biology","Year 11–12 ATAR Biology","Browse resources by year, unit and syllabus topic."],["Psychology","Year 11–12 ATAR Psychology","Browse resources by year, unit and syllabus topic."]];
let active="Year 7";const norm=s=>String(s||"").toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z0-9]+/g," ").trim();
const hay=r=>norm([r.title,r.topic,r.subtopic,r.description,...(r.keywords||[])].join(" "));
function strandOK(r,strand){const a=norm(r.strand),b=norm(strand);if(b==="science inquiry")return a.includes("inquiry");return a===b}
function score(r,keys){const h=` ${hay(r)} `;let total=0;for(const key of keys){const k=norm(key);if(!k)continue;if(h.includes(` ${k} `)||h.includes(k))total+=k.includes(' ')?4:2}return total}
function originalFileName(r){const source=String(r.file||r.title||"");try{return decodeURIComponent(source.split("/").pop()||r.title||"Resource file")}catch(e){return source.split("/").pop()||r.title||"Resource file"}}
function shortTitle(r){let s=originalFileName(r).replace(/\.(pptx?|docx?|pdf|xlsx?|csv)$/i,"").replace(/[_]+/g," ").replace(/[–—-]+/g," ");s=s.replace(/\b(copy|final|updated?|new|version|ver|draft)\b/gi," ").replace(/\b(v\s*\d+(?:\.\d+)*)\b/gi," ").replace(/\b(year|yr|y)\s*(7|8|9|10|11|12)\b/gi," ").replace(/^\s*(7|8|9|10|11|12)\s+/i,"").replace(/\b(lesson|week|term)\s*\d+[a-z]?\b/gi," ").replace(/\b(pptx?|powerpoint|document|docx?|pdf)\b/gi," ").replace(/\(\s*\d+\s*\)/g," ").replace(/\s+/g," ").trim();if(!s||s.length<3)s=r.topic||r.subtopic||r.type||"Science Resource";return s.replace(/\b\w/g,m=>m.toUpperCase())}
function card(r){const fileName=originalFileName(r);return `<article class="syllabus-resource"><div><b>${shortTitle(r)}</b><small>${[r.type,r.year,r.strand].filter(Boolean).join(" • ")}</small><small><strong>Original file:</strong> ${fileName}</small></div><div class="resource-actions">${r.file?`<a class="download-btn" href="${encodeURI(r.file)}" download>Download</a>`:""}</div></article>`}
function grouped(rows){const order=['PowerPoints','Worksheets','Practicals','Notes','Revision','Tests','Other Resources'];const groups={};rows.forEach(r=>{const k=r.type||"Other Resources";(groups[k]??=[]).push(r)});return Object.entries(groups).sort((a,b)=>{const ai=order.indexOf(a[0]),bi=order.indexOf(b[0]);return (ai<0?99:ai)-(bi<0?99:bi)||a[0].localeCompare(b[0])}).map(([type,items])=>`<details class="resource-type-group"><summary><b>${type}</b><span>${items.length}</span></summary><div class="compact-resource-list">${items.map(card).join("")}</div></details>`).join("")}
function dot(x,rows){return `<section class="dotpoint-card"><div class="dotpoint-head"><span class="strand-badge">${x[0]}</span><div><h2>${x[1]}</h2><p>${x[2]}</p></div><span class="dot-count">${rows.length} resources</span></div>${rows.length?grouped(rows):'<p class="empty-dot">No matching resources currently indexed.</p>'}</section>`}
function assignRows(points,year,q){const buckets=points.map(()=>[]);R.filter(r=>r.year===year).forEach(r=>{let best=-1,bestScore=0;points.forEach((p,i)=>{if(!strandOK(r,p[0]))return;const s=score(r,p[3]);if(s>bestScore){bestScore=s;best=i}});if(best>=0&&bestScore>0){if(!q||hay(r).includes(q)||norm(points[best].join(' ')).includes(q))buckets[best].push(r)}});return buckets}
function render(){const host=document.getElementById("syllabusContent"),q=norm(document.getElementById("syllabusSearch").value);if(active==="ATAR"){host.innerHTML='<div class="syllabus-list">'+ATAR.map(x=>{const rows=R.filter(r=>norm(r.course)===norm(x[0])&&(!q||hay(r).includes(q)));return dot(["ATAR",x[1],x[2],[]],rows)}).join('')+'</div>';return}const points=CURRICULUM[active]||[],buckets=assignRows(points,active,q);host.innerHTML='<div class="syllabus-list">'+points.map((x,i)=>dot(x,buckets[i])).join('')+'</div>'}
document.querySelectorAll('[data-syl-year]').forEach(b=>b.onclick=()=>{active=b.dataset.sylYear;document.querySelectorAll('[data-syl-year]').forEach(x=>x.classList.toggle('active',x===b));render()});document.getElementById('syllabusSearch').addEventListener('input',render);window.addEventListener('science-vault-resources-ready',render);render();