import {waitForAccess} from './access-client.mjs?v=2026.10.9-classes';
import {myClasses,classTasks,assignTask,classReport} from './class-client.mjs';
import {SUBJECTS} from './registration-options.mjs';
const $=id=>document.getElementById(id);let rooms=[],draft=null,state,request=0;
function message(text,error=false){$('classStatus').textContent=text;$('classStatus').dataset.kind=error?'error':'info'}
$('taskYear').innerHTML=[7,8,9,10,11,12].map(y=>`<option>${y}</option>`).join('');
function subjects(){const values=Number($('taskYear').value)<=10?['Science','Mathematics','English']:SUBJECTS;$('taskCourse').replaceChildren(...values.map(s=>{const o=document.createElement('option');o.textContent=s;return o}))}subjects();$('taskYear').addEventListener('change',subjects);
try{draft=JSON.parse(sessionStorage.getItem('vault-assignment-draft')||'null')}catch{}
if(draft){$('taskKind').value='assessment';$('taskTitle').value=draft.title||'Class assessment';$('taskYear').value=draft.yearGroup;subjects();const normal=s=>s.replace(/ ATAR$/,'').toLowerCase();const opt=[...$('taskCourse').options].find(o=>normal(o.value)===normal(draft.course));if(opt)$('taskCourse').value=opt.value;$('taskUnit').value=draft.unit||'';$('draftStatus').textContent=draft.questionIds.length+' built questions ready to assign.'}
async function render(){const ticket=++request,code=$('classSelect').value;$('classCode').textContent=code;if(!code)return;try{const [tasks,report]=await Promise.all([classTasks(code),classReport(code)]);if(ticket!==request)return;$('taskList').replaceChildren();for(const task of tasks){const card=document.createElement('article');card.className='task-card';const h=document.createElement('h3');h.textContent=task.title;const p=document.createElement('p');p.textContent=task.course+' · Year '+task.yearGroup+' · '+task.kind+(task.dueDate?' · Due '+task.dueDate:'');card.append(h,p);$('taskList').appendChild(card)}if(!tasks.length)$('taskList').textContent='No tasks assigned yet.';
 $('reportSummary').replaceChildren();for(const[label,value]of [['Students',report.students.length],['Saved attempts',report.results.length],['Assigned tasks',tasks.length]]){const p=document.createElement('p'),n=document.createElement('strong');n.textContent=value;p.append(n,document.createTextNode(label));$('reportSummary').appendChild(p)}
 const table=document.createElement('table');table.innerHTML='<thead><tr><th>Student</th><th>Year</th><th>Attempts</th><th>Auto-checked marks</th><th>Assigned tasks completed</th></tr></thead>';const body=document.createElement('tbody');for(const student of report.students){const attempts=report.results.filter(r=>r.studentUid===student.studentUid),earned=attempts.reduce((s,r)=>s+r.earned,0),max=attempts.reduce((s,r)=>s+r.max,0),completed=new Set(attempts.filter(r=>r.taskId&&r.completed).map(r=>r.taskId)).size;const tr=document.createElement('tr');for(const value of [student.displayName||'Student '+student.studentUid.slice(0,6),student.yearGroup,attempts.length,max?`${earned}/${max} (${Math.round(earned/max*100)}%)`:'No auto-checked marks',completed]){const td=document.createElement('td');td.textContent=value;tr.appendChild(td)}body.appendChild(tr)}table.appendChild(body);$('studentReport').replaceChildren(table);
 $('attemptReport').replaceChildren();for(const result of report.results.slice(0,30)){const article=document.createElement('details');article.className='task-card';const summary=document.createElement('summary');const student=report.students.find(s=>s.studentUid===result.studentUid);summary.textContent=(student?.displayName||'Student')+' · '+result.title+' · '+(result.max?result.earned+'/'+result.max+' auto marks':result.selfReported?'Student-marked completion':'Self-review')+' · '+(result.createdAt?.toDate().toLocaleString()||'');article.appendChild(summary);const p=document.createElement('p');p.textContent=result.course+' · Year '+result.yearGroup+' · '+result.manualCount+' questions for self-review';article.appendChild(p);for(const response of result.responses||[]){const line=document.createElement('p');line.textContent=response.questionId+': '+(Array.isArray(response.answers)?response.answers.map(String).join(' | '):'');article.appendChild(line)}$('attemptReport').appendChild(article)}message('Class tasks and progress are up to date.')}catch{message('The class report could not load. Publish the latest Firestore rules and confirm your teacher account is approved.',true)}}
$('classSelect').addEventListener('change',render);$('refreshReport').addEventListener('click',render);
$('taskForm').addEventListener('submit',async e=>{e.preventDefault();const kind=$('taskKind').value;if(kind==='assessment'&&draft&&(Number($('taskYear').value)!==draft.yearGroup||$('taskCourse').value.replace(/ ATAR$/,'').toLowerCase()!==draft.course.replace(/ ATAR$/,'').toLowerCase())){message('Keep the built assessment’s original year and subject, or build a new assessment.',true);return}if(kind==='assessment'&&!draft?.questionIds?.length){message('Build an assessment first and use Assign to class.',true);return}$('assignTask').disabled=true;try{const url=new URL(kind==='lesson'?'topic-hub.html':'student-quiz.html',location.href);url.searchParams.set('course',$('taskCourse').value);url.searchParams.set('year',$('taskYear').value);if($('taskUnit').value.trim())url.searchParams.set('unit',$('taskUnit').value.trim());if($('taskTopic').value.trim())url.searchParams.set('topic',$('taskTopic').value.trim());await assignTask($('classSelect').value,{title:$('taskTitle').value.trim(),kind,course:$('taskCourse').value,yearGroup:Number($('taskYear').value),unit:$('taskUnit').value.trim(),topic:$('taskTopic').value.trim(),instructions:$('taskInstructions').value.trim(),dueDate:$('taskDue').value,minutes:Number($('taskMinutes').value),questionIds:kind==='assessment'?[...new Set(draft.questionIds.map(String))]:[],url:url.pathname.split('/').pop()+url.search});await render();message('Task assigned to the class.')}catch{message('Task could not be assigned. Confirm approval and Firebase setup, then try again.',true)}finally{$('assignTask').disabled=false}});
state=await waitForAccess();if(state.member?.role==='teacher'&&state.member.status==='active'){try{rooms=await myClasses(state);$('classSelect').replaceChildren(...rooms.map(r=>{const o=document.createElement('option');o.value=r.code;o.textContent=r.name+' · '+r.code;return o}));await render()}catch{message('Your classes could not load. Check Firebase setup.',true)}}
