const R=window.SCIENCE_VAULT_RESOURCES||[], Q=window.SCIENCE_VAULT_QUESTIONS||[], $=id=>document.getElementById(id), uniq=a=>[...new Set(a)].sort();
function answerFile(r){return !!r.answers||/answer|solution|marking key|mark key|answers|solutions/i.test(r.title||"")}
function assessment(r){return r.year==="Year 7"&&(/\/Tests\//i.test(r.file||"")||/test|exam|quiz|assessment|validation/i.test([r.type,r.title,r.description].join(" ")))}
const ALL=R.filter(assessment), A=ALL.filter(r=>!answerFile(r)), KEYS=ALL.filter(answerFile);
function schoolOf(r){if(r.school)return r.school;const p=(r.file||"").split("/");const i=p.indexOf("Tests");return i>=0?p[i+1]||"Unknown School":"Unknown School"}
function fill(){const ss=uniq(A.map(r=>r.strand).filter(Boolean));$("strand").innerHTML='<option value="All">All strands</option>'+ss.map(x=>'<option>'+x+'</option>').join("");updateTopics()}
function updateTopics(){const s=$("strand").value, ts=uniq(A.filter(r=>s==="All"||r.strand===s).map(r=>r.topic).filter(Boolean));$("topic").innerHTML='<option value="All">All topics</option>'+ts.map(x=>'<option>'+x+'</option>').join("");updateSources()}
function updateSources(){const s=$("strand").value,t=$("topic").value,p=A.filter(r=>(s==="All"||r.strand===s)&&(t==="All"||r.topic===t));const schools=uniq(p.map(schoolOf));$("source").innerHTML='<option value="All">All uploaded assessments ('+p.length+')</option>'+schools.map(x=>'<option value="'+x+'">'+x+' ('+p.filter(r=>schoolOf(r)===x).length+')</option>').join("")}
function norm(s){return (s||"").toLowerCase()}
function relatedKey(r){const stem=norm(r.title).replace(/answer(s)?|solution(s)?|marking key|mark key|final|copy|wip|\d{4}/g,"").replace(/[^a-z0-9]+/g," ").trim();return KEYS.find(k=>{const ks=norm(k.title).replace(/answer(s)?|solution(s)?|marking key|mark key|final|copy|wip|\d{4}/g,"").replace(/[^a-z0-9]+/g," ").trim();return k.strand===r.strand&&(ks.includes(stem)||stem.includes(ks))})}
let current=[];
function eligible(){const s=$("strand").value,t=$("topic").value,src=$("source").value,q=norm($("sourceSearch").value);return A.filter(r=>(s==="All"||r.strand===s)&&(t==="All"||r.topic===t)&&(src==="All"||schoolOf(r)===src)&&(!q||norm([r.title,r.topic,r.subtopic,schoolOf(r)].join(" ")).includes(q)))}
function draw(){ $("paperTitle").textContent=$("title").value||"Science Test"; if(!current.length){$("questions").innerHTML='<div class="notice"><strong>No matching uploaded assessments.</strong><br>Change the strand, topic, school or search words.</div>';$("totalMarks").textContent=A.length+" assessment sources indexed";return}
$("questions").innerHTML=current.map((r,i)=>{const key=relatedKey(r);return '<div class="question"><div class="question-head"><strong>'+(i+1)+'. '+r.title+'</strong></div><div class="source">'+[r.strand,r.topic,r.subtopic,schoolOf(r)].filter(Boolean).join(" › ")+'</div><div class="actions"><button class="maker-btn secondary preview-source" data-file="'+encodeURI(r.file)+'">Preview assessment</button><a class="maker-btn secondary" href="'+encodeURI(r.file)+'" download>Download source</a>'+(key?'<a class="maker-btn secondary" href="'+encodeURI(key.file)+'" target="_blank">Answer / marking key</a>':'')+'</div></div>'}).join("");$("totalMarks").textContent=current.length+" assessment source"+(current.length===1?"":"s");document.querySelectorAll(".preview-source").forEach(b=>b.onclick=()=>window.open(b.dataset.file,"_blank"))}
function questionPool(){const s=$("strand").value,t=$("topic").value,q=norm($("sourceSearch").value);return Q.filter(x=>x.year==="Year 7"&&(s==="All"||x.strand===s)&&(t==="All"||x.topic===t)&&(!q||norm([x.text,x.title,x.topic,x.subtopic,x.school].join(" ")).includes(q)))}
function drawQuestions(list){let total=0;$("paperTitle").textContent=$("title").value||"Science Test";if(!list.length){$("questions").innerHTML='<div class="notice"><strong>No individual questions indexed yet for this selection.</strong><br>The assessment files are available in Assessment files mode while questions are extracted and checked.</div>';$("totalMarks").textContent="0 indexed questions";return}$("questions").innerHTML=list.map((x,i)=>{total+=Number(x.marks)||0;const opts=x.options?.length?'<ol type="A">'+x.options.map(o=>'<li>'+o+'</li>').join("")+'</ol>':'';return '<div class="question"><div class="question-head"><strong>'+(i+1)+'. '+x.text+'</strong><span class="marks">['+(x.marks||"?")+' mark'+(x.marks==1?"":"s")+']</span></div>'+opts+'<div class="source">'+[x.strand,x.topic,x.school].filter(Boolean).join(" › ")+'</div>'+(x.source?'<div class="actions"><a class="maker-btn secondary" href="'+encodeURI(x.source)+'" target="_blank">Source assessment</a></div>':'')+'</div>'}).join("");$("totalMarks").textContent="Total: "+total+" marks"}
function generate(){const n=Math.max(1,Math.min(50,+$("count").value||10));if($("bankMode")?.value==="indexed"){let pool=[...questionPool()].sort(()=>Math.random()-.5),target=+$("targetMarks").value||0,out=[];if(target){let sum=0;for(const x of pool){if(sum>=target)break;out.push(x);sum+=Number(x.marks)||0}}else out=pool.slice(0,n);current=[];drawQuestions(out)}else{const pool=eligible();current=[...pool].sort(()=>Math.random()-.5).slice(0,n);draw()}}
$("strand").onchange=updateTopics;$("topic").onchange=updateSources;$("source").onchange=()=>{};$("sourceSearch").oninput=()=>{};$("generate").onclick=generate;$("shuffle").onclick=generate;$("toggleAnswers").style.display="none";fill();draw();