const R=window.SCIENCE_VAULT_RESOURCES||[], Q=window.SCIENCE_VAULT_QUESTIONS||[], $=id=>document.getElementById(id), uniq=a=>[...new Set(a)].sort();
let liveQuestions=[...Q]; let candidates=[];
function ext(path){return (path.split(".").pop()||"").toLowerCase()}
function cleanText(s){return (s||"").replace(/\r/g,"").replace(/[ \t]+/g," ").replace(/\n{3,}/g,"\n\n").trim()}
function markFrom(s){let m=s.match(/\[(\d{1,2})\s*(?:marks?)?\]/i)||s.match(/\((\d{1,2})\s*marks?\)/i)||s.match(/(?:^|\s)(\d{1,2})\s*marks?\b/i);return m?Number(m[1]):null}
function splitQuestions(text,r){
 let raw=cleanText(text);
raw=raw.replace(/\s+(?=(?:Question\s*)?\d{1,2}(?:\s*[\(\.]?[a-z]\)?)?[\.\)\:\-]\s+)/gi,"\n");
const lines=raw.split("\n").map(x=>x.trim()).filter(Boolean), out=[]; let cur=null;
 const qre=/^(?:question\s*)?(\d{1,2})[\.\)\:\-]\s+(.+)/i;
 for(const line of lines){const m=line.match(qre);if(m){if(cur&&cur.text.length>8)out.push(cur);cur={id:"auto-"+m[1]+(m[2]||"")+"-"+btoa(unescape(encodeURIComponent(r.file))).slice(0,12),title:r.title,text:m[3],year:r.year,strand:r.strand,topic:r.topic,subtopic:r.subtopic,marks:markFrom(line),type:"short",options:[],answer:"",source:r.file,answerSource:"",school:schoolOf(r),number:m[1]+(m[2]?"("+m[2]+")":"")}}else if(cur&&line.length<500){if(/^\(?[A-Da-d]\)[\.\s]|^[A-Da-d][\.\)]\s/.test(line)){cur.type="mc";cur.options.push(line.replace(/^\(?[A-Da-d]\)?[\.\)]?\s*/,""))}else cur.text+=" "+line;if(!cur.marks)cur.marks=markFrom(line)}}
 if(cur&&cur.text.length>8)out.push(cur);
 return out.filter(x=>x.text.length>12&&x.text.length<900&&!/name:|date:|total marks|instructions|end of test|out of \\d+ marks/i.test(x.text)&&/[?]|\\b(explain|describe|identify|state|calculate|determine|which|what|why|how|select|choose|name|compare|define|draw|label|predict|give)\\b/i.test(x.text))
}
async function extractDocx(r){
 const res=await fetch(encodeURI(r.file));if(!res.ok)throw Error("fetch");const ab=await res.arrayBuffer();const zip=await JSZip.loadAsync(ab);const xml=await zip.file("word/document.xml")?.async("text");if(!xml)return[];
 const doc=new DOMParser().parseFromString(xml,"application/xml");const paras=[...doc.getElementsByTagNameNS("*","p")].map(p=>[...p.getElementsByTagNameNS("*","t")].map(t=>t.textContent).join("")).join("\n");return splitQuestions(paras,r)
}
async function extractPdf(r){
 if(!window.pdfjsLib)return[];const pdf=await pdfjsLib.getDocument(encodeURI(r.file)).promise;let text="";for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),tc=await p.getTextContent();text+=tc.items.map(x=>x.str).join(" ")+"\n"}return splitQuestions(text,r)
}
async function loadAssessmentQuestions(){
 const status=$("extractStatus");if(status)status.textContent="Reading uploaded assessment files and detecting individual questions…";const pool=eligible().filter(r=>["docx","pdf"].includes(ext(r.file))).slice(0,80);let added=[];
 for(const r of pool){try{const qs=ext(r.file)==="docx"?await extractDocx(r):await extractPdf(r);added.push(...qs)}catch(e){}}
 const seen=new Set(liveQuestions.map(x=>x.source+"|"+x.text));for(const q of added){const k=q.source+"|"+q.text;if(!seen.has(k)){seen.add(k);liveQuestions.push(q)}}
 candidates=added.filter(goodQuestion);if(status)status.textContent=added.length?added.length+" candidate questions detected. They must be reviewed before entering the checked bank.":"0 usable candidate questions detected.";return added.length
}
function answerFile(r){return !!r.answers||/answer|solution|marking key|mark key|answers|solutions/i.test(r.title||"")}
function assessment(r){return r.year==="Year 7"&&(/\/Tests\//i.test(r.file||"")||/test|exam|quiz|assessment|validation/i.test([r.type,r.title,r.description].join(" ")))}
const ALL=R.filter(assessment), A=ALL.filter(r=>!answerFile(r)), KEYS=ALL.filter(answerFile);
function schoolOf(r){if(r.school)return r.school;const p=(r.file||"").split("/");const i=p.indexOf("Tests");return i>=0?p[i+1]||"Unknown School":"Unknown School"}
function fill(){const ss=uniq(A.map(r=>r.strand).filter(Boolean));$("strand").innerHTML='<option value="All">All strands</option>'+ss.map(x=>'<option>'+x+'</option>').join("");updateTopics()}
function updateTopics(){const s=$("strand").value, ts=uniq(A.filter(r=>s==="All"||r.strand===s).map(r=>r.topic).filter(Boolean));$("topic").innerHTML='<option value="All">All topics</option>'+ts.map(x=>'<option>'+x+'</option>').join("");updateSources()}
function updateSources(){const s=$("strand").value,t=$("topic").value,p=A.filter(r=>(s==="All"||r.strand===s)&&(t==="All"||r.topic===t));const schools=uniq(p.map(schoolOf));$("source").innerHTML='<option value="All">All uploaded assessments ('+p.length+')</option>'+schools.map(x=>'<option value="'+x+'">'+x+' ('+p.filter(r=>schoolOf(r)===x).length+')</option>').join("")}
function norm(s){return (s||"").toLowerCase()}
function relatedKey(r){const stem=norm(r.title).replace(/answer(s)?|solution(s)?|marking key|mark key|final|copy|wip|\d{4}/g,"").replace(/[^a-z0-9]+/g," ").trim();return KEYS.find(k=>{const ks=norm(k.title).replace(/answer(s)?|solution(s)?|marking key|mark key|final|copy|wip|\d{4}/g,"").replace(/[^a-z0-9]+/g," ").trim();return k.strand===r.strand&&(ks.includes(stem)||stem.includes(ks))})}
let current=[];
function eligible(){const s=$("strand").value,t=$("topic").value,src=$("source").value,q=norm($("sourceSearch").value);return A.filter(r=>(s==="All"||r.strand===s)&&(t==="All"||r.topic===t)&&(src==="All"||schoolOf(r)===src)&&(!q||norm([r.title,r.topic,r.subtopic,schoolOf(r)].join(" ")).includes(q)))}
function draw(){ $("paperTitle").textContent=$("title").value||"Science Test"; if(!current.length){$("questions").innerHTML='<div class="notice"><strong>No matching uploaded assessments.</strong><br>Change the strand, topic, school or search words.</div>';$("totalMarks").textContent=A.length+" assessment sources indexed";return}
$("questions").innerHTML=current.map((r,i)=>{const key=relatedKey(r);return '<div class="question"><div class="question-head"><strong>'+(i+1)+'. '+r.title+'</strong></div><div class="source">'+[r.strand,r.topic,r.subtopic,schoolOf(r)].filter(Boolean).join(" › ")+'</div><div class="actions"><button class="maker-btn secondary preview-source" data-file="'+encodeURI(r.file)+'">Preview assessment</button><a class="maker-btn secondary" href="'+encodeURI(r.file)+'" download>Download source</a>'+(key?'<a class="maker-btn secondary" href="'+encodeURI(key.file)+'" target="_blank">Answer / marking key</a>':'')+'</div></div>'}).join("");$("totalMarks").textContent=current.length+" assessment source"+(current.length===1?"":"s");document.querySelectorAll(".preview-source").forEach(b=>b.onclick=()=>window.open(b.dataset.file,"_blank"))}
function questionPool(){const s=$("strand").value,t=$("topic").value;return liveQuestions.filter(x=>x.year==="Year 7"&&(s==="All"||x.strand===s)&&(t==="All"||x.topic===t))}
function goodQuestion(x){const t=(x.text||"").trim();return t&&!/^undefined\b/i.test(t)&&!/end of test|word sleuth|not going to be marked|out of \d+ marks/i.test(t)&&t.length>12&&(/[?]/.test(t)||/\b(explain|describe|identify|state|calculate|determine|which|what|why|how|select|choose|name|compare|define|draw|label|predict|give|find)\b/i.test(t))}
function drawQuestions(list){list=list.filter(goodQuestion);let total=0;$("paperTitle").textContent=$("title").value||"Science Test";if(!list.length){$("questions").innerHTML='<div class="notice"><strong>No individual questions indexed yet for this selection.</strong><br>The assessment files are available in Assessment files mode while questions are extracted and checked.</div>';$("totalMarks").textContent="0 indexed questions";return}$("questions").innerHTML=list.map((x,i)=>{total+=Number(x.marks)||0;const opts=x.options?.length?'<ol type="A">'+x.options.map(o=>'<li>'+o+'</li>').join("")+'</ol>':'';return '<div class="question"><div class="question-head"><strong>'+(i+1)+'. '+x.text+'</strong><span class="marks">'+(x.marks?'['+x.marks+' mark'+(x.marks==1?'':'s')+']':'')+'</span></div>'+opts+'<div class="source">'+[x.strand,x.topic,x.school].filter(Boolean).join(" › ")+'</div>'+(x.source?'<div class="actions"><a class="maker-btn secondary" href="'+encodeURI(x.source)+'" target="_blank">Source assessment</a></div>':'')+'</div>'}).join("");$("totalMarks").textContent="Total: "+total+" marks"}
async function generate(){const n=Math.max(1,Math.min(50,+$("count").value||10));if($("bankMode")?.value==="indexed"){await loadAssessmentQuestions();let pool=[...questionPool()].filter(goodQuestion).sort(()=>Math.random()-.5),target=+$("targetMarks").value||0,out=[];if(target){let sum=0;for(const x of pool){if(sum>=target)break;out.push(x);sum+=Number(x.marks)||0}}else out=pool.slice(0,n);current=[];drawQuestions(out)}else{const pool=eligible();current=[...pool].sort(()=>Math.random()-.5).slice(0,n);draw()}}
$("strand").onchange=updateTopics;$("topic").onchange=updateSources;$("source").onchange=()=>{};$("sourceSearch").oninput=()=>{};$("generate").onclick=generate;$("shuffle").onclick=generate;$("toggleAnswers").style.display="none";fill();draw();
function reviewCandidates(){
 const p=$("reviewPanel");p.style.display="block";
 if(!candidates.length){p.innerHTML='<div class="notice"><strong>No candidates loaded.</strong><br>Select a strand/topic or assessment search, then click Build assessment once to scan matching assessments.</div>';return}
 p.innerHTML='<h3>Question-bank review</h3><p>Only approve questions that are complete and correctly extracted.</p>'+candidates.slice(0,50).map((q,i)=>'<div class="question"><label class="check"><input type="checkbox" class="approveQ" data-i="'+i+'"> <strong>Approve</strong></label><div>'+q.text+'</div><div class="source">'+[q.title,q.school,q.topic].filter(Boolean).join(" › ")+'</div></div>').join("")+'<div class="actions"><button class="maker-btn primary" id="useApproved">Use approved questions this session</button></div>';
 $("useApproved").onclick=()=>{const approved=[...document.querySelectorAll(".approveQ:checked")].map(x=>candidates[+x.dataset.i]);const seen=new Set(liveQuestions.map(x=>x.source+"|"+x.text));approved.forEach(q=>{const k=q.source+"|"+q.text;if(!seen.has(k)){seen.add(k);liveQuestions.push(q)}});p.innerHTML='<div class="notice"><strong>'+approved.length+' questions approved for this session.</strong><br>They can now be used by the Checked question bank mode.</div>'}
}
$("reviewBank").onclick=reviewCandidates;
