/* Topic tile dashboard + contextual Biology photography layer */
(function(){
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function render(host,topics,onOpen){host.innerHTML='<div class="topic-head"><div><span class="eyebrow">CHOOSE A TOPIC</span><h2>Biological Sciences</h2><p>Select a topic to begin its self-paced learning module.</p></div><span class="topic-count">'+topics.length+' topics</span></div><div class="topic-tile-grid">'+topics.map((t,i)=>'<button class="topic-tile" data-i="'+i+'"><span class="topic-icon">'+t.icon+'</span><span class="topic-number">TOPIC '+String(i+1).padStart(2,'0')+'</span><strong>'+esc(t.title)+'</strong><small>'+esc(t.subtitle)+'</small><span class="topic-open">Start topic <b>→</b></span></button>').join('')+'</div>';host.querySelectorAll('.topic-tile').forEach(b=>b.onclick=()=>onOpen(topics[+b.dataset.i]));}
window.ScienceVaultTopicTiles={render};

/* Openly licensed Wikimedia Commons photographs. Photos are contextual enrichment; diagrams remain only where they teach a concept. */
const photos=[
 {match:/scientific naming|genus|species/i,url:'https://commons.wikimedia.org/wiki/Special:FilePath/Lion%20in%20namibia.jpg',alt:'Lion in Namibia',cap:'Lion — an example used when learning genus and species naming.',credit:'Kevin Pluck / Wikimedia Commons, CC BY 2.0'},
 {match:/food chain|consumer|energy transfer/i,url:'https://commons.wikimedia.org/wiki/Special:FilePath/Common%20grasshopper.jpg',alt:'Common grasshopper',cap:'A grasshopper can act as a primary consumer in a grassland food chain.',credit:'ProjectManhattan / Wikimedia Commons, CC0'},
 {match:/food web|predator|prey|population/i,url:'https://commons.wikimedia.org/wiki/Special:FilePath/Rana-temporaria-grasfrosch.jpg',alt:'Common frog',cap:'A frog can be both predator and prey, linking several pathways in a food web.',credit:'Wikimedia Commons'},
 {match:/biodiversity|characteristic|classify|classification|organism/i,url:'https://commons.wikimedia.org/wiki/Special:FilePath/Swallowtail%20butterfly%20on%20fern%20plant.jpg',alt:'Swallowtail butterfly on a fern',cap:'Living things show a wide diversity of observable characteristics.',credit:'Wikimedia Commons'},
 {match:/vertebrate|animal group|broad group|kingdom/i,url:'https://commons.wikimedia.org/wiki/Special:FilePath/Lion%20waiting%20in%20Namibia.jpg',alt:'Lion in grassland',cap:'Scientists use shared characteristics to place organisms into increasingly specific groups.',credit:'Kevin Pluck / Wikimedia Commons'}
];
function addPhoto(){const screen=document.querySelector('#svScreen'),heading=document.querySelector('#svScreenTitle');if(!screen||!heading||screen.querySelector('.sv-photo'))return;const text=(heading.textContent+' '+screen.textContent).slice(0,1400);const p=photos.find(x=>x.match.test(text));if(!p)return;/* Do not force an image onto every screen. */
 const screensWithVisual=screen.querySelector('.sv-visual');if(screensWithVisual&&Math.random()<0.65)return;
 const fig=document.createElement('figure');fig.className='sv-photo';fig.innerHTML='<img loading="lazy" src="'+p.url+'" alt="'+esc(p.alt)+'"><figcaption><strong>'+esc(p.cap)+'</strong><small>'+esc(p.credit)+'</small></figcaption>';screen.insertAdjacentElement('afterbegin',fig);
}
const style=document.createElement('style');style.textContent='.sv-photo{margin:4px 0 26px;border-radius:18px;overflow:hidden;background:#102f3b;box-shadow:0 8px 24px rgba(18,45,58,.16)}.sv-photo img{display:block;width:100%;height:300px;object-fit:cover}.sv-photo figcaption{display:flex;justify-content:space-between;gap:18px;align-items:center;padding:13px 16px;color:#fff}.sv-photo figcaption strong{font-size:13px;line-height:1.45}.sv-photo figcaption small{font-size:10px;opacity:.78;text-align:right;max-width:210px}@media(max-width:600px){.sv-photo img{height:220px}.sv-photo figcaption{display:block}.sv-photo figcaption small{display:block;text-align:left;margin-top:5px}}';document.head.appendChild(style);
const observer=new MutationObserver(()=>requestAnimationFrame(addPhoto));observer.observe(document.documentElement,{subtree:true,childList:true});
})();