/* Science Vault WA reusable activities + mastery engine */
(function(){
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const BANK={
 'Introduction to Classification':{
  example:'<div class="sv-worked"><span>WORKED EXAMPLE</span><h4>Which features help us classify these organisms?</h4><div class="sv-example-grid"><div>🦁 <b>Lion</b><small>fur · backbone · feeds on other organisms</small></div><div>🐸 <b>Frog</b><small>moist skin · backbone · lays eggs</small></div><div>🦋 <b>Butterfly</b><small>6 legs · exoskeleton · wings</small></div><div>🌿 <b>Fern</b><small>green leaves · photosynthesises · no backbone</small></div></div><p>Useful classification features are <strong>observable and consistent</strong>. Colour alone is often less useful because individuals of the same group can have different colours.</p></div>',
  fill:{text:'Scientists use observable ___ to organise organisms into groups.',answer:'characteristics'},
  sort:{prompt:'Drag each organism into the best broad group.',items:[['Lion','Animal'],['Fern','Plant'],['Mushroom','Fungus'],['Butterfly','Animal']],bins:['Animal','Plant','Fungus']},
  review:[['Why do scientists classify organisms?',['To organise biodiversity and communicate clearly','To make organisms identical','Only to name pets'],0],['Which is an observable characteristic?',['Number of legs','Favourite food chosen by a person','A scientist’s opinion'],0],['A lion and kangaroo both have fur. This is an example of a…',['shared characteristic','scientific name','habitat only'],0],['Which feature is most useful for grouping an insect?',['Six legs','Its nickname','The day it was observed'],0],['Classification systems help scientists…',['compare organisms consistently','remove biodiversity','change organisms'],0],['Which is a living organism?',['Fern','Rock','Glass'],0],['Biodiversity means…',['the variety of living things','one species only','the size of an organism'],0],['A useful classification feature should be…',['observable and consistent','based on a guess','different every minute'],0]]
 },
 'Classification Hierarchy':{
  example:'<div class="sv-worked"><span>WORKED EXAMPLE</span><h4>A lion through the hierarchy</h4><p><b>Animalia → Chordata → Mammalia → Carnivora → Felidae → Panthera → leo</b></p><p>At each step the group becomes smaller and the organisms share more characteristics. <em>Panthera leo</em> identifies the lion at species level.</p></div>',
  fill:{text:'The broadest classification level is ___ and the most specific is species.',answer:'kingdom'},
  sort:{prompt:'Drag the levels into broad or specific ends of the hierarchy.',items:[['Kingdom','Broad'],['Phylum','Broad'],['Genus','Specific'],['Species','Specific']],bins:['Broad','Specific']},
  review:[['Which level is broadest?',['Kingdom','Genus','Species'],0],['Which level is most specific?',['Species','Class','Phylum'],0],['What comes directly before species?',['Genus','Family','Kingdom'],0],['Which order is correct?',['Family → Genus → Species','Species → Family → Genus','Genus → Kingdom → Species'],0],['Moving toward species, organisms generally share…',['more characteristics','fewer characteristics','no characteristics'],0],['Which comes after phylum?',['Class','Species','Kingdom'],0],['Which comes after order?',['Family','Phylum','Kingdom'],0],['Panthera in Panthera leo is the…',['genus','species','kingdom'],0]]
 },
 'Scientific Naming':{
  example:'<div class="sv-worked"><span>WORKED EXAMPLE</span><h4>Why use <em>Panthera leo</em>?</h4><p>Common names can differ between languages and places. A two-part scientific name gives scientists one shared name. The <strong>genus</strong> begins with a capital letter and the <strong>species</strong> begins with a lower-case letter.</p></div>',
  fill:{text:'In the scientific name Panthera leo, Panthera is the ___ name.',answer:'genus'},
  sort:{prompt:'Drag each name into correctly or incorrectly formatted.',items:[['Homo sapiens','Correct'],['homo Sapiens','Incorrect'],['Canis lupus','Correct'],['CANIS LUPUS','Incorrect']],bins:['Correct','Incorrect']},
  review:[['Which is correctly formatted?',['Homo sapiens','homo Sapiens','HOMO SAPIENS'],0],['The first word is the…',['genus','species','family'],0],['The second word begins with a…',['lower-case letter','capital letter','number'],0],['Scientific names help because they are…',['shared internationally','different in every school','based on colour'],0],['In Canis lupus, lupus is the…',['species name','genus name','kingdom'],0],['Which is a two-part scientific name?',['Panthera leo','lion','Animalia'],0],['The genus name begins with…',['a capital letter','a lower-case letter','a symbol'],0],['Scientific naming reduces confusion caused by…',['different common names','classification evidence','observable features'],0]]
 },
 default:{
  example:'<div class="sv-worked"><span>WORKED EXAMPLE</span><h4>Apply the idea</h4><p>Science becomes easier when you connect a definition to a real example. Read the explanation above, identify the evidence, then explain how that evidence supports the conclusion.</p></div>',
  fill:{text:'A food-chain arrow shows the direction of ___ transfer.',answer:'energy'},
  sort:{prompt:'Drag each item into the best category.',items:[['Grass','Producer'],['Grasshopper','Consumer'],['Frog','Consumer'],['Fern','Producer']],bins:['Producer','Consumer']},
  review:[['What do food-chain arrows show?',['Direction of energy transfer','Animal size','Habitat temperature'],0],['Which is a producer?',['Grass','Frog','Hawk'],0],['Which is a consumer?',['Grasshopper','Fern','Grass'],0],['A food web contains…',['interconnected food chains','one organism only','no energy transfer'],0],['A predator…',['hunts other organisms','always makes its own food','is always a plant'],0],['Prey is an organism that…',['is eaten by a predator','makes sunlight','has no role in a food web'],0],['If one population changes, a food web may…',['affect other populations','remain completely unrelated','stop containing energy'],0],['Human activity can…',['change feeding relationships','never affect ecosystems','remove the need for producers'],0]]
 }
};
function config(topic){return BANK[topic]||BANK.default}
function fillActivity(cfg){return '<div class="sv-activity sv-fill"><span class="sv-act-label">FILL IN THE BLANK</span><h4>'+cfg.text.replace('___','<input aria-label="missing word" autocomplete="off">')+'</h4><button class="sv-check-btn">Check answer</button><div class="sv-act-feedback"></div></div>'}
function wireFill(root,cfg){const box=root.querySelector('.sv-fill');if(!box)return;box.querySelector('button').onclick=()=>{const v=box.querySelector('input').value.trim().toLowerCase(),ok=v===cfg.answer.toLowerCase();const f=box.querySelector('.sv-act-feedback');f.innerHTML=ok?'✓ <strong>Correct.</strong>':'Not yet. Re-read the example and try again.';f.className='sv-act-feedback '+(ok?'good':'try')}}
function sortActivity(cfg){return '<div class="sv-activity sv-sort"><span class="sv-act-label">DRAG & DROP</span><h4>'+esc(cfg.prompt)+'</h4><div class="sv-dragbank">'+cfg.items.map((x,i)=>'<button draggable="true" data-id="'+i+'">'+esc(x[0])+'</button>').join('')+'</div><div class="sv-bins">'+cfg.bins.map(b=>'<div class="sv-bin" data-bin="'+esc(b)+'"><b>'+esc(b)+'</b><div></div></div>').join('')+'</div><button class="sv-check-btn">Check sorting</button><div class="sv-act-feedback"></div></div>'}
function wireSort(root,cfg){const box=root.querySelector('.sv-sort');if(!box)return;let drag=null;box.querySelectorAll('[draggable]').forEach(x=>{x.ondragstart=()=>drag=x;x.onclick=()=>{drag=x}});box.querySelectorAll('.sv-bin').forEach(bin=>{bin.ondragover=e=>e.preventDefault();bin.ondrop=e=>{e.preventDefault();if(drag)bin.querySelector('div').appendChild(drag)};bin.onclick=e=>{if(e.target===bin||e.target===bin.querySelector('b')||e.target===bin.querySelector('div'))if(drag)bin.querySelector('div').appendChild(drag)}});box.querySelector('.sv-check-btn').onclick=()=>{let placed=0,correct=0;box.querySelectorAll('.sv-bin').forEach(bin=>bin.querySelectorAll('[data-id]').forEach(x=>{placed++;if(cfg.items[+x.dataset.id][1]===bin.dataset.bin)correct++}));const f=box.querySelector('.sv-act-feedback');const ok=placed===cfg.items.length&&correct===cfg.items.length;f.innerHTML=ok?'✓ <strong>Perfect sorting.</strong>':'You have '+correct+' of '+cfg.items.length+' correct. Move the items and try again.';f.className='sv-act-feedback '+(ok?'good':'try')}}
function masteryHTML(topic,cfg){return '<div class="sv-mastery"><span class="sv-act-label">MASTERY REVIEW</span><h3>Score 100% to complete '+esc(topic)+'</h3><p>You can retry any questions you miss. The topic is complete only when every answer is correct.</p><div class="sv-score">Current mastery: <b>0%</b></div><div class="sv-review">'+cfg.review.map((q,qi)=>'<div class="sv-rq" data-q="'+qi+'"><h4>'+(qi+1)+'. '+esc(q[0])+'</h4>'+q[1].map((o,oi)=>'<button data-a="'+oi+'">'+String.fromCharCode(65+oi)+'. '+esc(o)+'</button>').join('')+'<div class="sv-qfeed"></div></div>').join('')+'</div><div class="sv-master-message"></div></div>'}
function wireMastery(root,topic,cfg,onMaster){const box=root.querySelector('.sv-mastery');if(!box)return;const key='sv-master:'+topic,correct=new Set(JSON.parse(localStorage.getItem(key)||'[]'));function paint(){const pc=Math.round(correct.size/cfg.review.length*100);box.querySelector('.sv-score b').textContent=pc+'%';if(pc===100){box.querySelector('.sv-master-message').innerHTML='<div class="sv-mastered">🏆 <strong>100% Mastery achieved!</strong><br>This topic is complete.</div>';onMaster&&onMaster();}localStorage.setItem(key,JSON.stringify([...correct]))}box.querySelectorAll('.sv-rq').forEach(r=>{const qi=+r.dataset.q;if(correct.has(qi))r.classList.add('mastered');r.querySelectorAll('button').forEach(btn=>btn.onclick=()=>{const ok=+btn.dataset.a===cfg.review[qi][2],f=r.querySelector('.sv-qfeed');if(ok){correct.add(qi);r.classList.add('mastered');f.innerHTML='✓ Correct';}else{correct.delete(qi);r.classList.remove('mastered');f.innerHTML='Not quite — try this question again.'}paint()})});paint()}
function enhance(root,topic,screenTitle){const cfg=config(topic),t=screenTitle.toLowerCase();if(/worked example|example|apply/.test(t)&&!root.querySelector('.sv-worked'))root.insertAdjacentHTML('afterbegin',cfg.example);if(/quick check|check understanding|practice/.test(t)&&!root.querySelector('.sv-fill')){root.insertAdjacentHTML('beforeend',fillActivity(cfg.fill));wireFill(root,cfg.fill)}if(/independent|application|activity/.test(t)&&!root.querySelector('.sv-sort')){root.insertAdjacentHTML('beforeend',sortActivity(cfg.sort));wireSort(root,cfg.sort)}}
function mastery(topic,onMaster){const cfg=config(topic),wrap=document.createElement('div');wrap.innerHTML=masteryHTML(topic,cfg);wireMastery(wrap,topic,cfg,onMaster);return wrap}
window.ScienceVaultMastery={enhance,mastery};
const s=document.createElement('style');s.textContent='.sv-worked,.sv-activity,.sv-mastery{border-radius:18px;padding:22px;margin:18px 0;border:2px solid #c7dce7;background:#f4f9fc}.sv-worked>span,.sv-act-label{font-size:10px;font-weight:900;letter-spacing:.13em;color:#285c83}.sv-worked h4,.sv-activity h4{margin:7px 0 12px;font-size:19px}.sv-example-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0}.sv-example-grid div{background:#fff;border:1px solid #ccdce5;border-radius:12px;padding:13px;font-size:24px}.sv-example-grid b,.sv-example-grid small{display:block;font-size:13px}.sv-example-grid small{color:#587080;margin-top:4px}.sv-fill input{border:0;border-bottom:3px solid #285c83;background:#fff;padding:6px 9px;font-size:16px;max-width:170px}.sv-check-btn{border:0;border-radius:9px;background:#285c83;color:#fff;padding:10px 14px;font-weight:800;cursor:pointer}.sv-act-feedback{margin-top:10px;font-weight:700}.sv-act-feedback.good{color:#147047}.sv-act-feedback.try{color:#9a4a34}.sv-dragbank{display:flex;flex-wrap:wrap;gap:9px;margin:13px 0}.sv-dragbank button,.sv-bin button{border:1px solid #8eaaba;background:#fff;border-radius:9px;padding:9px 12px;cursor:grab;font-weight:700}.sv-bins{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:12px 0}.sv-bin{min-height:100px;border:2px dashed #8aa8b8;border-radius:12px;padding:10px;background:#fff}.sv-bin>b{display:block;margin-bottom:8px}.sv-bin div{display:flex;flex-wrap:wrap;gap:6px}.sv-mastery{background:#f8f5ff;border-color:#b8a8dc}.sv-score{position:sticky;top:8px;z-index:2;background:#30245e;color:#fff;padding:12px 15px;border-radius:10px;margin:14px 0;font-weight:800}.sv-rq{background:#fff;border:1px solid #ddd7ed;border-radius:13px;padding:15px;margin:10px 0}.sv-rq.mastered{border:2px solid #3a9b6a;background:#f0fbf5}.sv-rq h4{margin:0 0 10px}.sv-rq button{display:block;width:100%;text-align:left;border:1px solid #d8dbea;background:#fff;border-radius:9px;padding:9px 11px;margin:6px 0;cursor:pointer}.sv-qfeed{font-weight:800;margin-top:6px}.sv-mastered{text-align:center;background:#daf3e5;color:#125f3b;padding:18px;border-radius:13px;margin-top:16px;font-size:17px}@media(max-width:650px){.sv-example-grid,.sv-bins{grid-template-columns:1fr}}';document.head.appendChild(s);
})();