// WA Curriculum Mathematics Year 9 - 2026 aligned starter assessment bank
(function(){const S='mathematics',Y=9,Q=[];const a=(id,topic,type,difficulty,marks,question,answer,extra={})=>Q.push({id,subject:S,year:Y,topic,type,difficulty,marks,question,answer,...extra});const N='Number and algebra',G='Measurement and geometry',P='Probability and statistics';
a('m9-001',N,'Multiple choice','Easy',1,'Simplify x³ × x⁵. A. x⁸ B. x¹⁵ C. 2x⁸ D. x²','A. x⁸ [1]');
a('m9-002',N,'Short answer','Medium',3,'Simplify (3x²)(4x³).','12x⁵ [3].');
a('m9-003',N,'Short answer','Medium',3,'Expand and simplify 3(2x-5)+4x.','6x-15+4x=10x-15 [3].');
a('m9-004',N,'Short answer','Medium',4,'Solve 3(x-2)=2x+7.','3x-6=2x+7 [1]; x-6=7 [1]; x=13 [2].',{response:'working'});
a('m9-005',N,'Application','Hard',5,'Solve the inequality 4x-7 < 17 and represent the solution in words.','4x<24 [1]; x<6 [2]; all real values less than 6 [2].',{response:'working'});
a('m9-006',N,'Multiple choice','Medium',1,'Which equation has gradient 3 and y-intercept -2? A. y=3x-2 B. y=-2x+3 C. y=3x+2 D. y=-3x-2','A. y=3x-2 [1]');
a('m9-007',N,'Application','Medium',4,'For y=2x+5, calculate y when x=-3 and identify the y-intercept.','y=-1 [2]; y-intercept=5 [2].',{response:'working'});
a('m9-008',N,'Application','Hard',5,'A line passes through (2,5) and (6,13). Find its gradient and equation.','m=(13-5)/(6-2)=2 [2]; y=2x+b [1]; 5=4+b → b=1 [1]; y=2x+1 [1].',{response:'working'});
a('m9-009',N,'Short answer','Medium',3,'Factorise x²+7x.','x(x+7) [3].');
a('m9-010',N,'Application','Hard',5,'A quantity of $850 increases by 6% each year. Calculate its value after 2 years.','$850×1.06² [2]; = $955.06 approximately [3].',{response:'working'});
a('m9-011',N,'Extended response','Hard',6,'Plan A costs $25 plus $0.10 per message. Plan B costs $10 plus $0.20 per message. Form equations and determine when the plans cost the same.','A=25+0.10m [1]; B=10+0.20m [1]; set equal [1]; 15=0.10m [1]; m=150 [1]; both cost $40 [1].',{responseLines:10});
a('m9-012',G,'Multiple choice','Easy',1,'A right triangle has legs 9 cm and 12 cm. Its hypotenuse is: A. 15 cm B. 18 cm C. 21 cm D. 144 cm','A. 15 cm [1]');
a('m9-013',G,'Short answer','Medium',4,'A right triangle has hypotenuse 13 cm and one shorter side 5 cm. Find the other side.','x²+25=169 [2]; x²=144 [1]; x=12 cm [1].',{response:'working'});
a('m9-014',G,'Application','Medium',4,'A cylinder has radius 3 cm and height 10 cm. Calculate its volume to one decimal place.','V=πr²h=90π [2]; ≈282.7 cm³ [2].',{response:'working'});
a('m9-015',G,'Application','Hard',5,'A prism has a constant cross-sectional area of 24 cm² and length 15 cm. Calculate its volume and explain the method.','V=area of cross-section × length [2]; 24×15=360 cm³ [2]; explanation [1].',{response:'working'});
a('m9-016',G,'Multiple choice','Medium',1,'If two triangles are similar, corresponding angles are: A. supplementary B. equal C. always 90° D. unrelated','B. equal [1]');
a('m9-017',G,'Application','Hard',5,'Two similar triangles have corresponding side lengths 6 cm and 15 cm. A second side on the smaller triangle is 8 cm. Find the corresponding larger side.','Scale factor=15/6=2.5 [2]; 8×2.5=20 cm [3].',{response:'working'});
a('m9-018',G,'Short answer','Medium',3,'Find the sum of the interior angles of a hexagon.','(6-2)×180=720° [3].',{response:'working'});
a('m9-019',G,'Application','Hard',5,'A regular polygon has each exterior angle equal to 24°. Determine the number of sides.','Exterior angles sum 360° [1]; n=360/24 [2]; n=15 [2].',{response:'working'});
a('m9-020',G,'Extended response','Hard',6,'A rectangular water tank is 2.4 m long, 1.5 m wide and 1.2 m deep. Calculate its capacity in litres when full and the amount of water when it is 75% full.','Volume=4.32 m³ [2]; =4320 L [2]; 75%=3240 L [2].',{responseLines:9});
a('m9-021',P,'Multiple choice','Easy',1,'Events that cannot occur at the same time are called: A. independent B. mutually exclusive C. identical D. complementary only','B. mutually exclusive [1]');
a('m9-022',P,'Short answer','Medium',4,'A bag contains 4 red and 6 blue counters. A counter is selected, replaced, then another is selected. Find P(red then red).','4/10×4/10 [2] =16/100=4/25 [2].',{response:'working'});
a('m9-023',P,'Application','Hard',5,'A bag contains 4 red and 6 blue counters. Two are selected without replacement. Find P(red then red).','4/10×3/9 [3] =12/90=2/15 [2].',{response:'working'});
a('m9-024',P,'Multiple choice','Medium',1,'If two events are independent, then: A. the first changes the probability of the second B. one cannot occur C. one event does not affect the probability of the other D. their probabilities must be equal','C [1]');
a('m9-025',P,'Short answer','Medium',4,'For data 5, 6, 7, 8, 9, 20, calculate the mean.','Sum=55 [2]; mean=55/6≈9.17 [2].',{response:'working'});
a('m9-026',P,'Application','Medium',5,'Two classes have the same median test score, but Class A has a much larger interquartile range. Explain what this says about the distributions.','Centres/medians are same [2]; middle 50% of A is more spread [2]; A shows greater variability [1].',{responseLines:7});
a('m9-027',P,'Extended response','Hard',6,'A researcher surveys 40 students from one high-achieving class to estimate study time for the entire Year 9 cohort. Evaluate the sampling method and propose a better method.','Sample likely biased/not representative [2]; class achievement/study habits may differ [1]; sample across whole cohort [1]; random or stratified sampling [1]; explain representation [1].',{responseLines:10});
a('m9-028',N,'Multiple choice','Medium',1,'Which is equivalent to 4.2 × 10⁵? A. 42,000 B. 420,000 C. 4,200,000 D. 0.00042','B. 420,000 [1]');
a('m9-029',N,'Short answer','Medium',4,'Calculate (6 × 10⁴)(3 × 10²) in scientific notation.','18×10⁶ [2] =1.8×10⁷ [2].',{response:'working'});
a('m9-030',G,'Application','Medium',4,'A map has scale 1:25 000. A walking trail measures 14 cm on the map. Find the actual distance in kilometres.','14×25,000=350,000 cm [2]=3.5 km [2].',{response:'working'});
a('m9-031',P,'Application','Hard',5,'A tree diagram models two selections with replacement from a bag containing 3 green and 2 yellow counters. Find P(one of each colour in any order).','P(GY)=3/5×2/5=6/25 [2]; P(YG)=2/5×3/5=6/25 [2]; total=12/25 [1].',{response:'working'});
a('m9-032',N,'Application','Medium',4,'A car depreciates by 12% from a value of $24,000 in one year. Find its value after the year.','Multiplier=0.88 [2]; 24,000×0.88=$21,120 [2].',{response:'working'});
a('m9-033',G,'Short answer','Hard',4,'A right triangle has hypotenuse √85 cm and one leg 6 cm. Find the other leg exactly.','x²+36=85 [2]; x²=49 [1]; x=7 cm [1].',{response:'working'});
a('m9-034',P,'Application','Medium',4,'A data set has median 18, Q1=12 and Q3=27. Calculate the interquartile range and interpret it.','IQR=27-12=15 [2]; middle 50% spans 15 units / lies from 12 to 27 [2].');
a('m9-035',N,'Extended response','Hard',6,'A streaming service charges a fixed monthly fee plus a charge per movie. A customer pays $29 for 3 movies and $41 for 7 movies. Determine a linear rule for total cost C in terms of number of movies m.','Gradient=(41-29)/(7-3)=3 [2]; C=3m+b [1]; 29=9+b → b=20 [2]; C=3m+20 [1].',{responseLines:10});
window.AssessmentQuestionBank=(window.AssessmentQuestionBank||[]).concat(Q);})();