// WA Curriculum Mathematics Year 8 - 2026 aligned starter assessment bank
(function(){const S='mathematics',Y=8,Q=[];const a=(id,topic,type,difficulty,marks,question,answer,extra={})=>Q.push({id,subject:S,year:Y,topic,type,difficulty,marks,question,answer,...extra});const N='Number and algebra',G='Measurement and geometry',P='Probability and statistics';
a('m8-001',N,'Multiple choice','Easy',1,'Evaluate (-3)². A. -9 B. -6 C. 6 D. 9','D. 9 [1]');
a('m8-002',N,'Short answer','Medium',3,'Simplify 3a + 5a - 2.','8a - 2 [3].');
a('m8-003',N,'Short answer','Medium',3,'Solve 5x - 7 = 23.','5x=30 [1]; x=6 [2].',{response:'working'});
a('m8-004',N,'Application','Medium',4,'A $320 bicycle is reduced by 15%. Calculate the sale price.','Discount=$48 [2]; sale price=$272 [2].',{response:'working'});
a('m8-005',N,'Application','Hard',4,'A quantity increases from 80 to 98. Calculate the percentage increase.','Increase=18 [1]; 18/80×100 [2]; 22.5% [1].',{response:'working'});
a('m8-006',N,'Multiple choice','Medium',1,'Which is equal to 2³ × 2⁴? A. 2⁷ B. 4⁷ C. 2¹² D. 4¹²','A. 2⁷ [1]');
a('m8-007',N,'Short answer','Medium',3,'Expand 4(x + 3).','4x + 12 [3].');
a('m8-008',N,'Short answer','Hard',4,'Factorise 12x + 18 completely.','6(2x+3) [4].');
a('m8-009',N,'Application','Medium',4,'The rule y=3x-2 is used. Find y when x=7 and find x when y=19.','y=19 [2]; 19=3x-2 → x=7 [2].',{response:'working'});
a('m8-010',N,'Extended response','Hard',6,'A taxi fare is modelled by C=4.50+1.80d, where d is distance in kilometres. Explain each number in the model and calculate the fare for 12 km.','$4.50 fixed/start charge [1]; $1.80 per km [1]; d is km [1]; substitute 12 [1]; 4.50+21.60 [1]; $26.10 [1].',{responseLines:9});
a('m8-011',G,'Multiple choice','Easy',1,'What is the area of a parallelogram with base 9 cm and perpendicular height 5 cm? A. 14 B. 22.5 C. 45 D. 90','C. 45 cm² [1]');
a('m8-012',G,'Short answer','Medium',3,'Calculate the area of a trapezium with parallel sides 8 cm and 14 cm and height 6 cm.','1/2(8+14)×6=66 cm² [3].',{response:'working'});
a('m8-013',G,'Short answer','Medium',3,'A rectangular prism measures 6 cm by 4 cm by 3 cm. Calculate its volume.','6×4×3=72 cm³ [3].',{response:'working'});
a('m8-014',G,'Application','Hard',5,'A cylindrical tank has radius 2 m and height 3 m. Calculate its volume in terms of π and to the nearest tenth of a cubic metre.','V=πr²h [1]; =π×4×3=12π m³ [2]; ≈37.7 m³ [2].',{response:'working'});
a('m8-015',G,'Multiple choice','Medium',1,'A triangle has angles 48° and 67°. The third angle is: A. 55° B. 65° C. 75° D. 115°','B. 65° [1]');
a('m8-016',G,'Short answer','Medium',3,'An exterior angle of a triangle is 125°. One opposite interior angle is 52°. Find the other opposite interior angle.','125-52=73° [3].',{response:'working'});
a('m8-017',G,'Application','Medium',4,'A right triangle has shorter sides 6 cm and 8 cm. Find the hypotenuse.','c²=6²+8²=100 [2]; c=10 cm [2].',{response:'working'});
a('m8-018',G,'Application','Hard',5,'A ladder 5 m long reaches 4 m up a vertical wall. How far is its base from the wall?','x²+4²=5² [2]; x²=9 [1]; x=3 m [2].',{response:'working'});
a('m8-019',G,'Extended response','Hard',6,'A rectangular box is 40 cm long, 30 cm wide and 25 cm high. Calculate its volume in cm³ and litres, then explain the conversion.','30,000 cm³ [2]; 1000 cm³=1 L [1]; 30 L [2]; clear conversion explanation [1].',{responseLines:9});
a('m8-020',P,'Multiple choice','Easy',1,'Two fair coins are tossed. What is P(two heads)? A. 1/2 B. 1/3 C. 1/4 D. 3/4','C. 1/4 [1]');
a('m8-021',P,'Short answer','Medium',4,'Two fair six-sided dice are rolled. How many equally likely ordered outcomes are in the sample space? What is P(a total of 7)?','36 outcomes [2]; six outcomes total 7, so 6/36=1/6 [2].',{response:'working'});
a('m8-022',P,'Application','Medium',4,'A basketball player makes 36 of 50 free throws. Use relative frequency to estimate the probability that the player scores the next free throw.','36/50=0.72 [3]; estimated probability 0.72 or 72% [1].',{response:'working'});
a('m8-023',P,'Multiple choice','Medium',1,'Which graph is usually most suitable for comparing the distribution of a numerical variable across groups? A. Box plot B. Pie chart only C. Pictograph only D. Flowchart','A. Box plot [1]');
a('m8-024',P,'Short answer','Medium',4,'For 3, 5, 6, 6, 8, 10, 12, find the median and range.','Median=6 [2]; range=9 [2].',{response:'working'});
a('m8-025',P,'Application','Hard',5,'A survey about school lunches is completed only by students who buy lunch from the canteen. Explain a possible source of bias and how the sampling could be improved.','Sample excludes students who bring lunch [2]; may overrepresent canteen users/preferences [1]; use random/stratified sample from whole student population [2].',{responseLines:7});
a('m8-026',P,'Extended response','Hard',6,'Design a simulation for two free throws where the probability of scoring each shot is 0.7. Explain how random digits could represent score/miss and how you would estimate P(at least one score).','Assign 7/10 digits to score and 3/10 to miss [2]; select two random digits per trial [1]; repeat many trials [1]; count trials with at least one score [1]; divide by total trials [1].',{responseLines:10});
a('m8-027',N,'Multiple choice','Medium',1,'Which number is irrational? A. 0.25 B. 3/7 C. √2 D. -5','C. √2 [1]');
a('m8-028',N,'Short answer','Medium',3,'Write 0.00056 in scientific notation.','5.6 × 10⁻⁴ [3].');
a('m8-029',N,'Application','Hard',4,'A population of 25,000 increases by 8%. Find the new population.','Increase=2000 [2]; new population=27,000 [2].',{response:'working'});
a('m8-030',G,'Short answer','Medium',3,'Convert 2.75 L to cubic centimetres.','2750 cm³ [3].');
a('m8-031',G,'Application','Hard',4,'A square has diagonal length 10 cm. Use Pythagoras to find the side length to one decimal place.','2s²=100 [2]; s=√50≈7.1 cm [2].',{response:'working'});
a('m8-032',P,'Application','Medium',4,'A spinner has experimental results: red 42, blue 33, green 25 in 100 spins. Estimate each probability.','Red 0.42, blue 0.33, green 0.25 [3]; probabilities total 1 [1].');
a('m8-033',N,'Extended response','Hard',6,'A savings account contains $1200 and earns simple interest of 4% per year. Calculate the interest and final balance after 3 years, explaining your method.','Annual interest=$48 [2]; 3-year interest=$144 [2]; balance=$1344 [1]; explanation [1].',{responseLines:9});
a('m8-034',P,'Short answer','Medium',3,'State the sample space for choosing one letter at random from the word MATHS, treating positions as equally likely.','M, A, T, H, S [3].');
a('m8-035',G,'Application','Medium',4,'A scale model uses 1:200. A building is 7.5 cm tall on the model. Find its actual height in metres.','7.5×200=1500 cm [2]; =15 m [2].',{response:'working'});
window.AssessmentQuestionBank=(window.AssessmentQuestionBank||[]).concat(Q);})();