// WA Curriculum Mathematics Year 7 - 2026 aligned starter assessment bank
(function(){const S='mathematics',Y=7,Q=[];const a=(id,topic,type,difficulty,marks,question,answer,extra={})=>Q.push({id,subject:S,year:Y,topic,type,difficulty,marks,question,answer,...extra});
const N='Number and algebra',G='Measurement and geometry',P='Probability and statistics';
a('m7-001',N,'Multiple choice','Easy',1,'Which number is greatest? A. -8 B. -2 C. 0 D. -1','C. 0 [1]');
a('m7-002',N,'Multiple choice','Easy',1,'Evaluate 6 + 3 × 4. A. 36 B. 18 C. 24 D. 15','B. 18 [1]');
a('m7-003',N,'Short answer','Easy',2,'Calculate: -7 + 12.','5 [2]');
a('m7-004',N,'Short answer','Medium',3,'A submarine is at -35 m and rises 18 m. What is its new position relative to sea level? Show your working.','-35 + 18 = -17; new position is 17 m below sea level / -17 m [3].',{response:'working'});
a('m7-005',N,'Multiple choice','Medium',1,'Which fraction is equivalent to 0.375? A. 3/8 B. 3/5 C. 5/8 D. 7/20','A. 3/8 [1]');
a('m7-006',N,'Short answer','Medium',3,'Calculate 3/4 + 2/3. Give your answer in simplest form.','9/12 + 8/12 = 17/12 = 1 5/12 [3].',{response:'working'});
a('m7-007',N,'Short answer','Medium',3,'Find 15% of $240.','0.15 × 240 = $36 [3].',{response:'working'});
a('m7-008',N,'Application','Medium',4,'A jacket originally costs $80 and is discounted by 25%. Calculate the sale price.','$20 discount [2]; sale price $60 [2].',{response:'working'});
a('m7-009',N,'Multiple choice','Medium',1,'Simplify 5x + 2x - 3. A. 7x - 3 B. 7x + 3 C. 10x - 3 D. 3x','A. 7x - 3 [1]');
a('m7-010',N,'Short answer','Medium',3,'Solve 4x + 3 = 19.','4x=16 [1]; x=4 [2].',{response:'working'});
a('m7-011',N,'Application','Hard',4,'The rule for a sequence is 3n + 2. Find the 10th term and explain what n represents.','3(10)+2=32 [3]; n represents the term number/position [1].',{response:'working'});
a('m7-012',N,'Extended response','Hard',5,'A school buys 18 packs of pens. Each pack contains 12 pens and costs $8.40. Calculate the total number of pens, total cost, and cost per pen. Show a clear method.','216 pens [1]; total cost $151.20 [2]; cost per pen $0.70 [2].',{responseLines:8});
a('m7-013',G,'Multiple choice','Easy',1,'How many millimetres are in 2.4 metres? A. 24 B. 240 C. 2400 D. 24000','C. 2400 [1]');
a('m7-014',G,'Short answer','Medium',3,'A rectangle is 8.5 cm long and 4 cm wide. Calculate its perimeter.','2(8.5+4)=25 cm [3].',{response:'working'});
a('m7-015',G,'Short answer','Medium',3,'Calculate the area of a triangle with base 12 cm and perpendicular height 7 cm.','1/2 × 12 × 7 = 42 cm² [3].',{response:'working'});
a('m7-016',G,'Application','Medium',4,'A rectangular garden measures 9 m by 6 m. A 1 m wide path runs inside the garden around all four edges. Calculate the area of the remaining central grass section.','Central dimensions 7 m × 4 m [2]; area 28 m² [2].',{response:'working'});
a('m7-017',G,'Multiple choice','Medium',1,'Two angles on a straight line are x and 125°. What is x? A. 45° B. 55° C. 65° D. 125°','B. 55° [1]');
a('m7-018',G,'Short answer','Medium',3,'Two vertically opposite angles are labelled (3x + 5)° and 80°. Find x.','3x+5=80 [1]; 3x=75 [1]; x=25 [1].',{response:'working'});
a('m7-019',G,'Application','Hard',4,'A scale drawing uses 1 cm to represent 2.5 m. A wall measures 7.2 cm on the drawing. Find the actual wall length.','7.2 × 2.5 = 18 m [4].',{response:'working'});
a('m7-020',G,'Extended response','Hard',5,'A room is 5.8 m by 4.2 m. Square tiles have side length 0.4 m. Estimate how many tiles are needed to cover the floor and explain why extra tiles may be required.','Floor area 24.36 m² [2]; tile area 0.16 m² [1]; 24.36/0.16=152.25 so at least 153 tiles mathematically [1]; extra for cuts/breakage/wastage [1].',{responseLines:8});
a('m7-021',P,'Multiple choice','Easy',1,'A fair six-sided die is rolled. What is P(rolling a 4)? A. 1/2 B. 1/4 C. 1/6 D. 4/6','C. 1/6 [1]');
a('m7-022',P,'Short answer','Medium',3,'A bag contains 5 red, 3 blue and 2 green counters. One counter is chosen at random. Find P(blue).','10 counters total [1]; P(blue)=3/10 [2].',{response:'working'});
a('m7-023',P,'Application','Medium',4,'A coin is tossed 50 times and lands heads 28 times. Calculate the experimental probability of heads and compare it with the theoretical probability.','Experimental P=28/50=0.56 [2]; theoretical P=0.5 [1]; experimental result is 0.06 higher / reasonably close with variation expected [1].',{response:'working'});
a('m7-024',P,'Multiple choice','Medium',1,'Which data type is categorical? A. Height B. Temperature C. Favourite sport D. Time taken','C. Favourite sport [1]');
a('m7-025',P,'Short answer','Medium',4,'For the data 4, 7, 7, 8, 9, 10, 11, find the median and range.','Median=8 [2]; range=11-4=7 [2].',{response:'working'});
a('m7-026',P,'Application','Hard',5,'Class A has mean test score 68 and Class B has mean 72. Explain why these means alone are not enough to conclude that every student in Class B performed better.','Mean describes centre, not individual scores [1]; distributions may overlap [1]; Class A can contain scores above Class B scores [1]; spread/range and sample information matter [1]; clear conclusion [1].',{responseLines:7});
a('m7-027',P,'Extended response','Hard',6,'Design a simple simulation to estimate the probability of obtaining at least one 6 when a fair die is rolled twice. Describe the trial, what is recorded, and how the estimate is calculated.','Roll die twice per trial [1]; record whether at least one roll is 6 [1]; repeat many trials [1]; count successful trials [1]; estimated probability = successes/total trials [1]; more trials generally improve stability of estimate [1].',{responseLines:10});
a('m7-028',N,'Application','Hard',4,'A recipe uses flour and sugar in the ratio 5:2. If 750 g of flour is used, how much sugar is needed?','750/5=150 g per part [2]; sugar=2×150=300 g [2].',{response:'working'});
a('m7-029',N,'Short answer','Medium',3,'Write 0.045 as a percentage.','4.5% [3].');
a('m7-030',G,'Short answer','Medium',3,'A full turn is divided into 8 equal angles. Find the size of each angle.','360°/8=45° [3].',{response:'working'});
a('m7-031',P,'Application','Medium',4,'The values 12, 13, 13, 14, 15, 15, 40 are recorded. Identify the possible outlier and explain its effect on the mean.','40 [2]; it pulls/increases the mean upward [2].');
a('m7-032',N,'Multiple choice','Hard',1,'Which value is closest to 2/3? A. 0.23 B. 0.60 C. 0.67 D. 0.75','C. 0.67 [1]');
a('m7-033',G,'Application','Medium',4,'A map scale is 1:50 000. Two locations are 6 cm apart on the map. Find the actual distance in kilometres.','6×50,000=300,000 cm [2] = 3,000 m = 3 km [2].',{response:'working'});
a('m7-034',P,'Short answer','Medium',3,'List the sample space when a coin is tossed twice.','HH, HT, TH, TT [3].');
a('m7-035',N,'Extended response','Hard',6,'A phone plan charges $18 per month plus $0.12 per text message. Write an expression for the monthly cost for t texts, then calculate the cost for 175 texts and explain your substitution.','C=18+0.12t [2]; substitute t=175 [1]; 0.12×175=21 [1]; total $39 [1]; explanation of variable/substitution [1].',{responseLines:9});
window.AssessmentQuestionBank=(window.AssessmentQuestionBank||[]).concat(Q);})();