"""Precise vector teaching models and original visual-text stimuli."""
from html import escape
VISUALS={}
def svg(title,inside):
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 400" role="img" aria-label="{escape(title)}"><title>{escape(title)}</title><rect width="640" height="400" rx="18" fill="#f9f7fc"/>{inside}</svg>'
def model(key,title,rows,explain,limit):
    inside=''
    for i,(label,note) in enumerate(rows):
        y=25+i*88
        inside+=f'<rect x="24" y="{y}" width="592" height="74" rx="12" fill="'+['#e6dcf4','#e0eff0','#fbebda','#e6e8f4'][i]+'"/>'
        inside+=f'<text x="42" y="{y+27}" font-family="Arial,sans-serif" font-size="20" font-weight="bold" fill="#38264e">{escape(label)}</text><text x="42" y="{y+54}" font-family="Arial,sans-serif" font-size="17" fill="#243744">{escape(note)}</text>'
    VISUALS[key]=dict(title=title,svg=svg(title,inside),explain=explain,limit=limit)
model('analysis','A reasoning path, not a sentence formula',[('Claim','What does this choice help the text mean?'),('Evidence','Select and accurately identify the relevant detail.'),('Explanation','Connect the choice with a specific interpretation.'),('Qualification','Test the claim against context or another detail.')], 'Move from an answer to evidence and an explained relationship. Return to the question throughout.', 'These are reasoning functions. A paragraph need not have four sentences or follow a fixed acronym.')
model('context','Two contexts and the text between them',[('Creation','Who makes this text, for whom, and in what situation?'),('Textual choices','Which words, images or conventions need explanation?'),('Reception','What position or knowledge might a reader bring?'),('Bounded claim','Explain the connection; do not invent biography.')], 'Creation and reception contexts can differ. The claim still needs evidence from the text.', 'Hypothetical receptions are possibilities, not a documented history of these original teaching texts.')
model('structure','Development through a meaningful turn',[('Opening','Establish the issue, scene or question.'),('Development','Add relevant pressure, evidence or reflection.'),('Turning point','Complicate or revise the initial direction.'),('Ending','Resolve, qualify or reopen the central relationship.')], 'The ending should grow from the development. A turn changes more than the location.', 'Different genres can organise development differently. This model does not require a plot twist.')
model('visual','Read relationships in a layout',[('Salience','What draws attention first, and through which resources?'),('Composition','How do position, size and space relate elements?'),('Language + image','How does wording anchor or change the image?'),('Meaning','Which view of the subject do these choices invite?')], 'Combine observed choices into an interpretation. Consider a possible competing reading.', 'Colours and positions have contextual associations; they do not carry one universal emotion.')
model('film','Resources working across a sequence',[('Shot','Distance, angle, framing and what is withheld.'),('Sound','Story-world sound, added sound and meaningful absence.'),('Transition','How one shot changes the meaning of another.'),('Interpretation','Explain the sequence without inventing an outcome.')], 'The hand, door and interrupted entry work together in the supplied storyboard.', 'A written storyboard is a specified design, not a recording of an actual performance.')
model('argument','A proposal with a fair test',[('Position','State the change or judgement being proposed.'),('Support','Explain relevant reasons and evidence.'),('Counterargument','Address a serious constraint without caricature.'),('Next step','Justify an action whose scope follows from the reasons.')], 'The counterargument may revise the proposal rather than merely appear in a token sentence.', 'A persuasive teaching example does not establish real-world data. Fictional figures remain fictional.')
model('revision','Four separate revision questions',[('Task','Does the argument answer the actual prompt?'),('Evidence','Is attribution and every quoted word accurate?'),('Reasoning','Does explanation connect choice and meaning?'),('Expression','Are sentences, punctuation and reference clear?')], 'Revise the idea before the final proofreading pass; both matter.', 'A checklist records review activity. It is not an automatic assessment of writing quality.')
model('genre','A transformation involves choices',[('Retain','Name the central relationship to carry forward.'),('Change','Use the new form’s resources deliberately.'),('Omit','State what the new version cannot preserve.'),('Evaluate','Test the result for the new audience and purpose.')], 'A station scene can become a letter or shot sequence, but each version gives readers different access.', 'Changing layout alone does not establish that an adaptation succeeds.')
model('digital','Popularity and access are different',[('Visible metric','Likes show interaction, not truth or representativeness.'),('Sorting','Engagement order may differ from time order.'),('Pinned update','Corrections can be made easier to locate.'),('Access route','Provide usable information beyond the thread.')], 'The neighbour’s question leads to a specific correction; the counts alone cannot demonstrate inclusion.', 'These are supplied fictional interface features, not an audit of a real platform algorithm.')
model('comparison','Compare through a shared question',[('Common basis','What issue or relationship do both texts address?'),('Text A','Select choices which support its particular treatment.'),('Text B','Explain its treatment with equally relevant evidence.'),('Synthesis','Why does the similarity or difference matter?')], 'Compare motivation and practical access, or recognition and decision process, rather than listing devices.', 'Balanced reasoning does not require identical word counts for each text.')
model('oral','Listening and speaking as a feedback loop',[('Hear the claim','Paraphrase before agreeing or challenging.'),('Respond','Use relevant evidence; distinguish motive from consequence.'),('Test delivery','Can a listener restate the intended proposal?'),('Revise','Name what changed and the evidence for the change.')], 'A transcript supports reasoning practice; rehearsal with a listener tests delivery and understanding.', 'The page does not record audio or automatically judge speaking and listening.')
model('exam','Current Year 12 examination design',[('Comprehending · 30%','Two questions · around 200–300 words each · 60 min'),('Responding · 40%','Choose one of six · studied texts · 60 min'),('Composing · 30%','Choose one of four or five · sustained text · 60 min'),('Total time','10 min reading + 3 hours working')], 'These are the current examination section weightings and suggested times, checked against the official design.', 'School assessment weightings differ. Check the actual paper’s instructions; our rehearsal is original practice.')
door='<rect x="275" y="125" width="108" height="190" fill="#f8db8e"/><rect x="275" y="125" width="18" height="190" fill="#614852"/><polygon points="293,315 383,315 460,366 194,366" fill="#b59657"/><circle cx="208" cy="273" r="12" fill="#edf2f6"/><path d="M208 286 L208 323 M208 298 L190 308 M208 298 L224 310 M208 323 L194 349 M208 323 L221 349" stroke="#edf2f6" stroke-width="7" fill="none"/>'
posterA='<rect x="16" y="16" width="608" height="368" rx="12" fill="#15283d"/>'+door+'<text x="320" y="57" text-anchor="middle" fill="#fff" font-family="Arial,sans-serif" font-size="25" font-weight="bold">A PLACE FOR YOUR NEXT CHAPTER</text><text x="320" y="91" text-anchor="middle" fill="#d8e6ed" font-family="Arial,sans-serif" font-size="19">Town Library · A shared public space</text><rect x="40" y="345" width="560" height="30" fill="#f8db8e"/><text x="320" y="366" text-anchor="middle" fill="#15283d" font-family="Arial,sans-serif" font-size="17">Thursday late session · 5–8 pm · Free entry</text>'
posterB='<rect x="16" y="16" width="608" height="368" rx="12" fill="#e8edf4"/><text x="320" y="61" text-anchor="middle" fill="#26384e" font-family="Arial,sans-serif" font-size="27" font-weight="bold">MEASURE WHAT MOVES</text><text x="320" y="117" text-anchor="middle" fill="#526583" font-family="Arial,sans-serif" font-size="19">Town Library · Annual loan transactions</text><text x="320" y="197" text-anchor="middle" fill="#4b3476" font-family="Arial,sans-serif" font-size="68" font-weight="bold">24,000</text>'
for x in [105,195,285,375,465]:
    posterB+=f'<rect x="{x}" y="234" width="65" height="58" rx="4" fill="#718ca2"/><path d="M{x+8} 247 H{x+54} M{x+8} 259 H{x+54} M{x+8} 271 H{x+54}" stroke="#fff" stroke-width="3"/>'
posterB+='<rect x="298" y="307" width="25" height="36" fill="#546171"/><text x="320" y="369" text-anchor="middle" fill="#26384e" font-family="Arial,sans-serif" font-size="16">Thursday late session · 5–8 pm · Free entry</text>'
VISUALS['posterA']=dict(title='Poster A: invitation',svg=svg('Original library poster: invitation',posterA),explain='Original visual stimulus. A bright central doorway casts light towards a small figure. The headline and hours panel belong to the poster.',limit='Fictional service and hours; the drawing does not document an actual library.')
VISUALS['posterB']=dict(title='Poster B: transactions',svg=svg('Original library poster: transactions',posterB),explain='Original visual stimulus. A large fictional annual total and identical book icons dominate. A small doorway and hours line receive less emphasis.',limit='The total is invented. Popularity or output alone does not establish accessibility.')
